//! Bare nested do elements share their enclosing return/loop scope. A normal
//! result resumes a checked value continuation; an early return bypasses it.
//! Parenthesized term-do expressions never enter this path.
use super::*;

pub(super) fn complete(action: Syntax, continuation: Syntax) -> Syntax {
    Syntax::node(
        parser_kind(&["Term", "nativeDoNestedAction"]),
        vec![action, continuation],
    )
}

/// Read the sole binder generated by the ordinary do-binding constructor.
/// An explicit annotation constrains the normal action before its elaboration;
/// the continuation body itself is checked only after that action's domain.
pub(in crate::source) fn bind_join_domain(
    continuation: &Syntax,
) -> Result<Option<&Syntax>, NatDefinitionElabError> {
    let parts = expect_node(
        continuation,
        &parser_kind(&["Term", "fun"]),
        2,
        "nested do continuation",
    )?;
    expect_atom(&parts[0], "fun", "nested do continuation keyword")?;
    let parts = expect_node(
        &parts[1],
        &parser_kind(&["Term", "basicFun"]),
        4,
        "nested do continuation body",
    )?;
    let [binder] = expect_null_args(&parts[0], "nested do continuation binder")? else {
        return Err(invalid());
    };
    if matches!(binder, Syntax::Ident { .. }) {
        return Ok(None);
    }
    let parts = expect_node(
        binder,
        &parser_kind(&["Term", "typeAscription"]),
        5,
        "nested do binder annotation",
    )?;
    let [domain] = expect_null_args(&parts[3], "nested do binder type")? else {
        return Err(invalid());
    };
    Ok(Some(domain))
}

pub(super) fn sequence(element: &Syntax) -> Option<&Syntax> {
    let element = if element.kind() == Some(&parser_kind(&["Term", "doLetArrow"])) {
        let Syntax::Node { args, .. } = element else {
            return None;
        };
        let Syntax::Node { kind, args, .. } = args.get(3)? else {
            return None;
        };
        if kind != &parser_kind(&["Term", "doIdDecl"])
            && kind != &parser_kind(&["Term", "doPatDecl"])
        {
            return None;
        }
        args.get(3)?
    } else {
        element
    };
    let Syntax::Node { kind, args, .. } = element else {
        return None;
    };
    (kind == &parser_kind(&["Term", "doNested"]) && args.len() == 2).then(|| &args[1])
}

pub(super) struct Nested {
    pub sequence: Syntax,
    pub completion: Option<Syntax>,
    pub join: Option<(Syntax, Syntax)>,
}

impl Context {
    /// The checked Pure/Bind/exception telescope chooses its still-unknown monad and
    /// result parameters from the written expected application before aliases
    /// such as Id erase that application. This is the same typed parameter
    /// choice as nativeDoPure; it also applies to written Pure.pure calls and
    /// to Bind's continuation. Already chosen result parameters are left to
    /// ordinary conversion: a monad need not be injective in that parameter.
    pub(in crate::source) fn do_operation_result_hint(
        &mut self,
        function: &Typed,
        result: &Expr,
        expected: &Expr,
    ) -> Result<(), NatDefinitionElabError> {
        let mut head = &function.value;
        let mut supplied = 0_usize;
        while let ExprNode::App { f, .. } = head.node() {
            self.tick()?;
            supplied = supplied.checked_add(1).ok_or_else(invalid)?;
            head = f;
        }
        let ExprNode::Const { name, .. } = head.node() else {
            return Ok(());
        };
        if name != &Name::from_components(["Pure", "pure"])
            && name != &Name::from_components(["Bind", "bind"])
            && name != &Name::from_components(["MonadExcept", "tryCatch"])
            && name != &Name::from_components(["tryCatchThe"])
        {
            return Ok(());
        }
        let Some(info) = self.txn.env.find(name) else {
            return Ok(());
        };
        let mut telescope = info.constant_val().type_.clone();
        let mut parameters = 0_usize;
        while let ExprNode::ForallE { body, .. } = telescope.node() {
            self.tick()?;
            parameters = parameters.checked_add(1).ok_or_else(invalid)?;
            telescope = body.clone();
        }
        // A function-valued operation can be overapplied. Its later arguments
        // are outside the declared operation's own parameter choices.
        if supplied.checked_add(1) != Some(parameters) {
            return Ok(());
        }
        let result = self.instantiate(result)?;
        let expected = self.instantiate(expected)?;
        let (
            ExprNode::App {
                f: monad,
                a: result,
            },
            ExprNode::App {
                f: expected_monad,
                a: expected_result,
            },
        ) = (result.node(), expected.node())
        else {
            return Ok(());
        };
        if matches!(monad.node(), ExprNode::MVar { .. }) {
            self.constrain_type(monad, expected_monad)?;
        } else if monad != expected_monad {
            return Ok(());
        }
        if matches!(result.node(), ExprNode::MVar { .. }) {
            self.constrain_type(result, expected_result)?;
        }
        Ok(())
    }

    /// Choose Bind's action result parameter from the checked continuation,
    /// before elaborating the action. This is a typed parameter choice, not
    /// an assumption that the monad is injective (Id may erase its head).
    pub(in crate::source) fn do_nested_action_function(
        &mut self,
        function: Typed,
        continuation: &Syntax,
    ) -> Result<Typed, NatDefinitionElabError> {
        let Syntax::Ident { val: name, .. } = continuation else {
            return Err(invalid());
        };
        if !name.parent().is_anonymous()
            || !matches!(name.leaf_view(), fln_core::name::LeafView::Num(_))
        {
            return Err(invalid());
        }
        let local = self.txn.lctx.find_by_user_name(name).ok_or_else(invalid)?;
        let continuation_type = self.instantiate(&local.type_.clone())?;
        let ExprNode::ForallE {
            binder_type: domain,
            ..
        } = continuation_type.node()
        else {
            return Err(invalid());
        };
        let function = self.insert_implicits(function, ImplicitInsertion::ExplicitArgument)?;
        let function = self.coerce_function(function)?;
        let ExprNode::ForallE { binder_type, .. } = function.type_.node() else {
            return Err(invalid());
        };
        let binder_type = self.instantiate(binder_type)?;
        let ExprNode::App { a: parameter, .. } = binder_type.node() else {
            return Err(invalid());
        };
        self.constrain_type(parameter, domain)?;
        Ok(function)
    }

    pub(super) fn prepare_nested_do(
        &mut self,
        mut element: Syntax,
        suffix: Option<Syntax>,
        completion: Option<Syntax>,
        scope: SequenceScope<'_>,
    ) -> Result<Nested, NatDefinitionElabError> {
        self.tick()?;
        let binding = element.kind() == Some(&parser_kind(&["Term", "doLetArrow"]));
        let (nested, continuation) = if binding {
            let suffix = suffix.ok_or_else(invalid)?;
            // Reuse ordinary named/pattern-bind checking to build the value
            // continuation. The temporary action is never elaborated or run.
            let Syntax::Node { args, .. } = &mut element else {
                return Err(invalid());
            };
            let Some(Syntax::Node {
                args: declaration, ..
            }) = args.get_mut(3)
            else {
                return Err(invalid());
            };
            let action = declaration.get_mut(3).ok_or_else(invalid)?;
            let nested = std::mem::replace(
                action,
                Syntax::node(parser_kind(&["Term", "doExpr"]), vec![atom("_")]),
            );
            let expanded = self.prepend_do_element(element, Some(suffix), scope, false)?;
            let mut args = node(expanded, "nativeDoBind", 2)?;
            (nested, Some(args.pop().expect("bind continuation")))
        } else {
            let continuation = suffix
                .map(|suffix| {
                    let ignored = self.do_control_name()?;
                    lambda(ignored, unit_annotation(), suffix)
                })
                .transpose()?;
            (element, continuation)
        };
        let mut parts = node(nested, "doNested", 2)?;
        expect_atom(&parts[0], "do", "nested do keyword")?;
        let sequence = parts.pop().expect("nested do sequence");
        let (completion, join) = match continuation {
            Some(continuation) => {
                let name = self.do_control_name()?;
                (Some(name.clone()), Some((name, continuation)))
            }
            None => (completion, None),
        };
        Ok(Nested {
            sequence,
            completion,
            join,
        })
    }

    /// Fresh continuation identities cannot be shadowed by user syntax. A
    /// syntactically unreachable continuation is omitted before elaboration,
    /// matching the pin's deadSyntactically path; no runtime test decides this.
    pub(super) fn do_syntax_uses(
        &mut self,
        syntax: &Syntax,
        identifier: &Syntax,
    ) -> Result<bool, NatDefinitionElabError> {
        let Syntax::Ident { val: wanted, .. } = identifier else {
            return Err(invalid());
        };
        let mut work = vec![syntax];
        while let Some(syntax) = work.pop() {
            self.tick()?;
            match syntax {
                Syntax::Ident { val, .. } if val == wanted => return Ok(true),
                Syntax::Node { args, .. } => work.extend(args),
                _ => {}
            }
        }
        Ok(false)
    }
}
