#!/usr/bin/env bash
# G0-9 no-mock e2e: regenerate every committed trace fixture from the REAL pinned
# Reference binary and hold byte-identity, with a negative control proving the
# comparison can fail (bead franken_lean-foo; plan §18.3, §22.1-9).
#
# This is the provenance half of the golden-trace loop: the committed fixtures in
# crates/fln-conformance/fixtures/ are the pinned binary's own output, and this
# script is the deliberate regeneration act the module docs name. The validation
# half (parse totality, family checkers, replay) lives in the trace_replay tests.
#
# On-demand, like the corpus thread-matrix lane: needs the pin installed, ~seconds
# of wall. Receipt: NDJSON, schema fln-g09-trace-regen/1, written to
# crates/fln-conformance/evidence/g09_trace_replay/regen_<tag>.jsonl.
set -u -o pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
FIXTURES="$ROOT/crates/fln-conformance/fixtures"
SCRATCH="${TMPDIR:-/tmp}/g09-trace-regen.$$"

fail() {
  printf '[g09_trace_regen] REFUSED: %s\n' "$*" >&2
  exit 2
}

# --- pin resolution, exactly as ref_vs_ref.sh derives it -----------------------
mapfile -t rows < <(grep -E '^reference ' "$ROOT/SUITE.lock")
[ "${#rows[@]}" -eq 1 ] || fail "SUITE.lock must have exactly one Reference row"
PIN_TAG=""
for field in ${rows[0]}; do
  case "$field" in
    tag=*) PIN_TAG="${field#tag=}" ;;
  esac
done
[[ "$PIN_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+([.-][A-Za-z0-9.-]+)?$ ]] \
  || fail "Reference tag is malformed: $PIN_TAG"
LEAN="$HOME/.elan/toolchains/leanprover--lean4---$PIN_TAG/bin/lean"
[ -x "$LEAN" ] || fail "pinned Reference binary is not installed at $LEAN"

mkdir -p "$SCRATCH" || fail "cannot create scratch $SCRATCH"
RECEIPT="$SCRATCH/receipt.jsonl"
: > "$RECEIPT"

sha() { sha256sum "$1" | cut -d' ' -f1; }

emit() {
  printf '%s\n' "$1" >> "$RECEIPT"
}

# --- one fixture pair: run twice, compare run-vs-run and run-vs-committed ------
regen() {
  local name="$1" source="$2" committed="$3"
  shift 3
  local out1="$SCRATCH/$name.run1" out2="$SCRATCH/$name.run2"
  local t0 t1 rc=0
  t0=$(date +%s%3N)
  env -u LEAN_PATH -u LEAN_SYSROOT LC_ALL=C TZ=UTC \
    "$LEAN" "$@" "$FIXTURES/$source" > "$out1" 2>&1 || rc=$?
  t1=$(date +%s%3N)
  [ "$rc" -eq 0 ] || fail "$name: pinned binary exited $rc on run 1"
  env -u LEAN_PATH -u LEAN_SYSROOT LC_ALL=C TZ=UTC \
    "$LEAN" "$@" "$FIXTURES/$source" > "$out2" 2>&1 || rc=$?
  [ "$rc" -eq 0 ] || fail "$name: pinned binary exited $rc on run 2"
  cmp -s "$out1" "$out2" || fail "$name: two runs of the pinned binary DIVERGED"
  cmp -s "$out1" "$FIXTURES/$committed" \
    || fail "$name: regenerated trace differs from committed $committed — the fixture has drifted from the pin, or the pin moved; regenerate deliberately and land both together"
  emit "{\"schema\":\"fln-g09-trace-regen/1\",\"step\":\"$name\",\"source\":\"$source\",\"fixture\":\"$committed\",\"sha256\":\"$(sha "$out1")\",\"runs_identical\":true,\"fixture_identical\":true,\"wall_ms\":$((t1 - t0))}"
}

regen pilot g09_pilot.lean g09_pilot_trace.txt \
  -D trace.Meta.isDefEq=true
regen multi_family g09_multi_family.lean g09_multi_family_trace.txt \
  -D trace.Meta.isDefEq=true -D trace.Meta.synthInstance=true \
  -D trace.Meta.Tactic.simp=true -D trace.Elab.step=true -D trace.Elab.postpone=true
regen diag g09_diag.lean g09_diag_trace.txt

# --- negative control: a corrupted copy MUST fail the comparison ---------------
# Without this cell a broken cmp invocation would report every fixture identical.
cp "$SCRATCH/pilot.run1" "$SCRATCH/pilot.corrupt"
printf 'X' >> "$SCRATCH/pilot.corrupt"
if cmp -s "$SCRATCH/pilot.corrupt" "$FIXTURES/g09_pilot_trace.txt"; then
  fail "negative control PASSED the comparison — the comparison is broken"
fi
emit '{"schema":"fln-g09-trace-regen/1","step":"negative_control","corrupted_copy_detected":true}'

emit "{\"schema\":\"fln-g09-trace-regen/1\",\"step\":\"summary\",\"pin\":\"$PIN_TAG\",\"fixtures\":3,\"verdict\":\"all-identical\"}"

DEST="$ROOT/crates/fln-conformance/evidence/g09_trace_replay/regen_$PIN_TAG.jsonl"
mkdir -p "$(dirname "$DEST")"
cp "$RECEIPT" "$DEST"
printf '[g09_trace_regen] OK: 3 fixtures regenerated byte-identical at %s; receipt %s\n' \
  "$PIN_TAG" "$DEST"
