[package]
name = "fln"
version = "0.0.0"
edition = "2024"
license = "LicenseRef-MIT-OpenAI-Anthropic-Rider"
publish = false

[dependencies]
fln-comp = { path = "../fln-comp" }
fln-checker = { path = "../fln-checker" }
fln-core = { path = "../fln-core" }
fln-elab = { path = "../fln-elab" }
fln-env = { path = "../fln-env" }
fln-hash = { path = "../fln-hash" }
fln-kernel = { path = "../fln-kernel" }
fln-olean = { path = "../fln-olean" }
fln-parse = { path = "../fln-parse" }
fln-vm = { path = "../fln-vm" }
