//! The poison boundary and the release reachability scan — D8, the Oracle-Only
//! Law, made mechanical (bead `fln-rzyk`, carved out of `fln-euo`; plan §18).
//!
//! # The failure this prevents
//!
//! **A release binary that quietly consults the Reference.** That is the one
//! thing the whole project is built to avoid: FrankenLean is a ground-up
//! reimplementation, and a shipped artifact that falls back to `lean` is not a
//! reimplementation at all — it is a wrapper wearing one's clothes. The
//! development-only lockstep harness exists, and it "poisons everything it
//! touches with [`ORACLE_FALLBACK`], satisfies no gate, and is compiled out of
//! releases — with a CI check proving its absence". This module is that check's
//! model and its laws.
//!
//! # Two halves, and the second is the one that matters
//!
//! **Poison typing.** Every oracle-derived product is poison-typed and
//! inadmissible to any gate or cache, and poison PROPAGATES: anything derived
//! from a poisoned input is poisoned, transitively and without exception.
//! [`Poisoned<T>`] has no `into_inner`, no `Deref`, and no `unwrap`-shaped
//! escape — the only way to read the value is [`Poisoned::inspect_for_diagnosis`],
//! whose name is the argument against using it anywhere else.
//!
//! **The release reachability scan.** [`scan`] enumerates every shippable
//! target × profile × feature combination and proves no oracle capability is
//! reachable from any of them, and that no unpoisoned oracle-derived product
//! exists.
//!
//! # Exhaustive, not sampled — and an incomplete scan is Inconclusive
//!
//! A reachability scan that misses one feature flag is **worse than none**,
//! because it certifies what it did not check. So:
//!
//! - the feature dimension is the **powerset** of the optional features, not
//!   merely `--no-default-features` and `--all-features`;
//! - [`ScanOutcome::Clean`] carries `combinations_checked`, and [`scan`] refuses
//!   to emit it unless that number equals `shippable × profiles × 2^features`;
//! - if the powerset exceeds [`ENUMERATION_BUDGET`], the outcome is
//!   [`ScanOutcome::Inconclusive`] — never a pass.
//!
//! That last point is FL-INV-07 applied to the scan itself, and it is the same
//! law [`crate::oracle`] establishes for the Reference: a non-answer is never an
//! answer. A scan that cannot enumerate its space has not cleared the release;
//! it has failed to look.
//!
//! # False positives are a failure mode too
//!
//! Development-only Tribunal targets **may** contain oracle machinery — that is
//! where the oracle is supposed to live. A scan that flags them cries wolf, and
//! a gate that cries wolf gets routed around. [`Shippability`] is therefore a
//! property of the target, checked before anything else, and the suite tests
//! both directions.

use std::collections::BTreeSet;

/// The marker a poisoned product carries. Named to match the doctrine so a
/// grep for it finds both the law and its enforcement.
pub const ORACLE_FALLBACK: &str = "ORACLE_FALLBACK";

/// The largest number of (target, profile, feature-set) combinations [`scan`]
/// will enumerate before refusing to answer.
///
/// Exceeding it is [`ScanOutcome::Inconclusive`], not a sampled pass. The
/// number is deliberately generous — a real workspace that exceeds it has a
/// feature-count problem that a reachability gate should surface rather than
/// paper over.
pub const ENUMERATION_BUDGET: u64 = 1 << 20;

/// Where a product came from. A closed vocabulary, separate from every other.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Provenance {
    /// Authored in this repository, owing nothing to the Reference.
    OwnWork,
    /// Extracted from, generated by, or observed from the Reference. Poisoned
    /// on arrival, whatever it looks like.
    OracleDerived,
}

/// Whether a target can ever be shipped.
///
/// Checked FIRST in the scan. Development-only targets may contain oracle
/// machinery; flagging them is a false positive, and a gate that produces false
/// positives is a gate people learn to ignore.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Shippability {
    /// Reachable by a user of a released artifact.
    Shippable,
    /// Compiled only in development; absent from every released artifact. The
    /// lockstep harness lives here and is *supposed* to.
    DevelopmentOnly,
}

/// A Cargo target kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TargetKind {
    Lib,
    Bin,
    Test,
    Bench,
    Example,
    BuildScript,
}

/// A build profile.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Profile {
    Dev,
    Release,
    /// `--reproducible`, which additionally forbids the two inherited external
    /// tools of D2.
    ReproducibleRelease,
}

/// A capability that would put the Reference inside a running FrankenLean.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OracleCapability {
    /// Spawning the pinned `lean`/`leanc`/`leanchecker` binary.
    SpawnReferenceBinary,
    /// Linking a symbol from `libleanshared`.
    LinkReferenceSymbol,
    /// Reading a Reference artifact as an authority rather than as data.
    ReadReferenceArtifact,
    /// The development-only lockstep fallback path.
    OracleFallback,
}

impl OracleCapability {
    pub fn as_str(self) -> &'static str {
        match self {
            OracleCapability::SpawnReferenceBinary => "spawn-reference-binary",
            OracleCapability::LinkReferenceSymbol => "link-reference-symbol",
            OracleCapability::ReadReferenceArtifact => "read-reference-artifact",
            OracleCapability::OracleFallback => "oracle-fallback",
        }
    }
}

/// One build target.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Target {
    pub crate_name: String,
    pub name: String,
    pub kind: TargetKind,
    pub shippability: Shippability,
}

impl Target {
    /// How this target is named in scan output.
    pub fn label(&self) -> String {
        format!("{}::{}", self.crate_name, self.name)
    }
}

/// A path from a target to an oracle capability, gated on features.
///
/// `requires` is the set of features that must ALL be enabled for the path to
/// exist. An empty set means the path is always there — including under default
/// features, which is the only case a naive scan would catch.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OracleEdge {
    pub target: String,
    pub capability: OracleCapability,
    pub requires: BTreeSet<String>,
}

/// A build product with its provenance and poison state.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Product {
    pub name: String,
    pub provenance: Provenance,
    /// Whether this product carries the poison marker. The law is that
    /// `OracleDerived` implies `poisoned`; a product that violates it is the
    /// "unpoisoned product" the epic names as a mutant.
    pub poisoned: bool,
}

impl Product {
    /// May this product be offered to a gate as evidence?
    ///
    /// Reads `poisoned` only. A poisoned product satisfies no gate — that is
    /// the doctrine's word, and it is not conditional on provenance, profile or
    /// anybody's intent.
    pub fn admissible_to_gate(&self) -> bool {
        !self.poisoned
    }

    /// May this product be cached?
    ///
    /// Same answer, separate question. A cached poisoned product is worse than
    /// an admitted one, because the cache outlives the run that made it and
    /// nothing downstream can tell where it came from.
    pub fn cacheable(&self) -> bool {
        !self.poisoned
    }
}

/// A value that came from, or was derived from, the Reference.
///
/// There is deliberately no `into_inner`, no `Deref`, no `AsRef`, and no `From`
/// back to `T`. Poison that can be removed is not poison — it is a label, and a
/// label is exactly what D8 says is not enough. The single accessor is named
/// [`Poisoned::inspect_for_diagnosis`] so that any use of it reads, at the call
/// site, as the argument it needs to be.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Poisoned<T> {
    value: T,
    marker: &'static str,
}

impl<T> Poisoned<T> {
    /// Poison a value on arrival from the oracle.
    pub fn new(value: T) -> Poisoned<T> {
        Poisoned {
            value,
            marker: ORACLE_FALLBACK,
        }
    }

    /// The marker, for reporting.
    pub fn marker(&self) -> &'static str {
        self.marker
    }

    /// Look at the value for diagnosis only.
    ///
    /// Named for what it is for. This exists because a poisoned artifact still
    /// has to be triageable — you must be able to see WHAT leaked — and not
    /// because there is a legitimate way to use the value.
    pub fn inspect_for_diagnosis(&self) -> &T {
        &self.value
    }

    /// Derive a new value. The result is poisoned, because it is derived from
    /// something poisoned.
    ///
    /// This is the propagation law with teeth: the only `map`-shaped operation
    /// on a `Poisoned` returns a `Poisoned`, so there is no chain of ordinary
    /// combinators that ends in a clean value.
    pub fn derive<U>(&self, f: impl FnOnce(&T) -> U) -> Poisoned<U> {
        Poisoned::new(f(&self.value))
    }
}

/// Poison a product, and everything derived from it.
///
/// `inputs` are the provenances of everything that fed this product. The rule
/// is transitive by construction: a product is poisoned if it is itself
/// oracle-derived OR if any input was poisoned.
pub fn derive_product(name: &str, own: Provenance, inputs: &[&Product]) -> Product {
    let inherited = inputs.iter().any(|p| p.poisoned);
    Product {
        name: name.to_string(),
        provenance: own,
        poisoned: own == Provenance::OracleDerived || inherited,
    }
}

/// The inventory a scan runs over.
///
/// In production this is generated from `cargo metadata`; here it is supplied,
/// which is the seam a CI lane plugs into. `features` is the union of optional
/// features considered — the powerset of THIS set is the feature dimension.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Inventory {
    pub targets: Vec<Target>,
    pub profiles: Vec<Profile>,
    pub features: Vec<String>,
    pub edges: Vec<OracleEdge>,
    pub products: Vec<Product>,
}

/// One way a release is not clear.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Leak {
    /// A shippable target can reach an oracle capability under some
    /// combination. Carries the exact combination, so the finding is
    /// reproducible rather than a claim.
    ReachableCapability {
        target: String,
        capability: OracleCapability,
        profile: Profile,
        features: Vec<String>,
    },
    /// An oracle-derived product that is not poison-typed.
    UnpoisonedProduct { name: String },
    /// A poisoned product that something nevertheless treats as admissible.
    PoisonedProductAdmitted { name: String },
    /// An edge naming a target the inventory does not contain: the scan cannot
    /// classify it, so it must not silently ignore it.
    DanglingEdge { target: String },
}

impl Leak {
    pub fn reason(&self) -> &'static str {
        match self {
            Leak::ReachableCapability { .. } => "reachable-capability",
            Leak::UnpoisonedProduct { .. } => "unpoisoned-product",
            Leak::PoisonedProductAdmitted { .. } => "poisoned-product-admitted",
            Leak::DanglingEdge { .. } => "dangling-edge",
        }
    }
}

/// Why a scan could not answer.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Incomplete {
    /// The enumeration space exceeds [`ENUMERATION_BUDGET`].
    BudgetExceeded { required: u64, budget: u64 },
    /// The inventory declares no profiles, so "every profile" is vacuous and a
    /// pass would mean nothing.
    NoProfiles,
    /// The enumeration visited a different number of combinations than the
    /// space contains. An internal fault: the scan contradicted itself, and
    /// FL-INV-07 says that is a typed outcome rather than a panic.
    CountMismatch { visited: u64, expected: u64 },
    /// The walk exceeded the budget that the pre-walk check was supposed to
    /// have refused. Distinct from [`Incomplete::BudgetExceeded`] on purpose:
    /// that one is an honest refusal made before any work, this one means the
    /// pre-walk arithmetic was WRONG and the fallback guard had to stop a
    /// runaway. It should never be observed, and if it is, the bug is in the
    /// size computation rather than in the inventory.
    EnumerationRunaway { visited: u64, budget: u64 },
}

/// What a scan concluded.
///
/// Three outcomes, not two. [`ScanOutcome::Inconclusive`] is NOT a pass and is
/// not a leak: it is the scan saying it failed to look, which is the only
/// honest thing to report when the space could not be enumerated.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ScanOutcome {
    Clean {
        combinations_checked: u64,
        shippable_targets: usize,
    },
    Leaks(Vec<Leak>),
    Inconclusive(Incomplete),
}

impl ScanOutcome {
    /// Whether this outcome clears a release. Only `Clean` does.
    pub fn clears_release(&self) -> bool {
        matches!(self, ScanOutcome::Clean { .. })
    }

    pub fn verdict(&self) -> &'static str {
        match self {
            ScanOutcome::Clean { .. } => "pass",
            ScanOutcome::Leaks(_) => "fail",
            ScanOutcome::Inconclusive(_) => "inconclusive",
        }
    }
}

/// Every subset of `features`, in a deterministic order.
///
/// Index `i` selects the features whose bit is set in `i`, so the sequence is a
/// function of the input alone — no clock, no hash order, replayable.
fn powerset(features: &[String]) -> impl Iterator<Item = Vec<String>> + '_ {
    let n = features.len();
    (0u64..(1u64 << n)).map(move |mask| {
        (0..n)
            .filter(|b| mask & (1u64 << b) != 0)
            .map(|b| features[b].clone())
            .collect()
    })
}

/// Run the release reachability scan.
///
/// Enumerates every shippable target × profile × feature subset. Development-
/// only targets are skipped BEFORE anything else, because they are allowed to
/// contain the machinery and flagging them is a false positive.
pub fn scan(inv: &Inventory) -> ScanOutcome {
    if inv.profiles.is_empty() {
        return ScanOutcome::Inconclusive(Incomplete::NoProfiles);
    }

    let shippable: Vec<&Target> = inv
        .targets
        .iter()
        .filter(|t| t.shippability == Shippability::Shippable)
        .collect();

    // The size of the space, computed BEFORE walking it, so the walk can be
    // checked against it rather than trusted.
    let feature_combinations = if inv.features.len() >= 64 {
        u64::MAX
    } else {
        1u64 << inv.features.len()
    };
    let expected = (shippable.len() as u64)
        .saturating_mul(inv.profiles.len() as u64)
        .saturating_mul(feature_combinations);
    if feature_combinations > ENUMERATION_BUDGET || expected > ENUMERATION_BUDGET {
        return ScanOutcome::Inconclusive(Incomplete::BudgetExceeded {
            required: expected,
            budget: ENUMERATION_BUDGET,
        });
    }

    let mut leaks = Vec::new();

    // DANGLING EDGE. An edge naming an unknown target cannot be classified as
    // shippable or development-only, so ignoring it would be assuming the
    // answer that happens to be convenient.
    let known: BTreeSet<&str> = inv.targets.iter().map(|t| t.name.as_str()).collect();
    for e in &inv.edges {
        if !known.contains(e.target.as_str()) {
            leaks.push(Leak::DanglingEdge {
                target: e.target.clone(),
            });
        }
    }

    let mut visited: u64 = 0;
    for target in &shippable {
        let edges: Vec<&OracleEdge> = inv
            .edges
            .iter()
            .filter(|e| e.target == target.name)
            .collect();
        for profile in &inv.profiles {
            for features in powerset(&inv.features) {
                visited += 1;
                // A SECOND, INDEPENDENT budget guard, and it reports a
                // DIFFERENT reason on purpose. The pre-walk check above is the
                // honest refusal — it declines before doing any work — but it
                // was also the only thing standing between this loop and 2^n
                // iterations, and removing it turned the scan into a hang
                // rather than a wrong answer. A gate that hangs is caught by a
                // CI timeout instead of by a named test, which is a far weaker
                // signal, so termination is now guaranteed structurally.
                //
                // Reporting `EnumerationRunaway` rather than `BudgetExceeded`
                // keeps the two guards distinguishable: if this one ever fires,
                // the pre-walk arithmetic was wrong, which is our bug and not
                // the inventory's. Collapsing them would also make the pre-walk
                // check unobservable — a mutation deleting it would produce an
                // identical outcome, and the campaign would stop being able to
                // tell whether it was still there.
                if visited > ENUMERATION_BUDGET {
                    return ScanOutcome::Inconclusive(Incomplete::EnumerationRunaway {
                        visited,
                        budget: ENUMERATION_BUDGET,
                    });
                }
                let enabled: BTreeSet<&str> = features.iter().map(String::as_str).collect();
                for e in &edges {
                    // Reachable when every feature the path needs is enabled.
                    // An edge requiring nothing is reachable in every
                    // combination, including the default one; an edge requiring
                    // a single non-default feature is reachable in half of
                    // them and in NONE of the ones a default-only scan visits.
                    if e.requires.iter().all(|f| enabled.contains(f.as_str())) {
                        leaks.push(Leak::ReachableCapability {
                            target: target.label(),
                            capability: e.capability,
                            profile: *profile,
                            features: features.clone(),
                        });
                    }
                }
            }
        }
    }

    // PRODUCTS. Oracle-derived implies poisoned, and poisoned implies
    // inadmissible. Two separate checks because they are two separate lies.
    for p in &inv.products {
        if p.provenance == Provenance::OracleDerived && !p.poisoned {
            leaks.push(Leak::UnpoisonedProduct {
                name: p.name.clone(),
            });
        }
        if p.poisoned && (p.admissible_to_gate() || p.cacheable()) {
            leaks.push(Leak::PoisonedProductAdmitted {
                name: p.name.clone(),
            });
        }
    }

    if !leaks.is_empty() {
        return ScanOutcome::Leaks(leaks);
    }

    // COMPLETENESS. A clean verdict is only emitted if the walk visited exactly
    // the space that was computed. Anything else means the scan certified what
    // it did not check, which is the thing this module exists to prevent.
    if visited != expected {
        return ScanOutcome::Inconclusive(Incomplete::CountMismatch { visited, expected });
    }

    ScanOutcome::Clean {
        combinations_checked: visited,
        shippable_targets: shippable.len(),
    }
}

/// Line-oriented scan report. Machine-first, no decoration.
pub fn report(outcome: &ScanOutcome) -> String {
    let mut out = String::new();
    match outcome {
        ScanOutcome::Clean {
            combinations_checked,
            shippable_targets,
        } => out.push_str(&format!(
            "oracle-reachability: verdict=pass combinations={combinations_checked} \
             shippable_targets={shippable_targets}\n"
        )),
        ScanOutcome::Leaks(leaks) => {
            for l in leaks {
                out.push_str(&format!(
                    "oracle-reachability: leak reason={} {l:?}\n",
                    l.reason()
                ));
            }
            out.push_str(&format!(
                "oracle-reachability: verdict=fail leaks={}\n",
                leaks.len()
            ));
        }
        ScanOutcome::Inconclusive(why) => out.push_str(&format!(
            "oracle-reachability: verdict=inconclusive reason={why:?}\n"
        )),
    }
    out
}

#[cfg(test)]
mod structural {
    use super::*;

    #[test]
    fn the_powerset_is_complete_and_deterministic() {
        let f: Vec<String> = ["a", "b", "c"].iter().map(|s| s.to_string()).collect();
        let once: Vec<Vec<String>> = powerset(&f).collect();
        assert_eq!(once.len(), 8, "powerset of 3 features must have 8 members");
        let twice: Vec<Vec<String>> = powerset(&f).collect();
        assert_eq!(once, twice, "the powerset order is not deterministic");
        // Every subset appears exactly once.
        let mut sets: Vec<BTreeSet<String>> =
            once.iter().map(|v| v.iter().cloned().collect()).collect();
        sets.sort();
        sets.dedup();
        assert_eq!(sets.len(), 8, "the powerset repeats or omits a subset");
    }

    #[test]
    fn an_inconclusive_scan_does_not_clear_a_release() {
        // The whole point of having three outcomes instead of two.
        assert!(!ScanOutcome::Inconclusive(Incomplete::NoProfiles).clears_release());
        assert!(
            !ScanOutcome::Inconclusive(Incomplete::BudgetExceeded {
                required: 1,
                budget: 0
            })
            .clears_release()
        );
        assert!(!ScanOutcome::Leaks(vec![]).clears_release());
        assert!(
            ScanOutcome::Clean {
                combinations_checked: 1,
                shippable_targets: 1
            }
            .clears_release()
        );
    }

    #[test]
    fn every_leak_variant_has_its_own_reason_token() {
        let all = [
            Leak::ReachableCapability {
                target: String::new(),
                capability: OracleCapability::OracleFallback,
                profile: Profile::Release,
                features: vec![],
            },
            Leak::UnpoisonedProduct {
                name: String::new(),
            },
            Leak::PoisonedProductAdmitted {
                name: String::new(),
            },
            Leak::DanglingEdge {
                target: String::new(),
            },
        ];
        let mut t: Vec<&str> = all.iter().map(Leak::reason).collect();
        let before = t.len();
        t.sort_unstable();
        t.dedup();
        assert_eq!(before, t.len(), "two Leak variants share a reason token");
    }
}
