//! Differential comparison against the pinned Reference for the fln-core surfaces
//! the C0 corpus does not reach (bead fln-it70).
//!
//! `fixtures/core_ext_observables.txt` is produced by
//! `scripts/extract/gen_core_ext_fixtures.lean`, run through its wrapper
//! `scripts/extract/gen_core_ext_fixtures.sh` under the pinned Reference binary
//! (bead `franken_lean-eh0c` moved the generator into the sanctioned home for
//! extraction scripts). Every record below is a value the Reference computed; this
//! file recomputes it with fln-core and compares. That is what moves the Parity
//! Ledger rows for these symbols from L1 (implemented against pinned SOURCE, in-repo
//! tests) to L2 (the pinned BINARY produced the expected value and we compare on
//! every run).
//!
//! Three guards keep the fixture honest:
//!
//! * the commit recorded in its header is checked against `SUITE.lock`, so a fixture
//!   generated by any binary other than the pin fails instead of being trusted;
//! * the generator the header names must still exist at that path, so relocating it
//!   without re-deriving the fixture fails here rather than leaving the artifact
//!   citing provenance nobody can reach;
//! * an unrecognised label is a failure, never a skip — the corpora cannot drift
//!   apart by one side quietly ignoring what the other emits.
//!
//! No dependency is added: fln-core is rank 0 in ci/WORKSPACE_GRAPH.txt with zero
//! dependency edges, and this is std-only text handling over checked-in files.

#![forbid(unsafe_code)]

use std::collections::BTreeSet;

use fln_core::level::{LMVarId, Level, LevelView};
use fln_core::name::Name;
use fln_core::options::{DataValue, KVMap};
use fln_core::pos::{FileMap, Position, RawPos};

const FIXTURE: &str = include_str!("../fixtures/core_ext_observables.txt");
const SUITE_LOCK: &str = include_str!("../../../SUITE.lock");

fn name_case(label: &str) -> Option<Name> {
    let anon = Name::anonymous;
    Some(match label {
        "anon" => anon(),
        "a" => Name::str(anon(), "a"),
        "b" => Name::str(anon(), "b"),
        "a.b" => Name::str(Name::str(anon(), "a"), "b"),
        "a.c" => Name::str(Name::str(anon(), "a"), "c"),
        "a.b.c" => Name::str(Name::str(Name::str(anon(), "a"), "b"), "c"),
        "n0" => Name::num(anon(), 0),
        "n1" => Name::num(anon(), 1),
        "a.n7" => Name::num(Name::str(anon(), "a"), 7),
        "a.n7.b" => Name::str(Name::num(Name::str(anon(), "a"), 7), "b"),
        _ => return None,
    })
}

fn hygienic_case(label: &str) -> Option<Name> {
    let anon = Name::anonymous;
    let foo_bar = Name::str(Name::str(anon(), "Foo"), "bar");
    Some(match label {
        "plain" => foo_bar,
        "hyg1" => Name::num(Name::str(Name::str(foo_bar, "_@"), "_hyg"), 7),
        "hyg2" => Name::num(Name::num(Name::str(Name::str(foo_bar, "_@"), "_hyg"), 7), 9),
        "hyg_with_module" => Name::num(
            Name::str(
                Name::str(Name::str(Name::str(anon(), "Foo"), "_@"), "Mod"),
                "_hyg",
            ),
            3,
        ),
        "hyg_no_sep" => Name::num(Name::str(anon(), "_hyg"), 1),
        "marker_only" => Name::str(anon(), "_hyg"),
        _ => return None,
    })
}

fn level_case(label: &str) -> Option<Level> {
    let u = || Level::param(Name::str(Name::anonymous(), "u"));
    let v = || Level::param(Name::str(Name::anonymous(), "v"));
    let packs = "the corpus is shallow";
    Some(match label {
        "zero" => Level::zero(),
        "one" => Level::zero().succ().expect(packs),
        "u" => u(),
        "v" => v(),
        "m" => Level::mvar(LMVarId(Name::str(Name::anonymous(), "m"))),
        "succ_u" => u().succ().expect(packs),
        "u_plus_2" => u().succ().expect(packs).succ().expect(packs),
        "max_u_v" => Level::max(u(), v()).expect(packs),
        "imax_u_v" => Level::imax(u(), v()).expect(packs),
        "imax_u_zero" => Level::imax(u(), Level::zero()).expect(packs),
        "imax_v_succ_u" => Level::imax(v(), u().succ().expect(packs)).expect(packs),
        "succ_imax_v_su" => Level::imax(v(), u().succ().expect(packs))
            .expect(packs)
            .succ()
            .expect(packs),
        "max_u_succ_v" => Level::max(u(), v().succ().expect(packs)).expect(packs),
        "three" => Level::zero()
            .succ()
            .expect(packs)
            .succ()
            .expect(packs)
            .succ()
            .expect(packs),
        _ => return None,
    })
}

fn kvmap_case(label: &str) -> Option<KVMap> {
    let key = |s: &str| Name::str(Name::anonymous(), s);
    let mut map = KVMap::new();
    match label {
        "empty" => {}
        "one_nat" => map.insert(key("a"), DataValue::OfNat(7)),
        "mixed" => {
            map.insert(key("a"), DataValue::OfString("s".to_string()));
            map.insert(key("b"), DataValue::OfBool(true));
            map.insert(key("c"), DataValue::OfInt(-3));
        }
        "replaced" => {
            map.insert(key("a"), DataValue::OfNat(1));
            map.insert(key("b"), DataValue::OfBool(false));
            map.insert(key("a"), DataValue::OfNat(2));
        }
        "named" => map.insert(
            key("k"),
            DataValue::OfName(Name::str(Name::str(Name::anonymous(), "x"), "y")),
        ),
        _ => return None,
    }
    Some(map)
}

fn source_case(label: &str) -> Option<&'static str> {
    Some(match label {
        "empty" => "",
        "one_line" => "abc",
        "two_lines" => "ab\ncd",
        "crlf" => "ab\r\ncd",
        "multibyte" => "héllo\nwörld",
        "trailing_nl" => "ab\n",
        "blank_line" => "a\n\nb",
        _ => return None,
    })
}

/// The structural rendering the generator emits, reproduced exactly. Iterative, per
/// the p8a.1 law — the corpus is shallow, but this walks the same values every other
/// traversal in this crate walks.
fn render_level(level: &Level) -> String {
    match level.view() {
        LevelView::Zero => "0".to_string(),
        LevelView::Succ(inner) => format!("s({})", render_level(inner)),
        LevelView::Max(a, b) => format!("M({},{})", render_level(a), render_level(b)),
        LevelView::IMax(a, b) => format!("I({},{})", render_level(a), render_level(b)),
        LevelView::Param(name) => format!("P({})", name.to_display_string()),
        LevelView::MVar(id) => format!("V({})", id.0.to_display_string()),
    }
}

fn render_opt_level(level: Option<Level>) -> String {
    level.map_or_else(|| "none".to_string(), |l| render_level(&l))
}

fn ordering_str(ordering: std::cmp::Ordering) -> &'static str {
    match ordering {
        std::cmp::Ordering::Less => "lt",
        std::cmp::Ordering::Equal => "eq",
        std::cmp::Ordering::Greater => "gt",
    }
}

#[test]
fn the_fixture_was_generated_by_the_pinned_reference() {
    let header = FIXTURE
        .lines()
        .find(|line| line.contains("# Oracle:"))
        .expect("the fixture records its oracle");
    let commit = header
        .split("commit ")
        .nth(1)
        .and_then(|rest| rest.split_whitespace().next())
        .expect("the header names a commit");

    let pin = SUITE_LOCK
        .lines()
        .find(|line| line.starts_with("reference "))
        .expect("SUITE.lock pins the Reference");
    assert!(
        pin.contains(commit),
        "the fixture was generated by commit {commit}, which SUITE.lock does not pin: {pin}"
    );
}

/// The fixture names its own generator. Nothing checked that the name still resolved,
/// so the generator could move (or vanish) while the artifact went on citing the old
/// path — the join between a claim and the thing that produces it, unwatched. This is
/// the check that would have caught `franken_lean-eh0c`'s relocation had it been made
/// carelessly, and it is what makes the next one fail loudly.
///
/// It is a path-existence check, not a re-derivation: re-deriving needs the pinned
/// Reference binary, which RCH workers do not have. That stronger check is
/// `scripts/extract/gen_core_ext_fixtures.sh --check`, run where the pin exists.
#[test]
fn the_generator_named_by_the_fixture_exists() {
    let repo_root = fln_core::checked_workspace_root!();

    let header = FIXTURE
        .lines()
        .find(|line| line.contains("GENERATED by "))
        .expect("the fixture names its generator");
    let generator = header
        .split("GENERATED by ")
        .nth(1)
        .map(|rest| rest.trim().trim_end_matches('.'))
        .filter(|path| !path.is_empty())
        .expect("the header names a generator path");

    assert!(
        repo_root.join(generator).is_file(),
        "the fixture says it was generated by `{generator}`, which does not exist \
         under {}; regenerate with scripts/extract/gen_core_ext_fixtures.sh",
        repo_root.display()
    );
}

#[test]
fn extended_observables_match_the_reference_fixture() {
    let mut mismatches: Vec<String> = Vec::new();
    let mut seen: BTreeSet<String> = BTreeSet::new();
    let mut records = 0usize;
    let mut schema_ok = false;

    for (number, line) in FIXTURE.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line == "schema fln-core-ext-observables/1" {
            schema_ok = true;
            continue;
        }
        records += 1;
        let fields: Vec<&str> = line.split('|').collect();
        let mut mismatch = |what: String| mismatches.push(format!("{}:{what}", number + 1));

        match fields.as_slice() {
            ["namecmp", a, b, cmp, lt] => {
                seen.insert(format!("namecmp/{a}/{b}"));
                let (Some(left), Some(right)) = (name_case(a), name_case(b)) else {
                    mismatch(format!("unknown name case `{a}` or `{b}`"));
                    continue;
                };
                let ours = ordering_str(left.quick_cmp(&right));
                if ours != *cmp {
                    mismatch(format!("quickCmp {a} {b}: ours {ours}, oracle {cmp}"));
                }
                let ours_lt = left.quick_lt(&right).to_string();
                if ours_lt != *lt {
                    mismatch(format!("quickLt {a} {b}: ours {ours_lt}, oracle {lt}"));
                }
            }
            ["namestr", label, rendered] => {
                seen.insert(format!("namestr/{label}"));
                let Some(name) = name_case(label) else {
                    mismatch(format!("unknown name case `{label}`"));
                    continue;
                };
                let ours = name.to_display_string();
                if ours != *rendered {
                    mismatch(format!("toString {label}: ours {ours}, oracle {rendered}"));
                }
            }
            ["hygiene", label, has, erased, simplified] => {
                seen.insert(format!("hygiene/{label}"));
                let Some(name) = hygienic_case(label) else {
                    mismatch(format!("unknown hygienic case `{label}`"));
                    continue;
                };
                let ours_has = name.has_macro_scopes().to_string();
                if ours_has != *has {
                    mismatch(format!(
                        "hasMacroScopes {label}: ours {ours_has}, oracle {has}"
                    ));
                }
                let ours_erased = name.erase_macro_scopes().to_display_string();
                if ours_erased != *erased {
                    mismatch(format!(
                        "eraseMacroScopes {label}: ours {ours_erased}, oracle {erased}"
                    ));
                }
                let ours_simp = name.simp_macro_scopes().to_display_string();
                if ours_simp != *simplified {
                    mismatch(format!(
                        "simpMacroScopes {label}: ours {ours_simp}, oracle {simplified}"
                    ));
                }
            }
            ["append", a, b, rendered] => {
                seen.insert(format!("append/{a}/{b}"));
                let (Some(left), Some(right)) = (name_case(a), name_case(b)) else {
                    mismatch(format!("unknown name case `{a}` or `{b}`"));
                    continue;
                };
                let ours = left.append_core(&right).to_display_string();
                if ours != *rendered {
                    mismatch(format!(
                        "appendCore {a} {b}: ours {ours}, oracle {rendered}"
                    ));
                }
            }
            [
                "lvlunary",
                label,
                always_zero,
                to_nat,
                dec,
                offset2,
                normalized,
            ] => {
                seen.insert(format!("lvlunary/{label}"));
                let Some(level) = level_case(label) else {
                    mismatch(format!("unknown level case `{label}`"));
                    continue;
                };
                let checks = [
                    (
                        "isAlwaysZero",
                        level.is_always_zero().to_string(),
                        always_zero.to_string(),
                    ),
                    (
                        "toNat",
                        level
                            .to_nat()
                            .map_or_else(|| "none".to_string(), |n| n.to_string()),
                        to_nat.to_string(),
                    ),
                    ("dec", render_opt_level(level.dec()), dec.to_string()),
                    (
                        "addOffset 2",
                        render_level(&level.add_offset(2).expect("shallow")),
                        offset2.to_string(),
                    ),
                    (
                        "normalize",
                        render_level(&level.normalize()),
                        normalized.to_string(),
                    ),
                ];
                for (what, ours, oracle) in checks {
                    if ours != oracle {
                        mismatch(format!("{what} {label}: ours {ours}, oracle {oracle}"));
                    }
                }
            }
            ["lvlbin", a, b, geq, occurs, smart_max, smart_imax] => {
                seen.insert(format!("lvlbin/{a}/{b}"));
                let (Some(left), Some(right)) = (level_case(a), level_case(b)) else {
                    mismatch(format!("unknown level case `{a}` or `{b}`"));
                    continue;
                };
                let checks = [
                    ("geq", left.is_geq(&right).to_string(), geq.to_string()),
                    (
                        "occurs",
                        left.occurs_in(&right).to_string(),
                        occurs.to_string(),
                    ),
                    (
                        "mkLevelMax'",
                        render_level(&Level::smart_max(left.clone(), right.clone())),
                        smart_max.to_string(),
                    ),
                    (
                        "mkLevelIMax'",
                        render_level(&Level::smart_imax(left.clone(), right.clone())),
                        smart_imax.to_string(),
                    ),
                ];
                for (what, ours, oracle) in checks {
                    if ours != oracle {
                        mismatch(format!("{what} {a} {b}: ours {ours}, oracle {oracle}"));
                    }
                }
            }
            ["kvmap", label, string, nat, int, bool_, name, size] => {
                seen.insert(format!("kvmap/{label}"));
                let Some(map) = kvmap_case(label) else {
                    mismatch(format!("unknown kvmap case `{label}`"));
                    continue;
                };
                let a = Name::str(Name::anonymous(), "a");
                let k = Name::str(Name::anonymous(), "k");
                let checks = [
                    ("getString", map.get_string(&a, "DEF"), string.to_string()),
                    ("getNat", map.get_nat(&a, 99).to_string(), nat.to_string()),
                    ("getInt", map.get_int(&a, -99).to_string(), int.to_string()),
                    (
                        "getBool",
                        map.get_bool(&a, true).to_string(),
                        bool_.to_string(),
                    ),
                    (
                        "getName",
                        map.get_name(&k, &Name::anonymous()).to_display_string(),
                        name.to_string(),
                    ),
                    ("size", map.len().to_string(), size.to_string()),
                ];
                for (what, ours, oracle) in checks {
                    if ours != oracle {
                        mismatch(format!("{what} {label}: ours {ours}, oracle {oracle}"));
                    }
                }
            }
            ["filemap", label, last_line, byte_size] => {
                seen.insert(format!("filemap/{label}"));
                let Some(source) = source_case(label) else {
                    mismatch(format!("unknown source case `{label}`"));
                    continue;
                };
                let map = FileMap::of_string(source);
                let ours = map.last_line().to_string();
                if ours != *last_line {
                    mismatch(format!(
                        "getLastLine {label}: ours {ours}, oracle {last_line}"
                    ));
                }
                if source.len().to_string() != *byte_size {
                    mismatch(format!("the corpus disagrees on the size of `{label}`"));
                }
            }
            ["filepos", label, at, line, column, back] => {
                seen.insert(format!("filepos/{label}/{at}"));
                let Some(source) = source_case(label) else {
                    mismatch(format!("unknown source case `{label}`"));
                    continue;
                };
                let map = FileMap::of_string(source);
                let offset: usize = at.parse().expect("byte offset");
                let position = map.to_position(RawPos::new(offset));
                let ours_line = position.line.to_string();
                let ours_column = position.column.to_string();
                if ours_line != *line || ours_column != *column {
                    mismatch(format!(
                        "toPosition {label}@{at}: ours {ours_line}:{ours_column}, oracle {line}:{column}"
                    ));
                }
                let ours_back = map
                    .of_position(Position {
                        line: position.line,
                        column: position.column,
                    })
                    .byte_idx
                    .to_string();
                if ours_back != *back {
                    mismatch(format!(
                        "ofPosition {label}@{at}: ours {ours_back}, oracle {back}"
                    ));
                }
            }
            ["kvmapops", label, erased_size, erased_has_a, has_a, has_zz] => {
                seen.insert(format!("kvmapops/{label}"));
                let Some(map) = kvmap_case(label) else {
                    mismatch(format!("unknown kvmap case `{label}`"));
                    continue;
                };
                let a = Name::str(Name::anonymous(), "a");
                let mut erased = map.clone();
                erased.erase(&a);
                let checks = [
                    (
                        "erase size",
                        erased.len().to_string(),
                        erased_size.to_string(),
                    ),
                    (
                        "erase find",
                        erased.find(&a).is_some().to_string(),
                        erased_has_a.to_string(),
                    ),
                    (
                        "findCore a",
                        map.find(&a).is_some().to_string(),
                        has_a.to_string(),
                    ),
                    (
                        "findCore absent",
                        map.find(&Name::str(Name::anonymous(), "zz"))
                            .is_some()
                            .to_string(),
                        has_zz.to_string(),
                    ),
                ];
                for (what, ours, oracle) in checks {
                    if ours != oracle {
                        mismatch(format!("{what} {label}: ours {ours}, oracle {oracle}"));
                    }
                }
            }
            ["sameCtor", a, b, same] => {
                seen.insert(format!("sameCtor/{a}/{b}"));
                let value = |label: &str| -> Option<DataValue> {
                    Some(match label {
                        "str" => DataValue::OfString("s".to_string()),
                        "bool" => DataValue::OfBool(true),
                        "name" => DataValue::OfName(Name::str(Name::anonymous(), "n")),
                        "nat" => DataValue::OfNat(1),
                        "int" => DataValue::OfInt(-1),
                        _ => return None,
                    })
                };
                let (Some(left), Some(right)) = (value(a), value(b)) else {
                    mismatch(format!("unknown data value `{a}` or `{b}`"));
                    continue;
                };
                let ours = left.same_ctor(&right).to_string();
                if ours != *same {
                    mismatch(format!("sameCtor {a} {b}: ours {ours}, oracle {same}"));
                }
            }
            ["fileline", label, line_no, start] => {
                seen.insert(format!("fileline/{label}/{line_no}"));
                let Some(source) = source_case(label) else {
                    mismatch(format!("unknown source case `{label}`"));
                    continue;
                };
                let map = FileMap::of_string(source);
                let line: usize = line_no.parse().expect("line number");
                let ours_start = map.line_start(line).byte_idx.to_string();
                if ours_start != *start {
                    mismatch(format!(
                        "lineStart {label}#{line_no}: ours {ours_start}, oracle {start}"
                    ));
                }
            }
            _ => mismatch(format!("unrecognised record shape: {line}")),
        }
    }

    assert!(schema_ok, "fixture is missing its schema line");
    assert!(
        records >= 400,
        "fixture corpus shrank to {records} records — regenerate rather than trim"
    );
    assert!(
        mismatches.is_empty(),
        "fln-core disagrees with the pinned Reference on {} of {records} records:\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
    // Every record kind must have been exercised; a corpus that silently loses a
    // family would still pass the checks above.
    for family in [
        "namecmp", "namestr", "hygiene", "append", "lvlunary", "lvlbin", "kvmap", "kvmapops",
        "sameCtor", "filemap", "filepos", "fileline",
    ] {
        assert!(
            seen.iter().any(|s| s.starts_with(family)),
            "no `{family}` records in the fixture"
        );
    }
}
