//! Generated by scripts/extract/gen_source_extension_contract.py; do not edit.
//! Reference: v4.32.0 @ 8c9756b28d64dab099da31a4c09229a9e6a2ef35.
//! src/Lean/Class.lean: sha256 8cdd3670c4aebff325d2455d827da6d190339283ebd8b68f19221edeeeb7a277
//! src/Lean/Meta/Instances.lean: sha256 48c564b1af0cd39232f8e8f151800009d05e79c7786fef9739da2011233f4517
//! src/Lean/ScopedEnvExtension.lean: sha256 dfe287a844583ccf6b13b16dbe3e9160d2cd29f0efd5193c76ba3944e1826346
//! src/Lean/Attributes.lean: sha256 8219a775586b85586ac84665045f0bcbc6cc78c2fd184d2f8c8b78d5bdd8d643
//! src/Lean/Meta/Tactic/Simp/SimpTheorems.lean: sha256 78b3a7f971d3bd2aeca9c60a7850ec3449b9e48f9730000569fa43fa0274957d
//! src/Lean/Meta/Tactic/Simp/Attr.lean: sha256 ce45e8a48edbab67408b197257e616091ab55c410254e3d303fe813f7fd42242
//! src/Lean/ResolveName.lean: sha256 c42a2e8e21b0d0325a32f09827be6253aad276ac4d25b30b5281b420f1beccb9
//! src/Init/Prelude.lean: sha256 44f86ebbb9ab743a05c6ebe2c674aadbf2c822bee874f1b16d7e6c8d56318dc9
//! src/Lean/Modifiers.lean: sha256 dee35dbc823a48b9ac79f11db4b2741f89702dd1ac0a7df83050e7f61d2154fd
//! src/Lean/EnvExtension.lean: sha256 18086b4119360fad18b8434e2e0b3ef6f52d23f57a4d93ca4f7f7ffbe0685e87
#![allow(dead_code)]

pub const CLASS_NAME: usize = 0;
pub const CLASS_OUT_PARAMS: usize = 1;
pub const CLASS_OUT_LEVEL_PARAMS: usize = 2;
pub const CLASS_POINTERS: usize = 3;
pub const CLASS_SCALAR_BYTES: usize = 0;

pub const INSTANCE_KEYS: usize = 0;
pub const INSTANCE_VAL: usize = 1;
pub const INSTANCE_PRIORITY: usize = 2;
pub const INSTANCE_GLOBAL_NAME_OPTION: usize = 3;
pub const INSTANCE_SYNTH_ORDER: usize = 4;
pub const INSTANCE_ATTR_KIND_SCALAR: usize = 0;
pub const INSTANCE_POINTERS: usize = 5;
pub const INSTANCE_SCALAR_BYTES: usize = 1;

pub const DEFAULT_CLASS_NAME: usize = 0;
pub const DEFAULT_INSTANCE_NAME: usize = 1;
pub const DEFAULT_PRIORITY: usize = 2;
pub const DEFAULT_POINTERS: usize = 3;
pub const DEFAULT_SCALAR_BYTES: usize = 0;

pub const SIMP_THM_KEYS: usize = 0;
pub const SIMP_THM_LEVEL_PARAMS: usize = 1;
pub const SIMP_THM_PROOF: usize = 2;
pub const SIMP_THM_PRIORITY: usize = 3;
pub const SIMP_THM_POST_SCALAR: usize = 0;
pub const SIMP_THM_PERM_SCALAR: usize = 1;
pub const SIMP_THM_ORIGIN: usize = 4;
pub const SIMP_THM_RFL_SCALAR: usize = 2;
pub const SIMP_THM_BACKWARD_RFL_SCALAR: usize = 3;
pub const SIMP_THM_POINTERS: usize = 5;
pub const SIMP_THM_SCALAR_BYTES: usize = 4;

pub const SCOPE_GLOBAL: u8 = 0;
pub const SCOPE_SCOPED: u8 = 1;
pub const ATTRIBUTE_GLOBAL: u8 = 0;
pub const ATTRIBUTE_LOCAL: u8 = 1;
pub const ATTRIBUTE_SCOPED: u8 = 2;
pub const SIMP_ENTRY_THM: u8 = 0;
pub const SIMP_ENTRY_TO_UNFOLD: u8 = 1;
pub const SIMP_ENTRY_TO_UNFOLD_THMS: u8 = 2;
pub const SIMP_ORIGIN_DECL: u8 = 0;
pub const SIMP_ORIGIN_FVAR: u8 = 1;
pub const SIMP_ORIGIN_STX: u8 = 2;
pub const SIMP_ORIGIN_OTHER: u8 = 3;
pub const SIMP_ORIGIN_DECL_NAME: usize = 0;
pub const SIMP_ORIGIN_DECL_POINTERS: usize = 1;
pub const SIMP_ORIGIN_DECL_POST_SCALAR: usize = 0;
pub const SIMP_ORIGIN_DECL_INV_SCALAR: usize = 1;
pub const SIMP_EXTENSION: &str = "Lean.Meta.simpExtension";
pub const CLASS_EXTENSION: &str = "Lean.classExtension";
pub const INSTANCE_EXTENSION: &str = "Lean.Meta.instanceExtension";
pub const DEFAULT_EXTENSION: &str = "Lean.Meta.defaultInstanceExtension";
pub const ALIAS_EXTENSION: &str = "Lean.aliasExtension";
pub const PROD_FST: usize = 0;
pub const PROD_SND: usize = 1;
pub const PROD_POINTERS: usize = 2;
pub const PROD_SCALAR_BYTES: usize = 0;
pub const PROTECTED_EXTENSION: &str = "Lean.protectedExt";
