//! Generated by scripts/extract/gen_source_extension_contract.py; do not edit.
//! Reference: v4.32.0 @ 8c9756b28d64dab099da31a4c09229a9e6a2ef35.
//! src/Lean/Class.lean: sha256 8cdd3670c4aebff325d2455d827da6d190339283ebd8b68f19221edeeeb7a277
//! src/Lean/Meta/Instances.lean: sha256 48c564b1af0cd39232f8e8f151800009d05e79c7786fef9739da2011233f4517
//! src/Lean/ScopedEnvExtension.lean: sha256 dfe287a844583ccf6b13b16dbe3e9160d2cd29f0efd5193c76ba3944e1826346
//! src/Lean/Attributes.lean: sha256 8219a775586b85586ac84665045f0bcbc6cc78c2fd184d2f8c8b78d5bdd8d643
#![allow(dead_code)]

pub const CLASS_NAME: usize = 0;
pub const CLASS_OUT_PARAMS: usize = 1;
pub const CLASS_OUT_LEVEL_PARAMS: usize = 2;
pub const CLASS_POINTERS: usize = 3;
pub const CLASS_SCALAR_BYTES: usize = 0;

pub const INSTANCE_KEYS: usize = 0;
pub const INSTANCE_VAL: usize = 1;
pub const INSTANCE_PRIORITY: usize = 2;
pub const INSTANCE_GLOBAL_NAME_OPTION: usize = 3;
pub const INSTANCE_SYNTH_ORDER: usize = 4;
pub const INSTANCE_ATTR_KIND_SCALAR: usize = 0;
pub const INSTANCE_POINTERS: usize = 5;
pub const INSTANCE_SCALAR_BYTES: usize = 1;

pub const DEFAULT_CLASS_NAME: usize = 0;
pub const DEFAULT_INSTANCE_NAME: usize = 1;
pub const DEFAULT_PRIORITY: usize = 2;
pub const DEFAULT_POINTERS: usize = 3;
pub const DEFAULT_SCALAR_BYTES: usize = 0;

pub const SCOPE_GLOBAL: u8 = 0;
pub const SCOPE_SCOPED: u8 = 1;
pub const ATTRIBUTE_GLOBAL: u8 = 0;
pub const ATTRIBUTE_LOCAL: u8 = 1;
pub const ATTRIBUTE_SCOPED: u8 = 2;
pub const CLASS_EXTENSION: &str = "Lean.classExtension";
pub const INSTANCE_EXTENSION: &str = "Lean.Meta.instanceExtension";
pub const DEFAULT_EXTENSION: &str = "Lean.Meta.defaultInstanceExtension";
