-- GENERATED by gen_attribute_state_census.py --tag-oracle-output; oracle-only (D8).
module
import Lean
import all Lean.Compiler.IR.UnboxResult
import all Lean.Compiler.LCNF.ToImpure
import all Lean.Compiler.NeverExtractAttr
import all Lean.Compiler.Specialize
import all Lean.DefEqAttrib
import all Lean.Elab.App
import all Lean.Elab.ComputedFields
import all Lean.Elab.Tactic.Basic
import all Lean.Elab.Tactic.Do.Attr
import all Lean.Elab.Term
import all Lean.LibrarySuggestions.Basic
import all Lean.Meta.Coe
import all Lean.Meta.Match.MatchPatternAttr
import all Lean.PrettyPrinter.Delaborator.Attributes
open Lean

def hexDigit (n : Nat) : Char := Char.ofNat (if n < 10 then 48 + n else 87 + n)
def hexText (s : String) : String := String.ofList <| s.toUTF8.toList.flatMap fun b =>
  [hexDigit (b.toNat / 16), hexDigit (b.toNat % 16)]
def encodeName : Name → String
  | .anonymous => "a"
  | .str p s => encodeName p ++ "/s" ++ hexText s
  | .num p n => encodeName p ++ "/n" ++ toString n

def attributes : List (String × TagAttribute) := [
  ("unbox\tLean.IR.UnboxResult.unboxAttr", Lean.IR.UnboxResult.unboxAttr),
  ("tagged_return\tLean.Compiler.LCNF.taggedReturnAttr", Lean.Compiler.LCNF.taggedReturnAttr),
  ("never_extract\tLean.neverExtractAttr", Lean.neverExtractAttr),
  ("nospecialize\tLean.Compiler.nospecializeAttr", Lean.Compiler.nospecializeAttr),
  ("weak_specialize\tLean.Compiler.weakSpecializeAttr", Lean.Compiler.weakSpecializeAttr),
  ("defeq\tLean.defeqAttr", Lean.defeqAttr),
  ("backward_defeq\tLean.backwardDefeqAttr", Lean.backwardDefeqAttr),
  ("elab_as_elim\tLean.Elab.Term.elabAsElim", Lean.Elab.Term.elabAsElim),
  ("elab_without_expected_type\tLean.Elab.Term.elabWithoutExpectedTypeAttr", Lean.Elab.Term.elabWithoutExpectedTypeAttr),
  ("computed_field\tLean.Elab.ComputedFields.computedFieldAttr", Lean.Elab.ComputedFields.computedFieldAttr),
  ("no_fallback\tLean.Elab.Tactic.noFallbackAttr", Lean.Elab.Tactic.noFallbackAttr),
  ("spec_invariant_type\tLean.Elab.Tactic.Do.SpecAttr.specInvariantAttr", Lean.Elab.Tactic.Do.SpecAttr.specInvariantAttr),
  ("incremental\tLean.Elab.incrementalAttr", Lean.Elab.incrementalAttr),
  ("library_suggestions\tLean.LibrarySuggestions.librarySuggestionsAttr", Lean.LibrarySuggestions.librarySuggestionsAttr),
  ("coe_decl\tLean.Meta.coeDeclAttr", Lean.Meta.coeDeclAttr),
  ("match_pattern\tLean.matchPatternAttr", Lean.matchPatternAttr),
  ("pp_using_anonymous_constructor\tLean.ppUsingAnonymousConstructorAttr", Lean.ppUsingAnonymousConstructorAttr),
  ("pp_nodot\tLean.ppNoDotAttr", Lean.ppNoDotAttr)
]

public unsafe def main : IO Unit := do
  initSearchPath (← getBuildDir)
  enableInitializersExecution
  let env ← importModules #[{ module := `Init.Prelude }] {} (loadExts := true) (level := .private)
  IO.println "schema fln-imported-tag-queries/1"
  IO.println s!"oracle\t{Lean.versionString}\t{Lean.githash}"
  IO.println "module\tInit.Prelude\tprivate"
  let decls := env.constants.toList.toArray.map Prod.fst |>.qsort Name.quickLt
  for (label, attr) in attributes do
    IO.println s!"binding\t{label}\t{encodeName attr.attr.ref}"
    let label := (label.splitOn "\t").head!
    for decl in decls do
      if attr.hasTag env decl then
        IO.println s!"query\t{label}\t{encodeName decl}\ttrue"
    let absent := `_frankenLeanAbsentTagProbe
    IO.println s!"query\t{label}\t{encodeName absent}\t{attr.hasTag env absent}"
