-- GENERATED by scripts/extract/facade_stubs.py from the pinned Reference
-- (v4.32.0) — Mirror facade stubs for the demanded toolchain surface
-- (bead fln-l8f, G0-8 acceptance b). DO NOT EDIT.
--
-- Each stub is an `axiom`: a facade DECLARES the symbol's type and leaves
-- the implementation to the native mirror. The bucket comment carries the
-- resistance class from contracts/facade_resistance.ndjson, so the L-level
-- ratchet is readable in the generated artifact rather than only beside it.
--
-- `autoImplicit false` is load-bearing: with it on, an unresolved name in a
-- stub type silently becomes a bound type variable and elaboration proves
-- only syntax — measured on the first generation of this file, which went
-- green while >=100 of its type references resolved to nothing.
import Lean
set_option autoImplicit false
namespace FlnFacade

-- R-EXTERN effect=pure extern=False
axiom Array_mapM.{u, v, w} : {α : Type u} → {β : Type v} → {m : Type v → Type w} → [Monad m] → (α → m β) → Array α → m (Array β)
-- R-EXTERN effect=pure extern=True
axiom Array_mkEmpty.{u} : {α : Type u} → Nat → Array α
-- R-EXTERN effect=pure extern=True
axiom Array_push.{u} : {α : Type u} → Array α → α → Array α
-- R-EXTERN effect=pure extern=True
axiom Array_replicate.{u} : {α : Type u} → Nat → α → Array α
-- R-EXTERN effect=pure extern=True
axiom Array_set!.{u_1} : {α : Type u_1} → Array α → Nat → α → Array α
-- R-EXTERN effect=pure extern=True
axiom Array_size.{u} : {α : Type u} → Array α → Nat
-- R-EXTERN effect=pure extern=False
axiom Dynamic_get?.{u_1} : (α : Type u_1) → Dynamic → [TypeName α] → Option α
-- R-EXTERN effect=pure extern=False
axiom Dynamic_typeName : Dynamic → Lean.Name
-- R-EFFECT effect=monad-transformer extern=False
axiom ExceptT_instMonad.{u, v} : {ε : Type u} → {m : Type u → Type v} → [Monad m] → Monad (ExceptT ε m)
-- R-EFFECT effect=io extern=False
axiom IO_instMonadLiftSTRealWorldBaseIO : MonadLift (ST IO.RealWorld) BaseIO
-- R-EFFECT effect=io extern=False
axiom IO_ofExcept.{u_1} : {ε : Type u_1} → {α : Type} → [ToString ε] → Except ε α → IO α
-- R-EXTERN effect=pure extern=True
axiom Int_negSucc : Nat → Int
-- R-EXTERN effect=pure extern=True
axiom Int_ofNat : Nat → Int
-- R-NONE effect=pure extern=False
axiom Lean_AsyncConstantInfo_kind : Lean.AsyncConstantInfo → Lean.ConstantKind
-- R-NONE effect=pure extern=False
axiom Lean_AsyncConstantInfo_toConstantVal : Lean.AsyncConstantInfo → Lean.ConstantVal
-- R-NONE effect=pure extern=False
axiom Lean_AttrM : Type → Type
-- R-NONE effect=pure extern=False
axiom Lean_AxiomVal_isUnsafe : Lean.AxiomVal → Bool
-- R-NONE effect=pure extern=False
axiom Lean_BinderInfo_ctorIdx : Lean.BinderInfo → Nat
-- R-NONE effect=pure extern=False
axiom Lean_BinderInfo_isInstImplicit : Lean.BinderInfo → Bool
-- R-NONE effect=pure extern=False
axiom Lean_ConstantInfo_casesOn.{u} : {motive : Lean.ConstantInfo → Sort u} → (t : Lean.ConstantInfo) → ((val : Lean.AxiomVal) → motive (Lean.ConstantInfo.axiomInfo val)) → ((val : Lean.DefinitionVal) → motive (Lean.ConstantInfo.defnInfo val)) → ((val : Lean.TheoremVal) → motive (Lean.ConstantInfo.thmInfo val)) → ((val : Lean.OpaqueVal) → motive (Lean.ConstantInfo.opaqueInfo val)) → ((val : Lean.QuotVal) → motive (Lean.ConstantInfo.quotInfo val)) → ((val : Lean.InductiveVal) → motive (Lean.ConstantInfo.inductInfo val)) → ((val : Lean.ConstructorVal) → motive (Lean.ConstantInfo.ctorInfo val)) → ((val : Lean.RecursorVal) → motive (Lean.ConstantInfo.recInfo val)) → motive t
-- R-NONE effect=pure extern=False
axiom Lean_ConstantInfo_ctorIdx : Lean.ConstantInfo → Nat
-- R-NONE effect=pure extern=False
axiom Lean_ConstantInfo_levelParams : Lean.ConstantInfo → List Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_ConstantInfo_toConstantVal : Lean.ConstantInfo → Lean.ConstantVal
-- R-NONE effect=pure extern=False
axiom Lean_ConstantKind_ctorIdx : Lean.ConstantKind → Nat
-- R-NONE effect=pure extern=False
axiom Lean_ConstantVal_levelParams : Lean.ConstantVal → List Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_ConstantVal_name : Lean.ConstantVal → Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_ConstantVal_type : Lean.ConstantVal → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_ConstructorVal_cidx : Lean.ConstructorVal → Nat
-- R-NONE effect=pure extern=False
axiom Lean_ConstructorVal_induct : Lean.ConstructorVal → Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_ConstructorVal_isUnsafe : Lean.ConstructorVal → Bool
-- R-NONE effect=pure extern=False
axiom Lean_ConstructorVal_numFields : Lean.ConstructorVal → Nat
-- R-NONE effect=pure extern=False
axiom Lean_ConstructorVal_numParams : Lean.ConstructorVal → Nat
-- R-NONE effect=pure extern=False
axiom Lean_Core_CoreM : Type → Type
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Core_checkSystem : String → Lean.Core.CoreM Unit
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Core_instAddMessageContextCoreM : Lean.AddMessageContext Lean.Core.CoreM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Core_instMonadCoreM : Monad Lean.Core.CoreM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Core_instMonadEnvCoreM : Lean.MonadEnv Lean.Core.CoreM
-- R-EFFECT effect=io extern=False
axiom Lean_Core_instMonadLiftIOCoreM : MonadLift IO Lean.Core.CoreM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Core_instMonadQuotationCoreM : Lean.MonadQuotation Lean.Core.CoreM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Core_instMonadRefCoreM : Lean.MonadRef Lean.Core.CoreM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Core_mkFreshUserName : Lean.Name → Lean.Core.CoreM Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_DeclarationRange_endPos : Lean.DeclarationRange → Lean.Position
-- R-NONE effect=pure extern=False
axiom Lean_DeclarationRange_pos : Lean.DeclarationRange → Lean.Position
-- R-NONE effect=pure extern=False
axiom Lean_DeclarationRanges_range : Lean.DeclarationRanges → Lean.DeclarationRange
-- R-NONE effect=pure extern=False
axiom Lean_DeclarationRanges_selectionRange : Lean.DeclarationRanges → Lean.DeclarationRange
-- R-NONE effect=pure extern=False
axiom Lean_DefinitionVal_all : Lean.DefinitionVal → List Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_DefinitionVal_hints : Lean.DefinitionVal → Lean.ReducibilityHints
-- R-NONE effect=pure extern=False
axiom Lean_DefinitionVal_safety : Lean.DefinitionVal → Lean.DefinitionSafety
-- R-NONE effect=pure extern=False
axiom Lean_DefinitionVal_toConstantVal : Lean.DefinitionVal → Lean.ConstantVal
-- R-NONE effect=pure extern=False
axiom Lean_DefinitionVal_value : Lean.DefinitionVal → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Command_CommandElabM : Type → Type
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Command_Context_fileMap : Lean.Elab.Command.Context → Lean.FileMap
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Command_State_env : Lean.Elab.Command.State → Lean.Environment
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Command_State_messages : Lean.Elab.Command.State → Lean.MessageLog
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Command_State_ngen : Lean.Elab.Command.State → Lean.NameGenerator
-- R-EFFECT effect=io extern=False
axiom Lean_Elab_Command_addLinter : Lean.Elab.Command.Linter → IO Unit
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Command_instAddMessageContextCommandElabM : Lean.AddMessageContext Lean.Elab.Command.CommandElabM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Command_instMonadCommandElabM : Monad Lean.Elab.Command.CommandElabM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Command_instMonadEnvCommandElabM : Lean.MonadEnv Lean.Elab.Command.CommandElabM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Command_instMonadExceptOfExceptionCommandElabM : MonadExceptOf Lean.Exception Lean.Elab.Command.CommandElabM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Command_instMonadInfoTreeCommandElabM : Lean.Elab.MonadInfoTree Lean.Elab.Command.CommandElabM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Command_instMonadLogCommandElabM : Lean.MonadLog Lean.Elab.Command.CommandElabM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Command_instMonadOptionsCommandElabM : Lean.MonadOptions Lean.Elab.Command.CommandElabM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Command_instMonadQuotationCommandElabM : Lean.MonadQuotation Lean.Elab.Command.CommandElabM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Command_instMonadRefCommandElabM : Lean.MonadRef Lean.Elab.Command.CommandElabM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Command_instMonadResolveNameCommandElabM : Lean.MonadResolveName Lean.Elab.Command.CommandElabM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Command_liftCoreM : {α : Type} → Lean.Core.CoreM α → Lean.Elab.Command.CommandElabM α
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Command_liftTermElabM : {α : Type} → Lean.Elab.Term.TermElabM α → Lean.Elab.Command.CommandElabM α
-- R-NONE effect=pure extern=False
axiom Lean_Elab_ContextInfo__sizeOf_inst : SizeOf Lean.Elab.ContextInfo
-- R-NONE effect=pure extern=False
axiom Lean_Elab_ContextInfo_parentDecl? : Lean.Elab.ContextInfo → Option Lean.Name
-- R-EFFECT effect=io extern=False
axiom Lean_Elab_ContextInfo_runMetaM : {α : Type} → Lean.Elab.ContextInfo → Lean.LocalContext → Lean.Meta.MetaM α → IO α
-- R-NONE effect=pure extern=False
axiom Lean_Elab_CustomInfo_stx : Lean.Elab.CustomInfo → Lean.Syntax
-- R-NONE effect=pure extern=False
axiom Lean_Elab_CustomInfo_value : Lean.Elab.CustomInfo → Dynamic
-- R-NONE effect=pure extern=False
axiom Lean_Elab_ElabInfo_stx : Lean.Elab.ElabInfo → Lean.Syntax
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Info_ctorIdx : Lean.Elab.Info → Nat
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Info_stx : Lean.Elab.Info → Lean.Syntax
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Info_updateContext? : Option Lean.Elab.ContextInfo → Lean.Elab.Info → Option Lean.Elab.ContextInfo
-- R-NONE effect=pure extern=False
axiom Lean_Elab_InfoState_enabled : Lean.Elab.InfoState → Bool
-- R-NONE effect=pure extern=False
axiom Lean_Elab_InfoTree_casesOn.{u} : {motive_1 : Lean.Elab.InfoTree → Sort u} → (t : Lean.Elab.InfoTree) → ((i : Lean.Elab.PartialContextInfo) → (t : Lean.Elab.InfoTree) → motive_1 (Lean.Elab.InfoTree.context i t)) → ((i : Lean.Elab.Info) → (children : Lean.PersistentArray Lean.Elab.InfoTree) → motive_1 (Lean.Elab.InfoTree.node i children)) → ((mvarId : Lean.MVarId) → motive_1 (Lean.Elab.InfoTree.hole mvarId)) → motive_1 t
-- R-NONE effect=pure extern=False
axiom Lean_Elab_InfoTree_collectNodesBottomUp : {α : Type} → (Lean.Elab.ContextInfo → Lean.Elab.Info → Lean.PersistentArray Lean.Elab.InfoTree → List α → List α) → Lean.Elab.InfoTree → List α
-- R-NONE effect=pure extern=False
axiom Lean_Elab_InfoTree_ctorIdx : Lean.Elab.InfoTree → Nat
-- R-NONE effect=pure extern=False
axiom Lean_Elab_InfoTree_foldInfo.{u_1} : {α : Type u_1} → (Lean.Elab.ContextInfo → Lean.Elab.Info → α → α) → α → Lean.Elab.InfoTree → α
-- R-NONE effect=pure extern=False
axiom Lean_Elab_InfoTree_foldInfoTree.{u_1} : {α : Type u_1} → α → (Lean.Elab.ContextInfo → Lean.Elab.InfoTree → α → α) → Lean.Elab.InfoTree → α
-- R-NONE effect=pure extern=False pp=explicit
axiom Lean_Elab_InfoTree_visitM.{u_1} : {m : Type → Type u_1} → {α : Type} → [inst : Monad m] → (optParam (Lean.Elab.ContextInfo → Lean.Elab.Info → Lean.PersistentArray Lean.Elab.InfoTree → m Bool) fun x x_1 x_2 => @Pure.pure m (@Applicative.toPure m (@Monad.toApplicative m inst)) Bool Bool.true) → (Lean.Elab.ContextInfo → Lean.Elab.Info → Lean.PersistentArray Lean.Elab.InfoTree → List (Option α) → m α) → optParam (Option Lean.Elab.ContextInfo) (@Option.none Lean.Elab.ContextInfo) → Lean.Elab.InfoTree → m (Option α)
-- R-NONE effect=pure extern=False pp=explicit
axiom Lean_Elab_MonadInfoTree_getInfoState : {m : Type → Type} → [self : Lean.Elab.MonadInfoTree m] → m Lean.Elab.InfoState
-- R-NONE effect=pure extern=False pp=explicit
axiom Lean_Elab_MonadMacroAdapter_toMonadQuotation : {m : Type → Type} → [self : Lean.Elab.MonadMacroAdapter m] → Lean.MonadQuotation m
-- R-NONE effect=pure extern=False
axiom Lean_Elab_PartialContextInfo_mergeIntoOuter? : Lean.Elab.PartialContextInfo → Option Lean.Elab.ContextInfo → Option Lean.Elab.ContextInfo
-- R-NONE effect=pure extern=False
axiom Lean_Elab_PartialTermInfo_expectedType? : Lean.Elab.PartialTermInfo → Option Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Elab_PartialTermInfo_lctx : Lean.Elab.PartialTermInfo → Lean.LocalContext
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_RCases_rcases : Array (Option Lean.Syntax.Ident × Lean.Syntax) → Lean.Elab.Tactic.RCases.RCasesPatt → Lean.MVarId → Lean.Elab.Term.TermElabM (List Lean.MVarId)
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_RCases_rintro : Lean.TSyntaxArray `rintroPat → Option Lean.Syntax.Term → Lean.MVarId → Lean.Elab.Term.TermElabM (List Lean.MVarId)
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Tactic_Tactic : Type
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Tactic_TacticM : Type → Type
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_elabTerm : Lean.Syntax → Option Lean.Expr → optParam Bool Bool.false → Lean.Elab.Tactic.TacticM Lean.Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_elabTermEnsuringType : Lean.Syntax → Option Lean.Expr → optParam Bool Bool.false → Lean.Elab.Tactic.TacticM Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Tactic_evalAllGoals : Lean.Elab.Tactic.Tactic
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_evalTactic : Lean.Syntax → Lean.Elab.Tactic.TacticM Unit
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_getGoals : Lean.Elab.Tactic.TacticM (List Lean.MVarId)
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_getMainGoal : Lean.Elab.Tactic.TacticM Lean.MVarId
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_instMonadTacticM : Monad Lean.Elab.Tactic.TacticM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_mkSimpContext : Lean.Syntax → Bool → optParam Lean.Elab.Tactic.SimpKind Lean.Elab.Tactic.SimpKind.simp → optParam Bool Bool.false → optParam (Lean.Core.CoreM Lean.Meta.SimpTheorems) Lean.Meta.getSimpTheorems → Lean.Elab.Tactic.TacticM Lean.Elab.Tactic.MkSimpContextResult
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_mkSimpOnly : Lean.Syntax → Lean.Meta.Simp.UsedSimps → Lean.Meta.MetaM Lean.Syntax
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_pruneSolvedGoals : Lean.Elab.Tactic.TacticM Unit
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_replaceMainGoal : List Lean.MVarId → Lean.Elab.Tactic.TacticM Unit
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_run : Lean.MVarId → Lean.Elab.Tactic.TacticM Unit → Lean.Elab.Term.TermElabM (List Lean.MVarId)
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_setGoals : List Lean.MVarId → Lean.Elab.Tactic.TacticM Unit
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_withMainContext : {α : Type} → Lean.Elab.Tactic.TacticM α → Lean.Elab.Tactic.TacticM α
-- R-NONE effect=pure extern=False
axiom Lean_Elab_TacticInfo__sizeOf_inst : SizeOf Lean.Elab.TacticInfo
-- R-NONE effect=pure extern=False
axiom Lean_Elab_TacticInfo_goalsAfter : Lean.Elab.TacticInfo → List Lean.MVarId
-- R-NONE effect=pure extern=False
axiom Lean_Elab_TacticInfo_goalsBefore : Lean.Elab.TacticInfo → List Lean.MVarId
-- R-NONE effect=pure extern=False
axiom Lean_Elab_TacticInfo_mctxAfter : Lean.Elab.TacticInfo → Lean.MetavarContext
-- R-NONE effect=pure extern=False
axiom Lean_Elab_TacticInfo_mctxBefore : Lean.Elab.TacticInfo → Lean.MetavarContext
-- R-NONE effect=pure extern=False
axiom Lean_Elab_TacticInfo_toElabInfo : Lean.Elab.TacticInfo → Lean.Elab.ElabInfo
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Term_FixedTermElabRef : Type
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Term_TermElab : Type
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Term_TermElabM : Type → Type
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Term_TermElabM_run' : {α : Type} → Lean.Elab.Term.TermElabM α → optParam Lean.Elab.Term.Context { } → optParam Lean.Elab.Term.State { } → Lean.Meta.MetaM α
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Term_elabTermAndSynthesize : Lean.Syntax → Option Lean.Expr → Lean.Elab.Term.TermElabM Lean.Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Term_elabType : Lean.Syntax → Lean.Elab.Term.TermElabM Lean.Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Term_instMonadMacroAdapterTermElabM : Lean.Elab.MonadMacroAdapter Lean.Elab.Term.TermElabM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Term_instMonadTermElabM : Monad Lean.Elab.Term.TermElabM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Term_mkCalcStepViews : Lean.TSyntax `Lean.calcSteps → Lean.Elab.Term.TermElabM (Array Lean.Elab.Term.CalcStepView)
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Term_withSynthesize.{u_1} : {m : Type → Type u_1} → {α : Type} → [MonadFunctorT Lean.Elab.Term.TermElabM m] → m α → optParam Lean.Elab.Term.PostponeBehavior Lean.Elab.Term.PostponeBehavior.no → m α
-- R-NONE effect=pure extern=False
axiom Lean_Elab_TermInfo_expectedType? : Lean.Elab.TermInfo → Option Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Elab_TermInfo_lctx : Lean.Elab.TermInfo → Lean.LocalContext
-- R-NONE effect=pure extern=False
axiom Lean_Elab_getInfoTrees : {m : Type → Type} → [Lean.Elab.MonadInfoTree m] → [Monad m] → m (Lean.PersistentArray Lean.Elab.InfoTree)
-- R-NONE effect=pure extern=False
axiom Lean_Elab_instInhabitedInfoTree : Inhabited Lean.Elab.InfoTree
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_runTactic : Lean.MVarId → Lean.Syntax → optParam Lean.Elab.Term.Context { } → optParam Lean.Elab.Term.State { } → Lean.Meta.MetaM (List Lean.MVarId × Lean.Elab.Term.State)
-- R-NONE effect=pure extern=False
axiom Lean_Elab_throwUnsupportedSyntax.{u_1, u_2} : {m : Type u_1 → Type u_2} → {α : Type u_1} → [MonadExceptOf Lean.Exception m] → m α
-- R-NONE effect=pure extern=False
axiom Lean_EnvExtension_asyncMode : {σ : Type} → Lean.EnvExtension σ → Lean.EnvExtension.AsyncMode
-- R-UNSAFE effect=pure extern=False
axiom Lean_Environment_evalConst : (α : Type) → Lean.Environment → Lean.Options → Lean.Name → optParam Bool Bool.true → Except String α
-- R-UNSAFE effect=monad-transformer extern=False
axiom Lean_Environment_evalConstCheck : (α : Type) → Lean.Environment → Lean.Options → Lean.Name → Lean.Name → ExceptT String Id α
-- R-NONE effect=pure extern=False
axiom Lean_Environment_findAsync? : Lean.Environment → Lean.Name → optParam Bool Bool.false → Option Lean.AsyncConstantInfo
-- R-NONE effect=pure extern=False
axiom Lean_Environment_getModuleIdxFor? : Lean.Environment → Lean.Name → Option Lean.ModuleIdx
-- R-NONE effect=pure extern=False
axiom Lean_Exception_toMessageData : Lean.Exception → Lean.MessageData
-- R-EXTERN effect=pure extern=False
axiom Lean_Expr_app : Lean.Expr → Lean.Expr → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Expr_app4? : Lean.Expr → Lean.Name → Option (Lean.Expr × Lean.Expr × Lean.Expr × Lean.Expr)
-- R-NONE effect=pure extern=False
axiom Lean_Expr_appArg! : Lean.Expr → Lean.Expr
-- R-NONE effect=pure extern=False pp=explicit
axiom Lean_Expr_below.{u} : {motive : Lean.Expr → Sort u} → Lean.Expr → Sort (max 1 u)
-- R-NONE effect=pure extern=False
axiom Lean_Expr_beta : Lean.Expr → Array Lean.Expr → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Expr_betaRev : Lean.Expr → Array Lean.Expr → optParam Bool Bool.false → optParam Bool Bool.false → Lean.Expr
-- R-NONE effect=pure extern=False pp=explicit
axiom Lean_Expr_brecOn.{u} : {motive : Lean.Expr → Sort u} → (t : Lean.Expr) → ((t : Lean.Expr) → @Lean.Expr.below motive t → motive t) → motive t
-- R-EXTERN effect=pure extern=False
axiom Lean_Expr_bvar : Nat → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Expr_cleanupAnnotations : Lean.Expr → Lean.Expr
-- R-EXTERN effect=pure extern=False
axiom Lean_Expr_const : Lean.Name → List Lean.Level → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Expr_constName! : Lean.Expr → Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_Expr_consumeMData : Lean.Expr → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Expr_ctorIdx : Lean.Expr → Nat
-- R-NONE effect=pure extern=False
axiom Lean_Expr_eq? : Lean.Expr → Option (Lean.Expr × Lean.Expr × Lean.Expr)
-- R-NONE effect=pure extern=False
axiom Lean_Expr_find? : (Lean.Expr → Bool) → Lean.Expr → Option Lean.Expr
-- R-EXTERN effect=pure extern=False
axiom Lean_Expr_forallE : Lean.Name → Lean.Expr → Lean.Expr → Lean.BinderInfo → Lean.Expr
-- R-EXTERN effect=pure extern=False
axiom Lean_Expr_fvar : Lean.FVarId → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Expr_fvarId! : Lean.Expr → Lean.FVarId
-- R-NONE effect=pure extern=False
axiom Lean_Expr_getAppArgs : Lean.Expr → Array Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Expr_getAppFn : Lean.Expr → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Expr_getAppFn' : Lean.Expr → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Expr_getAppNumArgs : Lean.Expr → Nat
-- R-NONE effect=pure extern=False
axiom Lean_Expr_getAppNumArgs' : Lean.Expr → Nat
-- R-NONE effect=pure extern=False
axiom Lean_Expr_getArg! : (e : Lean.Expr) → Nat → optParam Nat e.getAppNumArgs → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Expr_getRevArg! : Lean.Expr → Nat → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Expr_hasExprMVar : Lean.Expr → Bool
-- R-EXTERN effect=pure extern=True
axiom Lean_Expr_hasLooseBVar : Lean.Expr → Nat → Bool
-- R-NONE effect=pure extern=False
axiom Lean_Expr_heq? : Lean.Expr → Option (Lean.Expr × Lean.Expr × Lean.Expr × Lean.Expr)
-- R-NONE effect=pure extern=False
axiom Lean_Expr_iff? : Lean.Expr → Option (Lean.Expr × Lean.Expr)
-- R-NONE effect=pure extern=False
axiom Lean_Expr_instBEq : BEq Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Expr_isApp : Lean.Expr → Bool
-- R-NONE effect=pure extern=False
axiom Lean_Expr_isConst : Lean.Expr → Bool
-- R-NONE effect=pure extern=False
axiom Lean_Expr_isConstOf : Lean.Expr → Lean.Name → Bool
-- R-NONE effect=pure extern=False
axiom Lean_Expr_isFVar : Lean.Expr → Bool
-- R-NONE effect=pure extern=False
axiom Lean_Expr_isProp : Lean.Expr → Bool
-- R-EXTERN effect=pure extern=False
axiom Lean_Expr_lam : Lean.Name → Lean.Expr → Lean.Expr → Lean.BinderInfo → Lean.Expr
-- R-EXTERN effect=pure extern=False
axiom Lean_Expr_letE : Lean.Name → Lean.Expr → Lean.Expr → Lean.Expr → Bool → Lean.Expr
-- R-EXTERN effect=pure extern=False
axiom Lean_Expr_lit : Lean.Literal → Lean.Expr
-- R-EXTERN effect=pure extern=False
axiom Lean_Expr_mdata : Lean.MData → Lean.Expr → Lean.Expr
-- R-EXTERN effect=pure extern=False
axiom Lean_Expr_mvar : Lean.MVarId → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Expr_mvarId! : Lean.Expr → Lean.MVarId
-- R-NONE effect=pure extern=False
axiom Lean_Expr_ne? : Lean.Expr → Option (Lean.Expr × Lean.Expr × Lean.Expr)
-- R-NONE effect=pure extern=False
axiom Lean_Expr_not? : Lean.Expr → Option Lean.Expr
-- R-EXTERN effect=pure extern=False
axiom Lean_Expr_proj : Lean.Name → Nat → Lean.Expr → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Expr_rawNatLit? : Lean.Expr → Option Nat
-- R-EXTERN effect=pure extern=False
axiom Lean_Expr_sort : Lean.Level → Lean.Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_FVarId_getUserName : Lean.FVarId → Lean.Meta.MetaM Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_FVarId_name : Lean.FVarId → Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_FileMap_ofPosition : Lean.FileMap → Lean.Position → String.Pos.Raw
-- R-NONE effect=pure extern=False
axiom Lean_FileMap_toPosition : Lean.FileMap → String.Pos.Raw → Lean.Position
-- R-NONE effect=pure extern=False
axiom Lean_IR_getSorryDep : Lean.Environment → Lean.Name → Option Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_ImportM : Type → Type
-- R-NONE effect=pure extern=False
axiom Lean_ImportM_Context_casesOn.{u} : {motive : Lean.ImportM.Context → Sort u} → (t : Lean.ImportM.Context) → ((env : Lean.Environment) → (opts : Lean.Options) → motive { env := env, opts := opts }) → motive t
-- R-NONE effect=pure extern=False
axiom Lean_InductiveVal_all : Lean.InductiveVal → List Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_InductiveVal_ctors : Lean.InductiveVal → List Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_InductiveVal_isRec : Lean.InductiveVal → Bool
-- R-NONE effect=pure extern=False
axiom Lean_InductiveVal_isReflexive : Lean.InductiveVal → Bool
-- R-NONE effect=pure extern=False
axiom Lean_InductiveVal_isUnsafe : Lean.InductiveVal → Bool
-- R-NONE effect=pure extern=False
axiom Lean_InductiveVal_numIndices : Lean.InductiveVal → Nat
-- R-NONE effect=pure extern=False
axiom Lean_InductiveVal_numNested : Lean.InductiveVal → Nat
-- R-NONE effect=pure extern=False
axiom Lean_InductiveVal_numParams : Lean.InductiveVal → Nat
-- R-NONE effect=pure extern=False
axiom Lean_InductiveVal_toConstantVal : Lean.InductiveVal → Lean.ConstantVal
-- R-NONE effect=pure extern=False
axiom Lean_KVMap_instValueBool : Lean.KVMap.Value Bool
-- R-NONE effect=pure extern=False
axiom Lean_LMVarId : Type
-- R-NONE effect=pure extern=False
axiom Lean_Level_dec : Lean.Level → Option Lean.Level
-- R-EXTERN effect=pure extern=False
axiom Lean_Level_zero : Lean.Level
-- R-NONE effect=pure extern=False
axiom Lean_Linter_DeprecationEntry_since? : Lean.Linter.DeprecationEntry → Option String
-- R-NONE effect=pure extern=False
axiom Lean_Linter_deprecatedAttr : Lean.ParametricAttribute Lean.Linter.DeprecationEntry
-- R-NONE effect=pure extern=False
axiom Lean_Linter_getLinterOptions : {m : Type → Type} → [Monad m] → [Lean.MonadOptions m] → [Lean.MonadEnv m] → m Lean.Linter.LinterOptions
-- R-NONE effect=pure extern=False
axiom Lean_Linter_getLinterValue : Lean.Option Bool → Lean.Linter.LinterOptions → Bool
-- R-NONE effect=pure extern=False
axiom Lean_Linter_instInhabitedDeprecationEntry : Inhabited Lean.Linter.DeprecationEntry
-- R-NONE effect=pure extern=False
axiom Lean_Linter_logLint : {m : Type → Type} → [Monad m] → [Lean.MonadLog m] → [Lean.AddMessageContext m] → [Lean.MonadOptions m] → Lean.Option Bool → Lean.Syntax → Lean.MessageData → m Unit
-- R-NONE effect=pure extern=False
axiom Lean_LocalContext_find? : Lean.LocalContext → Lean.FVarId → Option Lean.LocalDecl
-- R-NONE effect=pure extern=False
axiom Lean_LocalContext_findFromUserName? : Lean.LocalContext → Lean.Name → Option Lean.LocalDecl
-- R-NONE effect=pure extern=False
axiom Lean_LocalContext_getFVarIds : Lean.LocalContext → Array Lean.FVarId
-- R-NONE effect=pure extern=False
axiom Lean_LocalContext_instForInLocalDeclOfMonad.{u_1, u_2} : {m : Type u_1 → Type u_2} → [Monad m] → ForIn m Lean.LocalContext Lean.LocalDecl
-- R-NONE effect=pure extern=False
axiom Lean_LocalDecl_fvarId : Lean.LocalDecl → Lean.FVarId
-- R-NONE effect=pure extern=False
axiom Lean_LocalDecl_userName : Lean.LocalDecl → Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_MData : Type
-- R-NONE effect=pure extern=False
axiom Lean_MVarId__sizeOf_inst : SizeOf Lean.MVarId
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_MVarId_changeLocalDecl : Lean.MVarId → Lean.FVarId → Lean.Expr → optParam Bool Bool.true → Lean.Meta.MetaM Lean.MVarId
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_MVarId_congrCore : Lean.MVarId → Lean.Meta.MetaM (List Lean.MVarId)
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_MVarId_congrN : Lean.MVarId → optParam Nat 1000000 → optParam Bool Bool.true → optParam Bool Bool.true → Lean.Meta.MetaM (List Lean.MVarId)
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_MVarId_getType : Lean.MVarId → Lean.Meta.MetaM Lean.Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_MVarId_intros : Lean.MVarId → Lean.Meta.MetaM (Array Lean.FVarId × Lean.MVarId)
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_MVarId_liftReflToEq : Lean.MVarId → Lean.Meta.MetaM Lean.MVarId
-- R-NONE effect=pure extern=False
axiom Lean_MVarId_name : Lean.MVarId → Lean.Name
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_MVarId_replaceLocalDecl : Lean.MVarId → Lean.FVarId → Lean.Expr → Lean.Expr → Lean.Meta.MetaM Lean.Meta.AssertAfterResult
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_MVarId_rewrite : Lean.MVarId → Lean.Expr → Lean.Expr → optParam Bool Bool.false → optParam Lean.Meta.Rewrite.Config { } → Lean.Meta.MetaM Lean.Meta.RewriteResult
-- R-NONE effect=pure extern=False
axiom Lean_MVarIdMap : Type → Type
-- R-NONE effect=pure extern=False
axiom Lean_MapDeclarationExtension_toPersistentEnvExtension : {α : Type} → Lean.MapDeclarationExtension α → Lean.PersistentEnvExtension (Lean.Name × α) (Lean.Name × α) (Lean.NameMap α)
-- R-NONE effect=pure extern=False
axiom Lean_Message : Type
-- R-NONE effect=pure extern=False
axiom Lean_MessageData_andList : List Lean.MessageData → Lean.MessageData
-- R-NONE effect=pure extern=False
axiom Lean_MessageData_instAppend : Append Lean.MessageData
-- R-NONE effect=pure extern=False
axiom Lean_MessageData_joinSep : List Lean.MessageData → Lean.MessageData → Lean.MessageData
-- R-NONE effect=pure extern=False
axiom Lean_MessageData_nil : Lean.MessageData
-- R-NONE effect=pure extern=False
axiom Lean_MessageData_note : Lean.MessageData → Lean.MessageData
-- R-NONE effect=pure extern=False
axiom Lean_MessageData_ofConstName : Lean.Name → optParam Bool Bool.false → Lean.MessageData
-- R-NONE effect=pure extern=False
axiom Lean_MessageData_ofExpr : Lean.Expr → Lean.MessageData
-- R-NONE effect=pure extern=False
axiom Lean_MessageData_ofFormat : Std.Format → Lean.MessageData
-- R-NONE effect=pure extern=False
axiom Lean_MessageData_ofSyntax : Lean.Syntax → Lean.MessageData
-- R-NONE effect=pure extern=False
axiom Lean_MessageLog_hasErrors : Lean.MessageLog → Bool
-- R-NONE effect=pure extern=False
axiom Lean_Meta_Ext_extExtension : Lean.SimpleScopedEnvExtension Lean.Meta.Ext.ExtTheorem Lean.Meta.Ext.ExtTheorems
-- R-NONE effect=pure extern=False
axiom Lean_Meta_MetaM : Type → Type
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_MetaM_run : {α : Type} → Lean.Meta.MetaM α → optParam Lean.Meta.Context { } → optParam Lean.Meta.State { } → Lean.Core.CoreM (α × Lean.Meta.State)
-- R-NONE effect=pure extern=False
axiom Lean_Meta_Rfl_reflExt : Lean.SimpleScopedEnvExtension (Lean.Name × Array Lean.Meta.DiscrTree.Key) (Lean.Meta.DiscrTree Lean.Name)
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_Simp_Context_mkDefault : Lean.Meta.MetaM Lean.Meta.Simp.Context
-- R-NONE effect=pure extern=False
axiom Lean_Meta_Simp_Discharge : Type
-- R-NONE effect=pure extern=False
axiom Lean_Meta_Simp_Simproc : Type
-- R-NONE effect=pure extern=False
axiom Lean_Meta_Simp_Stats_usedTheorems : Lean.Meta.Simp.Stats → Lean.Meta.Simp.UsedSimps
-- R-NONE effect=pure extern=False
axiom Lean_Meta_Simp_UsedSimps_map : Lean.Meta.Simp.UsedSimps → Lean.PHashMap Lean.Meta.Origin Nat
-- R-EXTERN effect=toolchain-monad extern=True
axiom Lean_Meta_Simp_dsimp : Lean.Expr → Lean.Meta.Simp.SimpM Lean.Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_Simp_getSimprocs : Lean.Core.CoreM Lean.Meta.Simp.Simprocs
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_Simp_mkDefaultMethods : Lean.Core.CoreM Lean.Meta.Simp.Methods
-- R-NONE effect=pure extern=False
axiom Lean_Meta_Simp_mkDefaultMethodsCore : Lean.Meta.Simp.SimprocsArray → Lean.Meta.Simp.Methods
-- R-NONE effect=pure extern=False
axiom Lean_Meta_Symm_symmExt : Lean.SimpleScopedEnvExtension (Lean.Name × Array Lean.Meta.DiscrTree.Key) (Lean.Meta.DiscrTree Lean.Name)
-- R-NONE effect=pure extern=False
axiom Lean_Meta_Tactic_TryThis_SuggestionStyle : Type
-- R-NONE effect=pure extern=False
axiom Lean_Meta_Tactic_TryThis_TryThisInfo_suggestion : Lean.Meta.Tactic.TryThis.TryThisInfo → Lean.Meta.Tactic.TryThis.Suggestion
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_Tactic_TryThis_addSuggestion : Lean.Syntax → Lean.Meta.Tactic.TryThis.Suggestion → optParam (Option Lean.Syntax) Option.none → optParam String "Try this:" → optParam (Option String) Option.none → optParam Lean.Meta.Hint.DiffGranularity Lean.Meta.Hint.DiffGranularity.none → optParam Lean.MessageData Lean.MessageData.nil → Lean.Core.CoreM Unit
-- R-NONE effect=pure extern=False
axiom Lean_Meta_Tactic_TryThis_instTypeNameTryThisInfo : TypeName Lean.Meta.Tactic.TryThis.TryThisInfo
-- R-NONE effect=pure extern=False
axiom Lean_Meta_approxDefEq.{u_1} : {n : Type → Type u_1} → [MonadControlT Lean.Meta.MetaM n] → [Monad n] → {α : Type} → n α → n α
-- R-NONE effect=pure extern=False
axiom Lean_Meta_coeExt : Lean.SimpleScopedEnvExtension (Lean.Name × Lean.Meta.CoeFnInfo) (Lean.NameMap Lean.Meta.CoeFnInfo)
-- R-UNSAFE effect=toolchain-monad extern=False
axiom Lean_Meta_evalExpr : (α : Type) → Lean.Expr → Lean.Expr → optParam Lean.DefinitionSafety Lean.DefinitionSafety.safe → optParam Bool Bool.true → Lean.Meta.MetaM α
-- R-NONE effect=pure extern=False
axiom Lean_Meta_forallTelescope.{u_1} : {n : Type → Type u_1} → [MonadControlT Lean.Meta.MetaM n] → [Monad n] → {α : Type} → Lean.Expr → (Array Lean.Expr → Lean.Expr → n α) → optParam Bool Bool.false → n α
-- R-NONE effect=pure extern=False
axiom Lean_Meta_forallTelescopeReducing.{u_1} : {n : Type → Type u_1} → [MonadControlT Lean.Meta.MetaM n] → [Monad n] → {α : Type} → Lean.Expr → (Array Lean.Expr → Lean.Expr → n α) → optParam Bool Bool.false → optParam Bool Bool.false → n α
-- R-EXTERN effect=toolchain-monad extern=True
axiom Lean_Meta_inferType : Lean.Expr → Lean.Meta.MetaM Lean.Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_instAddMessageContextMetaM : Lean.AddMessageContext Lean.Meta.MetaM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_instAlternativeMetaM : Alternative Lean.Meta.MetaM
-- R-NONE effect=pure extern=False
axiom Lean_Meta_instBEqOrigin : BEq Lean.Meta.Origin
-- R-NONE effect=pure extern=False
axiom Lean_Meta_instHashableOrigin : Hashable Lean.Meta.Origin
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_instMonadEnvMetaM : Lean.MonadEnv Lean.Meta.MetaM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_instMonadLCtxMetaM : Lean.MonadLCtx Lean.Meta.MetaM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_instMonadMCtxMetaM : Lean.MonadMCtx Lean.Meta.MetaM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_instMonadMetaM : Monad Lean.Meta.MetaM
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_isInstance : Lean.Name → Lean.Core.CoreM Bool
-- R-NONE effect=pure extern=False
axiom Lean_Meta_isMatcher : {m : Type → Type} → [Monad m] → [Lean.MonadEnv m] → Lean.Name → m Bool
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_isProof : Lean.Expr → Lean.Meta.MetaM Bool
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_isProp : Lean.Expr → Lean.Meta.MetaM Bool
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_mkAdd : Lean.Expr → Lean.Expr → Lean.Meta.MetaM Lean.Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_mkAppM : Lean.Name → Array Lean.Expr → Lean.Meta.MetaM Lean.Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_mkAppOptM : Lean.Name → Array (Option Lean.Expr) → Lean.Meta.MetaM Lean.Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_mkAuxTheorem : Lean.Expr → Lean.Expr → optParam Bool Bool.false → optParam (Option Lean.Name) Option.none → optParam Bool Bool.true → Lean.Meta.MetaM Lean.Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_mkForallFVars : Array Lean.Expr → Lean.Expr → optParam Bool Bool.false → optParam Bool Bool.true → optParam Bool Bool.true → optParam Lean.BinderInfo Lean.BinderInfo.implicit → Lean.Meta.MetaM Lean.Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_mkFreshExprMVar : Option Lean.Expr → optParam Lean.MetavarKind Lean.MetavarKind.natural → optParam Lean.Name Lean.Name.anonymous → Lean.Meta.MetaM Lean.Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_mkFreshLevelMVar : Lean.Meta.MetaM Lean.Level
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_mkHCongrWithArity : Lean.Expr → Nat → Lean.Meta.MetaM Lean.Meta.CongrTheorem
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_mkLambdaFVars : Array Lean.Expr → Lean.Expr → optParam Bool Bool.false → optParam Bool Bool.true → optParam Bool Bool.false → optParam Bool Bool.true → optParam Lean.BinderInfo Lean.BinderInfo.implicit → Lean.Meta.MetaM Lean.Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_mkMul : Lean.Expr → Lean.Expr → Lean.Meta.MetaM Lean.Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_mkSorry : Lean.Expr → Bool → Lean.Meta.MetaM Lean.Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_registerCoercion : Lean.Name → optParam (Option Lean.Meta.CoeFnInfo) Option.none → Lean.Meta.MetaM Unit
-- R-EFFECT effect=io extern=False
axiom Lean_Meta_registerGetEqnsFn : Lean.Meta.GetEqnsFn → IO Unit
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_simpGoal : Lean.MVarId → Lean.Meta.Simp.Context → optParam Lean.Meta.Simp.SimprocsArray #[] → optParam (Option Lean.Meta.Simp.Discharge) Option.none → optParam Bool Bool.true → optParam (Array Lean.FVarId) #[] → optParam Lean.Meta.Simp.Stats { } → Lean.Meta.MetaM (Option (Array Lean.FVarId × Lean.MVarId) × Lean.Meta.Simp.Stats)
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_synthInstance : Lean.Expr → optParam (Option Nat) Option.none → Lean.Meta.MetaM Lean.Expr
-- R-NONE effect=pure extern=False pp=explicit
axiom Lean_Meta_transform : {m : Type → Type} → [inst : Monad m] → [MonadLiftT Lean.Meta.MetaM m] → [MonadControlT Lean.Meta.MetaM m] → Lean.Expr → (optParam (Lean.Expr → m Lean.TransformStep) fun x => @Pure.pure m (@Applicative.toPure m (@Monad.toApplicative m inst)) Lean.TransformStep (Lean.TransformStep.continue (@Option.none Lean.Expr))) → (optParam (Lean.Expr → m Lean.TransformStep) fun e => @Pure.pure m (@Applicative.toPure m (@Monad.toApplicative m inst)) Lean.TransformStep (Lean.TransformStep.done e)) → optParam Bool Bool.false → optParam Bool Bool.false → m Lean.Expr
-- R-EXTERN effect=toolchain-monad extern=True
axiom Lean_Meta_whnf : Lean.Expr → Lean.Meta.MetaM Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Meta_withLocalDeclD.{u_1} : {n : Type → Type u_1} → [MonadControlT Lean.Meta.MetaM n] → [Monad n] → {α : Type} → Lean.Name → Lean.Expr → (Lean.Expr → n α) → n α
-- R-NONE effect=pure extern=False
axiom Lean_Meta_withMCtx.{u_1} : {n : Type → Type u_1} → [MonadControlT Lean.Meta.MetaM n] → [Monad n] → {α : Type} → Lean.MetavarContext → n α → n α
-- R-NONE effect=pure extern=False
axiom Lean_Meta_withReducible.{u_1} : {n : Type → Type u_1} → [MonadControlT Lean.Meta.MetaM n] → [Monad n] → {α : Type} → n α → n α
-- R-NONE effect=pure extern=False
axiom Lean_MetavarContext__sizeOf_inst : SizeOf Lean.MetavarContext
-- R-NONE effect=pure extern=False
axiom Lean_MetavarContext_decls : Lean.MetavarContext → Lean.PersistentHashMap Lean.MVarId Lean.MetavarDecl
-- R-NONE effect=pure extern=False
axiom Lean_MetavarContext_findDecl? : Lean.MetavarContext → Lean.MVarId → Option Lean.MetavarDecl
-- R-NONE effect=pure extern=False
axiom Lean_MetavarDecl_lctx : Lean.MetavarDecl → Lean.LocalContext
-- R-NONE effect=pure extern=False
axiom Lean_MetavarDecl_type : Lean.MetavarDecl → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_ModuleIdx : Type
-- R-NONE effect=pure extern=False pp=explicit
axiom Lean_MonadEnv_getEnv : {m : Type → Type} → [self : Lean.MonadEnv m] → m Lean.Environment
-- R-NONE effect=pure extern=False pp=explicit
axiom Lean_MonadFileMap_getFileMap : {m : Type → Type} → [self : Lean.MonadFileMap m] → m Lean.FileMap
-- R-NONE effect=pure extern=False pp=explicit
axiom Lean_MonadLCtx_getLCtx : {m : Type → Type} → [self : Lean.MonadLCtx m] → m Lean.LocalContext
-- R-NONE effect=pure extern=False pp=explicit
axiom Lean_MonadLog_toMonadFileMap : {m : Type → Type} → [self : Lean.MonadLog m] → Lean.MonadFileMap m
-- R-NONE effect=pure extern=False pp=explicit
axiom Lean_MonadOptions_getOptions : {m : Type → Type} → [self : Lean.MonadOptions m] → m Lean.Options
-- R-NONE effect=pure extern=False pp=explicit
axiom Lean_MonadResolveName_getCurrNamespace : {m : Type → Type} → [self : Lean.MonadResolveName m] → m Lean.Name
-- R-EXTERN effect=pure extern=False
axiom Lean_Name_anonymous : Lean.Name
-- R-EXTERN effect=pure extern=False
axiom Lean_Name_casesOn.{u} : {motive : Lean.Name → Sort u} → (t : Lean.Name) → motive Lean.Name.anonymous → ((pre : Lean.Name) → (str : String) → motive (pre.str str)) → ((pre : Lean.Name) → (i : Nat) → motive (pre.num i)) → motive t
-- R-NONE effect=pure extern=False
axiom Lean_Name_cmp : Lean.Name → Lean.Name → Ordering
-- R-NONE effect=pure extern=False
axiom Lean_Name_components : Lean.Name → List Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_Name_componentsRev : Lean.Name → List Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_Name_isInternalDetail : Lean.Name → Bool
-- R-EXTERN effect=pure extern=False
axiom Lean_Name_num : Lean.Name → Nat → Lean.Name
-- R-EXTERN effect=pure extern=False
axiom Lean_Name_str : Lean.Name → String → Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_Name_updatePrefix : Lean.Name → Lean.Name → Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_NameMap : Type → Type
-- R-NONE effect=pure extern=False
axiom Lean_NameMap_instEmptyCollection : (α : Type) → EmptyCollection (Lean.NameMap α)
-- R-NONE effect=pure extern=False
axiom Lean_NameMap_instForInProdNameOfMonad.{u_1, u_2} : {α : Type} → {m : Type u_1 → Type u_2} → [Monad m] → ForIn m (Lean.NameMap α) (Lean.Name × α)
-- R-NONE effect=pure extern=False
axiom Lean_NameMap_instInhabited : (α : Type) → Inhabited (Lean.NameMap α)
-- R-NONE effect=pure extern=False
axiom Lean_OLeanEntries_uniform : {α : Type} → α → Lean.OLeanEntries α
-- R-NONE effect=pure extern=False
axiom Lean_OpaqueVal_all : Lean.OpaqueVal → List Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_OpaqueVal_isUnsafe : Lean.OpaqueVal → Bool
-- R-NONE effect=pure extern=False
axiom Lean_OpaqueVal_toConstantVal : Lean.OpaqueVal → Lean.ConstantVal
-- R-NONE effect=pure extern=False
axiom Lean_OpaqueVal_value : Lean.OpaqueVal → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_Option__sizeOf_inst : (α : Type) → [SizeOf α] → SizeOf (Lean.Option α)
-- R-NONE effect=pure extern=False
axiom Lean_Option_name : {α : Type} → Lean.Option α → Lean.Name
-- R-EFFECT effect=io extern=False
axiom Lean_Option_register : {α : Type} → [Lean.KVMap.Value α] → Lean.Name → Lean.Option.Decl α → autoParam Lean.Name Lean.Option.register._auto_1 → IO (Lean.Option α)
-- R-NONE effect=pure extern=False
axiom Lean_Options_instEmptyCollection : EmptyCollection Lean.Options
-- R-NONE effect=pure extern=False
axiom Lean_ParametricAttribute_getParam? : {α : Type} → [Inhabited α] → Lean.ParametricAttribute α → Lean.Environment → Lean.Name → Option α
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_declId : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_declaration : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_deprecated_module : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_docComment : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_eoi : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_example : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_exit : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_export : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_in : Lean.Parser.TrailingParser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_instance : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_macro_rules : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_mixfix : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_moduleDoc : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_notation : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_private : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_registerTryTactic : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_set_option : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Module_header : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Module_import : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Module_module : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Conv_conv : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_allGoals : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_anyGoals : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_cases : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_failIfSuccess : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_first : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_focus : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_grindRepeat_ : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_grindSeq : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_grindSeq1Indented : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_grindSeqBracketed : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_instantiate : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_next : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_skip : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_acRfl : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_allGoals : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_anchor : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_anyGoals : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_apply : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_case : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_cases : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_congr : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_constructor : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_decide : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_discharger : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_done : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_dsimp : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_failIfSuccess : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_first : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_focus : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_grind : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_grindLemma : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_grindParam : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_grindTrace : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_grobner : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_guardHyp : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_guardTarget : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_induction : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_injections : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_intros : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_lia : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_location : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_nativeDecide : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_obtain : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_omega : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_optConfig : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_paren : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_quotSeq : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_rcases : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_rcasesPatMed : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_refine : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_replace : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_rotateLeft : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_rotateRight : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_rwRule : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_rwRuleSeq : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_show : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_simp : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_simpAll : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_simpStar : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_simpa : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_simpaUsingBang : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_skip : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_specialize : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_split : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_subst : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_substVars : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticAdmit : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticHave__ : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticIterate____ : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticLet__ : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticNorm_cast__ : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticRepeat_ : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticRfl : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticSeq : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticSeq1Indented : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticSeqBracketed : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticSorry : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticStop_ : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticSuffices_ : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticTry_ : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_traceMessage : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_traceState : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_withAnnotateState : Lean.ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Term_app : Lean.Parser.TrailingParser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Term_attributes : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Term_byTactic : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Term_cdot : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Term_dynamicQuot : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Term_matchDiscr : Lean.Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_PersistentArray_branching : USize
-- R-NONE effect=pure extern=False
axiom Lean_PersistentArray_findSomeM?.{u, v, w} : {α : Type u} → {m : Type v → Type w} → [Monad m] → {β : Type v} → Lean.PersistentArray α → (α → m (Option β)) → m (Option β)
-- R-NONE effect=pure extern=False
axiom Lean_PersistentArray_foldl.{u, u_1} : {α : Type u} → {β : Type u_1} → Lean.PersistentArray α → (β → α → β) → β → optParam Nat 0 → β
-- R-NONE effect=pure extern=False
axiom Lean_PersistentArray_initShift : USize
-- R-NONE effect=pure extern=False
axiom Lean_PersistentArray_instForInOfMonad.{u, v, w} : {α : Type u} → {m : Type v → Type w} → [Monad m] → ForIn m (Lean.PersistentArray α) α
-- R-NONE effect=pure extern=False
axiom Lean_PersistentArray_instGetElemNatLtSizeOfInhabited.{u} : {α : Type u} → [Inhabited α] → GetElem (Lean.PersistentArray α) Nat α fun as i => i < as.size
-- R-NONE effect=pure extern=False
axiom Lean_PersistentArray_size.{u} : {α : Type u} → Lean.PersistentArray α → Nat
-- R-NONE effect=pure extern=False
axiom Lean_PersistentEnvExtension_addEntry : {α β σ : Type} → (ext : Lean.PersistentEnvExtension α β σ) → Lean.Environment → β → optParam Lean.EnvExtension.AsyncMode ext.toEnvExtension.asyncMode → optParam Lean.Name Lean.Name.anonymous → Lean.Environment
-- R-NONE effect=pure extern=False
axiom Lean_PersistentEnvExtension_getState : {α β σ : Type} → [Inhabited σ] → (ext : Lean.PersistentEnvExtension α β σ) → Lean.Environment → optParam Lean.EnvExtension.AsyncMode ext.toEnvExtension.asyncMode → optParam Lean.Name Lean.Name.anonymous → σ
-- R-NONE effect=pure extern=False
axiom Lean_PersistentEnvExtension_toEnvExtension : {α β σ : Type} → Lean.PersistentEnvExtension α β σ → Lean.EnvExtension (Lean.PersistentEnvExtensionState α σ)
-- R-NONE effect=pure extern=False pp=explicit
axiom Lean_PersistentHashMap_find?.{u_1, u_2} : {α : Type u_1} → {β : Type u_2} → {x : BEq α} → {x_1 : Hashable α} → @Lean.PersistentHashMap α β x x_1 → α → Option β
-- R-NONE effect=pure extern=False pp=explicit
axiom Lean_PersistentHashMap_findD.{u_1, u_2} : {α : Type u_1} → {β : Type u_2} → {x : BEq α} → {x_1 : Hashable α} → @Lean.PersistentHashMap α β x x_1 → α → β → β
-- R-NONE effect=pure extern=False pp=explicit
axiom Lean_PersistentHashMap_isEmpty.{u_1, u_2} : {α : Type u_1} → {β : Type u_2} → {x : BEq α} → {x_1 : Hashable α} → @Lean.PersistentHashMap α β x x_1 → Bool
-- R-NONE effect=pure extern=False
axiom Lean_PersistentHashMap_mkEmptyEntriesArray.{u_1, u_2} : {α : Type u_1} → {β : Type u_2} → Array (Lean.PersistentHashMap.Entry α β (Lean.PersistentHashMap.Node α β))
-- R-NONE effect=pure extern=False
axiom Lean_Position_line : Lean.Position → Nat
-- R-NONE effect=pure extern=False
axiom Lean_PrettyPrinter_Parenthesizer : Type
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_PrettyPrinter_delab : Lean.Expr → optParam Lean.PrettyPrinter.Delaborator.OptionsPerPos ∅ → Lean.Meta.MetaM Lean.Syntax.Term
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_PrettyPrinter_ppTactic : Lean.TSyntax `tactic → Lean.Core.CoreM Std.Format
-- R-NONE effect=pure extern=False
axiom Lean_ProjectionFunctionInfo_ctorName : Lean.ProjectionFunctionInfo → Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_ProjectionFunctionInfo_i : Lean.ProjectionFunctionInfo → Nat
-- R-NONE effect=pure extern=False
axiom Lean_ProjectionFunctionInfo_numParams : Lean.ProjectionFunctionInfo → Nat
-- R-NONE effect=pure extern=False
axiom Lean_QuotVal_kind : Lean.QuotVal → Lean.QuotKind
-- R-NONE effect=pure extern=False
axiom Lean_RecursorVal_all : Lean.RecursorVal → List Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_RecursorVal_isUnsafe : Lean.RecursorVal → Bool
-- R-NONE effect=pure extern=False
axiom Lean_RecursorVal_k : Lean.RecursorVal → Bool
-- R-NONE effect=pure extern=False
axiom Lean_RecursorVal_numIndices : Lean.RecursorVal → Nat
-- R-NONE effect=pure extern=False
axiom Lean_RecursorVal_numMinors : Lean.RecursorVal → Nat
-- R-NONE effect=pure extern=False
axiom Lean_RecursorVal_numMotives : Lean.RecursorVal → Nat
-- R-NONE effect=pure extern=False
axiom Lean_RecursorVal_numParams : Lean.RecursorVal → Nat
-- R-NONE effect=pure extern=False
axiom Lean_RecursorVal_rules : Lean.RecursorVal → List Lean.RecursorRule
-- R-NONE effect=pure extern=False
axiom Lean_ReplayFn : Type → Type
-- R-NONE effect=pure extern=False
axiom Lean_ReservedNameAction : Type
-- R-NONE effect=pure extern=False
axiom Lean_StructureInfo_fieldNames : Lean.StructureInfo → Array Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_Syntax_getAtomVal : Lean.Syntax → String
-- R-NONE effect=pure extern=False
axiom Lean_Syntax_getRange? : Lean.Syntax → optParam Bool Bool.false → Option Lean.Syntax.Range
-- R-NONE effect=pure extern=False
axiom Lean_Syntax_instInhabitedRange : Inhabited Lean.Syntax.Range
-- R-NONE effect=pure extern=False
axiom Lean_Syntax_ofRange : Lean.Syntax.Range → optParam Bool Bool.true → Lean.Syntax
-- R-NONE effect=pure extern=False
axiom Lean_Syntax_reprint : Lean.Syntax → Option String
-- R-EXTERN effect=pure extern=False
axiom Lean_TSyntaxArray_mk : {ks : Lean.SyntaxNodeKinds} → Array Lean.Syntax → Lean.TSyntaxArray ks
-- R-EXTERN effect=pure extern=False
axiom Lean_TSyntaxArray_raw : {ks : Lean.SyntaxNodeKinds} → Lean.TSyntaxArray ks → Array Lean.Syntax
-- R-NONE effect=pure extern=False
axiom Lean_TheoremVal_all : Lean.TheoremVal → List Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_TheoremVal_toConstantVal : Lean.TheoremVal → Lean.ConstantVal
-- R-NONE effect=pure extern=False
axiom Lean_TheoremVal_value : Lean.TheoremVal → Lean.Expr
-- R-NONE effect=pure extern=False pp=explicit
axiom Lean_ToMessageData_toMessageData : {α : Type} → [self : Lean.ToMessageData α] → α → Lean.MessageData
-- R-NONE effect=pure extern=False
axiom Lean_declRangeExt : Lean.MapDeclarationExtension Lean.DeclarationRanges
-- R-NONE effect=pure extern=False
axiom Lean_findField? : Lean.Environment → Lean.Name → Lean.Name → Option Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_getConstInfo : {m : Type → Type} → [Monad m] → [Lean.MonadEnv m] → [Lean.MonadError m] → Lean.Name → m Lean.ConstantInfo
-- R-NONE effect=pure extern=False
axiom Lean_getPathToBaseStructure? : Lean.Environment → Lean.Name → Lean.Name → Option (List Lean.Name)
-- R-NONE effect=pure extern=False
axiom Lean_getProjFnForField? : Lean.Environment → Lean.Name → Lean.Name → Option Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_getProjectionFnInfo? : {m : Type → Type} → [Lean.MonadEnv m] → [Monad m] → Lean.Name → m (Option Lean.ProjectionFunctionInfo)
-- R-NONE effect=pure extern=False
axiom Lean_getStructureFields : Lean.Environment → Lean.Name → Array Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_getStructureInfo? : Lean.Environment → Lean.Name → Option Lean.StructureInfo
-- R-NONE effect=pure extern=False
axiom Lean_indentExpr : Lean.Expr → Lean.MessageData
-- R-NONE effect=pure extern=False
axiom Lean_instAddErrorMessageContextOfAddMessageContextOfMonad : (m : Type → Type) → [Lean.AddMessageContext m] → [Monad m] → Lean.AddErrorMessageContext m
-- R-NONE effect=pure extern=False
axiom Lean_instAddMessageContextOfMonadLift : (m n : Type → Type) → [MonadLift m n] → [Lean.AddMessageContext m] → Lean.AddMessageContext n
-- R-NONE effect=pure extern=False
axiom Lean_instBEqAttributeKind : BEq Lean.AttributeKind
-- R-NONE effect=pure extern=False
axiom Lean_instBEqFVarId : BEq Lean.FVarId
-- R-NONE effect=pure extern=False
axiom Lean_instBEqLevelMVarId : BEq Lean.LevelMVarId
-- R-NONE effect=pure extern=False
axiom Lean_instBEqMVarId : BEq Lean.MVarId
-- R-NONE effect=pure extern=False
axiom Lean_instEmptyCollectionMVarIdMap : {α : Type} → EmptyCollection (Lean.MVarIdMap α)
-- R-NONE effect=pure extern=False
axiom Lean_instHashableFVarId : Hashable Lean.FVarId
-- R-NONE effect=pure extern=False
axiom Lean_instHashableLevelMVarId : Hashable Lean.LevelMVarId
-- R-NONE effect=pure extern=False
axiom Lean_instHashableMVarId : Hashable Lean.MVarId
-- R-NONE effect=pure extern=False
axiom Lean_instInhabitedDeclaration : Inhabited Lean.Declaration
-- R-NONE effect=pure extern=False
axiom Lean_instInhabitedFVarId : Inhabited Lean.FVarId
-- R-NONE effect=pure extern=False
axiom Lean_instInhabitedLocalDecl : Inhabited Lean.LocalDecl
-- R-NONE effect=pure extern=False
axiom Lean_instInhabitedMetavarDecl : Inhabited Lean.MetavarDecl
-- R-NONE effect=pure extern=False
axiom Lean_instInhabitedStructureInfo : Inhabited Lean.StructureInfo
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_instMonadExceptOfExceptionCoreM : MonadExceptOf Lean.Exception Lean.Core.CoreM
-- R-NONE effect=pure extern=False
axiom Lean_instMonadLCtxOfMonadLift : {m n : Type → Type} → [MonadLift m n] → [Lean.MonadLCtx m] → Lean.MonadLCtx n
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_instMonadLiftImportMAttrM : MonadLift Lean.ImportM Lean.AttrM
-- R-NONE effect=pure extern=False
axiom Lean_instMonadMCtxOfMonadLift : (m n : Type → Type) → [MonadLift m n] → [Lean.MonadMCtx m] → Lean.MonadMCtx n
-- R-NONE effect=pure extern=False
axiom Lean_instToMessageDataExpr : Lean.ToMessageData Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_instToMessageDataMessageData : Lean.ToMessageData Lean.MessageData
-- R-NONE effect=pure extern=False
axiom Lean_instToMessageDataName : Lean.ToMessageData Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_instToMessageDataOfToFormat : {α : Type} → [Std.ToFormat α] → Lean.ToMessageData α
-- R-NONE effect=pure extern=False
axiom Lean_instToMessageDataString : Lean.ToMessageData String
-- R-NONE effect=pure extern=False
axiom Lean_instToMessageDataTSyntax : {k : Lean.SyntaxNodeKinds} → Lean.ToMessageData (Lean.TSyntax k)
-- R-NONE effect=pure extern=False
axiom Lean_instantiateMVarDeclMVars : {m : Type → Type} → [Monad m] → [Lean.MonadMCtx m] → Lean.MVarId → m Unit
-- R-NONE effect=pure extern=False
axiom Lean_instantiateMVars : {m : Type → Type} → [Monad m] → [Lean.MonadMCtx m] → Lean.Expr → m Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_isAuxRecursor : Lean.Environment → Lean.Name → Bool
-- R-NONE effect=pure extern=False
axiom Lean_isNoConfusion : Lean.Environment → Lean.Name → Bool
-- R-NONE effect=pure extern=False
axiom Lean_isPrivateName : Lean.Name → Bool
-- R-NONE effect=pure extern=False
axiom Lean_isRec : {m : Type → Type} → [Monad m] → [Lean.MonadEnv m] → Lean.Name → m Bool
-- R-NONE effect=pure extern=False
axiom Lean_isStructure : Lean.Environment → Lean.Name → Bool
-- R-NONE effect=pure extern=False
axiom Lean_isSubobjectField? : Lean.Environment → Lean.Name → Lean.Name → Option Lean.Name
-- R-NONE effect=pure extern=False
axiom Lean_logInfoAt : {m : Type → Type} → [Monad m] → [Lean.MonadLog m] → [Lean.AddMessageContext m] → [Lean.MonadOptions m] → Lean.Syntax → Lean.MessageData → m Unit
-- R-NONE effect=pure extern=False
axiom Lean_logWarning : {m : Type → Type} → [Monad m] → [Lean.MonadLog m] → [Lean.AddMessageContext m] → [Lean.MonadOptions m] → Lean.MessageData → m Unit
-- R-NONE effect=pure extern=False
axiom Lean_logWarningAt : {m : Type → Type} → [Monad m] → [Lean.MonadLog m] → [Lean.AddMessageContext m] → [Lean.MonadOptions m] → Lean.Syntax → Lean.MessageData → m Unit
-- R-NONE effect=pure extern=False
axiom Lean_mkApp : Lean.Expr → Lean.Expr → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_mkApp3 : Lean.Expr → Lean.Expr → Lean.Expr → Lean.Expr → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_mkAppN : Lean.Expr → Array Lean.Expr → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_mkConst : Lean.Name → optParam (List Lean.Level) [] → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_mkConstWithLevelParams : {m : Type → Type} → [Monad m] → [Lean.MonadEnv m] → [Lean.MonadError m] → Lean.Name → m Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_mkNot : Lean.Expr → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_mkRawNatLit : Nat → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_mkSort : Lean.Level → Lean.Expr
-- R-NONE effect=pure extern=False
axiom Lean_profileitM : {m : Type → Type} → (ε : Type) → [MonadFunctorT (EIO ε) m] → {α : Type} → String → Lean.Options → m α → optParam Lean.Name Lean.Name.anonymous → m α
-- R-EFFECT effect=io extern=False
axiom Lean_registerBuiltinAttribute : Lean.AttributeImpl → IO Unit
-- R-EXTERN effect=io extern=False
axiom Lean_registerPersistentEnvExtension : {α β σ : Type} → [Inhabited σ] → Lean.PersistentEnvExtensionDescr α β σ → IO (Lean.PersistentEnvExtension α β σ)
-- R-NONE effect=pure extern=False
axiom Lean_setEnv : {m : Type → Type} → [Lean.MonadEnv m] → Lean.Environment → m Unit
-- R-NONE effect=pure extern=False
axiom Lean_throwError : {m : Type → Type} → {α : Type} → [Monad m] → [Lean.MonadError m] → Lean.MessageData → m α
-- R-NONE effect=pure extern=False
axiom Lean_withHeartbeats.{u_1} : {m : Type → Type u_1} → {α : Type} → [Monad m] → [MonadLiftT BaseIO m] → m α → m (α × Nat)
-- R-NONE effect=pure extern=False
axiom Lean_withSetOptionIn : Lean.Elab.Command.CommandElab → Lean.Elab.Command.CommandElab
-- R-EXTERN effect=pure extern=True
axiom Nat_ble : Nat → Nat → Bool
-- R-EXTERN effect=pure extern=True
axiom Nat_decEq : (n m : Nat) → Decidable (n = m)
-- R-EXTERN effect=pure extern=True
axiom Nat_decLe : (n m : Nat) → Decidable (n ≤ m)
-- R-EXTERN effect=pure extern=True
axiom Nat_decLt : (n m : Nat) → Decidable (n < m)
-- R-EXTERN effect=pure extern=True
axiom Nat_land : Nat → Nat → Nat
-- R-EXTERN effect=pure extern=True
axiom Nat_pred : Nat → Nat
-- R-EXTERN effect=pure extern=True
axiom Nat_shiftRight : Nat → Nat → Nat
-- R-EFFECT effect=monad-transformer extern=False
axiom ReaderT_instApplicativeOfMonad.{u, v} : {ρ : Type u} → {m : Type u → Type v} → [Monad m] → Applicative (ReaderT ρ m)
-- R-EFFECT effect=monad-transformer extern=False
axiom ReaderT_instMonad.{u, v} : {ρ : Type u} → {m : Type u → Type v} → [Monad m] → Monad (ReaderT ρ m)
-- R-EFFECT effect=monad-transformer extern=False
axiom ReaderT_instMonadExceptOf.{u, v, u_1} : {ρ : Type u} → {m : Type u → Type v} → (ε : Type u_1) → [MonadExceptOf ε m] → MonadExceptOf ε (ReaderT ρ m)
-- R-EFFECT effect=monad-transformer extern=False
axiom ReaderT_instMonadFunctor.{u_1, u_2} : (ρ : Type u_1) → (m : Type u_1 → Type u_2) → MonadFunctor m (ReaderT ρ m)
-- R-EFFECT effect=monad-transformer extern=False
axiom ReaderT_instMonadLift.{u, v} : {ρ : Type u} → {m : Type u → Type v} → MonadLift m (ReaderT ρ m)
-- R-EXTERN effect=pure extern=True
axiom USize_toNat : USize → Nat
-- R-EXTERN effect=pure extern=True
axiom dbgTrace.{u} : {α : Type u} → String → (Unit → α) → α
-- R-EFFECT effect=io extern=False
axiom instMonadEIO : {ε : Type} → Monad (EIO ε)
-- R-EFFECT effect=io extern=False
axiom instMonadLiftBaseIOEIO : {ε : Type} → MonadLift BaseIO (EIO ε)
-- R-EFFECT effect=monad-transformer extern=False
axiom instMonadReaderOfReaderTOfMonad.{u, v} : {ρ : Type u} → {m : Type u → Type v} → [Monad m] → MonadReaderOf ρ (ReaderT ρ m)
-- R-EXTERN effect=pure extern=True
axiom mixHash : UInt64 → UInt64 → UInt64

end FlnFacade
