-- GENERATED by scripts/extract/facade_stubs.py from the pinned Reference
-- (v4.32.0) — Mirror facade stubs for the demanded toolchain surface
-- (bead fln-l8f, G0-8 acceptance b). DO NOT EDIT.
--
-- Each stub is an `axiom`: a facade DECLARES the symbol's type and leaves
-- the implementation to the native mirror. The bucket comment carries the
-- resistance class from contracts/facade_resistance.ndjson, so the L-level
-- ratchet is readable in the generated artifact rather than only beside it.
namespace FlnFacade

-- R-NONE effect=pure extern=False
axiom Lean_Core_CoreM : Type → Type
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Core_checkSystem : String → CoreM Unit
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Command_liftTermElabM : {α : Type} → Elab.TermElabM α → Elab.Command.CommandElabM α
-- R-NONE effect=pure extern=False
axiom Lean_Elab_InfoTree_foldInfo : {α : Type u_1} → (Elab.ContextInfo → Elab.Info → α → α) → α → Elab.InfoTree → α
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_RCases_rcases : Array (Option Ident × Syntax) → Elab.Tactic.RCases.RCasesPatt → MVarId → Elab.TermElabM (List MVarId)
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_RCases_rintro : TSyntaxArray `rintroPat → Option Term → MVarId → Elab.TermElabM (List MVarId)
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Tactic_evalAllGoals : Elab.Tactic.Tactic
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_evalTactic : Syntax → Elab.Tactic.TacticM Unit
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_mkSimpContext : Syntax → Bool → optParam Elab.Tactic.SimpKind Elab.Tactic.SimpKind.simp → optParam Bool false → optParam (CoreM Meta.SimpTheorems) Meta.getSimpTheorems → Elab.Tactic.TacticM Elab.Tactic.MkSimpContextResult
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_mkSimpOnly : Syntax → Meta.Simp.UsedSimps → MetaM Syntax
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Tactic_run : MVarId → Elab.Tactic.TacticM Unit → Elab.TermElabM (List MVarId)
-- R-NONE effect=pure extern=False
axiom Lean_Elab_TacticInfo_goalsAfter : Elab.TacticInfo → List MVarId
-- R-NONE effect=pure extern=False
axiom Lean_Elab_TacticInfo_goalsBefore : Elab.TacticInfo → List MVarId
-- R-NONE effect=pure extern=False
axiom Lean_Elab_Term_TermElab : Type
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Term_elabTermAndSynthesize : Syntax → Option Expr → Elab.TermElabM Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_Term_mkCalcStepViews : TSyntax `Lean.calcSteps → Elab.TermElabM (Array Elab.Term.CalcStepView)
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Elab_runTactic : MVarId → Syntax → optParam Elab.Term.Context { } → optParam Elab.Term.State { } → MetaM (List MVarId × Elab.Term.State)
-- R-NONE effect=pure extern=False
axiom Lean_Elab_throwUnsupportedSyntax : {m : Type u_1 → Type u_2} → {α : Type u_1} → [MonadExceptOf Exception m] → m α
-- R-NONE effect=pure extern=False
axiom Lean_Linter_deprecatedAttr : ParametricAttribute Linter.DeprecationEntry
-- R-NONE effect=pure extern=False
axiom Lean_Linter_logLint : {m : Type → Type} → [Monad m] → [MonadLog m] → [AddMessageContext m] → [MonadOptions m] → Lean.Option Bool → Syntax → MessageData → m Unit
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_MVarId_changeLocalDecl : MVarId → FVarId → Expr → optParam Bool true → MetaM MVarId
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_MVarId_congrCore : MVarId → MetaM (List MVarId)
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_MVarId_congrN : MVarId → optParam Nat 1000000 → optParam Bool true → optParam Bool true → MetaM (List MVarId)
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_MVarId_intros : MVarId → MetaM (Array FVarId × MVarId)
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_MVarId_liftReflToEq : MVarId → MetaM MVarId
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_MVarId_replaceLocalDecl : MVarId → FVarId → Expr → Expr → MetaM Meta.AssertAfterResult
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_MVarId_rewrite : MVarId → Expr → Expr → optParam Bool false → optParam Meta.Rewrite.Config { } → MetaM Meta.RewriteResult
-- R-NONE effect=pure extern=False
axiom Lean_Message : Type
-- R-NONE effect=pure extern=False
axiom Lean_MessageData_joinSep : List MessageData → MessageData → MessageData
-- R-NONE effect=pure extern=False
axiom Lean_MessageData_ofExpr : Expr → MessageData
-- R-NONE effect=pure extern=False
axiom Lean_Meta_Ext_extExtension : SimpleScopedEnvExtension Meta.Ext.ExtTheorem Meta.Ext.ExtTheorems
-- R-NONE effect=pure extern=False
axiom Lean_Meta_MetaM : Type → Type
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_MetaM_run : {α : Type} → MetaM α → optParam Meta.Context { } → optParam Meta.State { } → CoreM (α × Meta.State)
-- R-NONE effect=pure extern=False
axiom Lean_Meta_Rfl_reflExt : SimpleScopedEnvExtension (Name × Array Meta.DiscrTree.Key) (Meta.DiscrTree Name)
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_Simp_Context_mkDefault : MetaM Meta.Simp.Context
-- R-NONE effect=pure extern=False
axiom Lean_Meta_Simp_Simproc : Type
-- R-EXTERN effect=toolchain-monad extern=True
axiom Lean_Meta_Simp_dsimp : Expr → Meta.SimpM Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_Simp_getSimprocs : CoreM Meta.Simprocs
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_Simp_mkDefaultMethods : CoreM Meta.Simp.Methods
-- R-NONE effect=pure extern=False
axiom Lean_Meta_Simp_mkDefaultMethodsCore : Meta.Simp.SimprocsArray → Meta.Simp.Methods
-- R-NONE effect=pure extern=False
axiom Lean_Meta_Symm_symmExt : SimpleScopedEnvExtension (Name × Array Meta.DiscrTree.Key) (Meta.DiscrTree Name)
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_Tactic_TryThis_addSuggestion : Syntax → Meta.Tactic.TryThis.Suggestion → optParam (Option Syntax) none → optParam String "Try this:" → optParam (Option String) none → optParam Meta.Hint.DiffGranularity Meta.Hint.DiffGranularity.none → optParam MessageData MessageData.nil → CoreM Unit
-- R-NONE effect=pure extern=False
axiom Lean_Meta_approxDefEq : {n : Type → Type u_1} → [MonadControlT MetaM n] → [Monad n] → {α : Type} → n α → n α
-- R-NONE effect=pure extern=False
axiom Lean_Meta_coeExt : SimpleScopedEnvExtension (Name × Meta.CoeFnInfo) (NameMap Meta.CoeFnInfo)
-- R-UNSAFE effect=toolchain-monad extern=False
axiom Lean_Meta_evalExpr : (α : Type) → Expr → Expr → optParam DefinitionSafety DefinitionSafety.safe → optParam Bool true → MetaM α
-- R-NONE effect=pure extern=False
axiom Lean_Meta_forallTelescope : {n : Type → Type u_1} → [MonadControlT MetaM n] → [Monad n] → {α : Type} → Expr → (Array Expr → Expr → n α) → optParam Bool false → n α
-- R-EXTERN effect=toolchain-monad extern=True
axiom Lean_Meta_inferType : Expr → MetaM Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_isInstance : Name → CoreM Bool
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_isProp : Expr → MetaM Bool
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_mkAdd : Expr → Expr → MetaM Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_mkAuxTheorem : Expr → Expr → optParam Bool false → optParam (Option Name) none → optParam Bool true → MetaM Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_mkHCongrWithArity : Expr → Nat → MetaM Meta.CongrTheorem
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_mkMul : Expr → Expr → MetaM Expr
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_registerCoercion : Name → optParam (Option Meta.CoeFnInfo) none → MetaM Unit
-- R-EFFECT effect=io extern=False
axiom Lean_Meta_registerGetEqnsFn : Meta.GetEqnsFn → IO Unit
-- R-EFFECT effect=toolchain-monad extern=False
axiom Lean_Meta_simpGoal : MVarId → Meta.Simp.Context → optParam Meta.Simp.SimprocsArray #[] → optParam (Option Meta.Simp.Discharge) none → optParam Bool true → optParam (Array FVarId) #[] → optParam Meta.Simp.Stats { } → MetaM (Option (Array FVarId × MVarId) × Meta.Simp.Stats)
-- R-NONE effect=pure extern=False
axiom Lean_Meta_transform : {m : Type → Type} → [inst : Monad m] → [MonadLiftT MetaM m] → [MonadControlT MetaM m] → Expr → (optParam (Expr → m TransformStep) fun x => pure TransformStep.continue) → (optParam (Expr → m TransformStep) fun e => pure (TransformStep.done e)) → optParam Bool false → optParam Bool false → m Expr
-- R-NONE effect=pure extern=False
axiom Lean_Meta_withMCtx : {n : Type → Type u_1} → [MonadControlT MetaM n] → [Monad n] → {α : Type} → MetavarContext → n α → n α
-- R-NONE effect=pure extern=False
axiom Lean_Name_cmp : Name → Name → Ordering
-- R-NONE effect=pure extern=False
axiom Lean_NameMap : Type → Type
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_declId : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_declaration : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_deprecated_module : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_docComment : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_eoi : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_example : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_exit : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_export : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_in : Parser.TrailingParser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_instance : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_macro_rules : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_mixfix : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_moduleDoc : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_notation : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_private : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_registerTryTactic : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Command_set_option : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Module_header : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Module_import : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Module_module : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Conv_conv : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_allGoals : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_anyGoals : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_cases : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_failIfSuccess : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_first : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_focus : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_grindRepeat_ : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_grindSeq : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_grindSeq1Indented : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_grindSeqBracketed : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_instantiate : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_next : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_Grind_skip : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_acRfl : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_allGoals : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_anchor : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_anyGoals : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_apply : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_case : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_cases : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_congr : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_constructor : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_decide : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_discharger : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_done : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_dsimp : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_failIfSuccess : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_first : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_focus : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_grind : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_grindLemma : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_grindParam : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_grindTrace : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_grobner : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_guardHyp : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_guardTarget : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_induction : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_injections : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_intros : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_lia : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_location : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_nativeDecide : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_obtain : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_omega : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_optConfig : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_paren : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_quotSeq : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_rcases : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_rcasesPatMed : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_refine : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_replace : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_rotateLeft : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_rotateRight : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_rwRule : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_rwRuleSeq : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_show : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_simp : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_simpAll : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_simpStar : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_simpa : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_simpaUsingBang : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_skip : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_specialize : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_split : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_subst : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_substVars : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticAdmit : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticHave__ : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticIterate____ : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticLet__ : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticNorm_cast__ : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticRepeat_ : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticRfl : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticSeq : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticSeq1Indented : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticSeqBracketed : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticSorry : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticStop_ : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticSuffices_ : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_tacticTry_ : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_traceMessage : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_traceState : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Tactic_withAnnotateState : ParserDescr
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Term_app : Parser.TrailingParser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Term_attributes : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Term_byTactic : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Term_cdot : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Term_dynamicQuot : Parser.Parser
-- R-NONE effect=pure extern=False
axiom Lean_Parser_Term_matchDiscr : Parser.Parser

end FlnFacade
