//! Real source calculations select kernel-admitted Trans dictionaries.
#![forbid(unsafe_code)]
use fln_core::expr::{BinderInfo, Expr, ExprNode, FVarId};
use fln_core::level::Level;
use fln_core::name::Name;
use fln_core::outcome::Outcome;
use fln_elab::instances::register_class;
use fln_elab::records::{RecordBudget, RecordSpec, record_declarations};
use fln_elab::{LocalContext, LocalDecl, check_definition_source};
use fln_env::environment::{DeclarationBudget, DeclarationCommitted, Environment};
use fln_env::pmap::CollisionBudget;
use fln_kernel::Declaration;
use fln_kernel::capability::{Published, admit};
use fln_kernel::council::{Council, CouncilOutcome, convene};
use fln_kernel::verdict::{Budget, Verdict};

fn n(name: &str) -> Name {
    Name::from_components(name.split('.'))
}
fn budget() -> Budget {
    Budget::for_stack_bytes(2 * 1024 * 1024)
}
fn publish(env: &Environment, declaration: Declaration) -> Environment {
    let description = format!("{declaration:?}");
    let Outcome::Complete(admitted) = admit(env, declaration, budget()) else {
        panic!("fixture admission nonanswer: {description}");
    };
    let CouncilOutcome::Agreed(checked) = convene(&Council::nobody_was_asked(), admitted) else {
        panic!("fixture rejected: {description}");
    };
    match checked.publish(
        DeclarationBudget::default(),
        CollisionBudget::default(),
        None,
    ) {
        Outcome::Complete(Published::Committed(DeclarationCommitted::Published(result))) => {
            result.environment
        }
        Outcome::Complete(Published::BlockCommitted(result)) => result.environment,
        other => panic!("fixture publication: {other:?}"),
    }
}
fn parameter(
    context: &mut LocalContext,
    name: &str,
    type_: Expr,
    style: BinderInfo,
) -> LocalDecl {
    context
        .add_param(FVarId(n(&format!("_calc_fixture.{name}"))), n(name), type_, style)
        .clone()
}
fn variable(local: &LocalDecl) -> Expr {
    Expr::fvar(local.id.clone())
}
fn arrow(domain: Expr, result: Expr) -> Expr {
    Expr::forall_e(Name::anonymous(), domain, result, BinderInfo::Default)
}
fn relation(head: &LocalDecl, left: &LocalDecl, right: &LocalDecl) -> Expr {
    Expr::app(Expr::app(variable(head), variable(left)), variable(right))
}
fn close(locals: &[LocalDecl], mut body: Expr) -> Expr {
    for local in locals.iter().rev() {
        body = body.abstract_fvar(&local.id, 0).unwrap();
        body = Expr::forall_e(
            local.user_name.clone(),
            local.type_.clone(),
            body,
            local.binder_info,
        );
    }
    body
}

// The same class shape as the ordinary Trans interface, generated by the
// production record builder and admitted by K1. No mocked registry or checker.
// Fixed universes let the tests independently exercise Prop- and Type-valued
// relations without requiring an imported Prelude or a Reference executable.
fn environment(type_valued: bool) -> Environment {
    let mut env = Environment::new();
    for declaration in fln_elab::seed::source_seed_declarations() {
        env = publish(&env, declaration);
    }
    if !env.contains(&n("outParam")) {
        env = publish(&env, fln_elab::seed::out_param_seed_declaration());
    }
    let mut context = LocalContext::new();
    let alpha = parameter(&mut context, "alpha", Expr::sort(Level::one()), BinderInfo::Implicit);
    let beta = parameter(&mut context, "beta", Expr::sort(Level::one()), BinderInfo::Implicit);
    let gamma = parameter(&mut context, "gamma", Expr::sort(Level::one()), BinderInfo::Implicit);
    let level = if type_valued { Level::one() } else { Level::zero() };
    let relation_type = |a: &LocalDecl, b: &LocalDecl| {
        arrow(variable(a), arrow(variable(b), Expr::sort(level.clone())))
    };
    let r = parameter(&mut context, "r", relation_type(&alpha, &beta), BinderInfo::Default);
    let s = parameter(&mut context, "s", relation_type(&beta, &gamma), BinderInfo::Default);
    let output = Expr::app(
        Expr::const_(n("outParam"), vec![level.clone().succ().unwrap()]),
        relation_type(&alpha, &gamma),
    );
    let t = parameter(&mut context, "t", output, BinderInfo::Default);
    let a = parameter(&mut context, "a", variable(&alpha), BinderInfo::Implicit);
    let b = parameter(&mut context, "b", variable(&beta), BinderInfo::Implicit);
    let c = parameter(&mut context, "c", variable(&gamma), BinderInfo::Implicit);
    let field_type = arrow(relation(&r, &a, &b), arrow(relation(&s, &b, &c), relation(&t, &a, &c)));
    let field_type = close(&[a, b, c], field_type);
    let field = parameter(&mut context, "trans", field_type, BinderInfo::Default);
    let spec = RecordSpec {
        name: n("Trans"),
        level_params: vec![],
        parameters: vec![alpha, beta, gamma, r, s, t],
        fields: vec![field],
        result_level: Level::one(),
        is_class: true,
    };
    for declaration in record_declarations(&spec, RecordBudget::default()).unwrap() {
        env = publish(&env, declaration);
    }
    register_class(&env, &n("Trans")).unwrap()
}

fn contains_trans(expr: &Expr) -> bool {
    let mut pending = vec![expr];
    while let Some(expr) = pending.pop() {
        match expr.node() {
            ExprNode::Const { name, .. } if name == &n("Trans.trans") => return true,
            ExprNode::App { f, a } => pending.extend([f, a]),
            ExprNode::Lam { binder_type, body, .. }
            | ExprNode::ForallE { binder_type, body, .. } => pending.extend([binder_type, body]),
            ExprNode::LetE { type_, value, body, .. } => pending.extend([type_, value, body]),
            ExprNode::MData { expr, .. } | ExprNode::Proj { expr, .. } => pending.push(expr),
            _ => {}
        }
    }
    false
}
fn accepted(env: &Environment, source: &str) {
    let checked = check_definition_source(source.as_bytes(), env, budget())
        .unwrap_or_else(|error| panic!("{source}\n{error:?}"));
    assert!(
        matches!(checked.outcome, Outcome::Complete(Verdict::Accepted { .. })),
        "{source}\n{:?}", checked.outcome
    );
    let value = match &checked.declaration {
        Declaration::Thm(value) => &value.value,
        Declaration::Defn(value) => &value.value,
        other => panic!("unexpected declaration: {other:?}"),
    };
    assert!(!value.has_expr_mvar());
    assert!(!value.has_level_mvar());
    assert!(!value.has_fvar());
    assert!(!value.has_loose_bvars());
    assert!(contains_trans(value), "the retained proof must use the selected dictionary");
}

#[test]
fn a_local_trans_instance_composes_distinct_relations() {
    accepted(&environment(false),
        "theorem chain (R S T : Nat -> Nat -> Prop) [dict : Trans R S T] (a b c : Nat) (h : R a b) (k : S b c) : T a c := calc\n  R a b := h\n  S _ c := k");
}

#[test]
fn relation_output_is_inferred_without_a_declared_result() {
    accepted(&environment(false),
        "def chain (R S T : Nat -> Nat -> Prop) [dict : Trans R S T] (a b c : Nat) (h : R a b) (k : S b c) := calc\n  R a b := h\n  S _ c := k");
}

#[test]
fn transitivity_supports_three_different_endpoint_types() {
    accepted(&environment(false),
        "theorem chain (R : Nat -> Bool -> Prop) (S : Bool -> String -> Prop) (T : Nat -> String -> Prop) [dict : Trans R S T] (a : Nat) (b : Bool) (c : String) (h : R a b) (k : S b c) : T a c := calc\n  R a b := h\n  S _ c := k");
}

#[test]
fn an_inferred_output_feeds_the_next_trans_instance() {
    accepted(&environment(false),
        "theorem chain (R S T U V : Nat -> Nat -> Prop) [first : Trans R S T] [second : Trans T U V] (a b c d : Nat) (h : R a b) (k : S b c) (l : U c d) : V a d := calc\n  R a b := h\n  S _ c := k\n  U _ d := l");
}

#[test]
fn general_transitivity_interleaves_with_equality_transport() {
    accepted(&environment(false),
        "theorem chain (R S T : Nat -> Nat -> Prop) [dict : Trans R S T] (a b c d : Nat) (h : R a b) (k : S b c) (e : c = d) : T a d := calc\n  R a b := h\n  S _ c := k\n  _ = d := e");
}

#[test]
fn type_valued_relations_use_the_same_typed_operation() {
    accepted(&environment(true),
        "def chain (R S T : Nat -> Nat -> Type) [dict : Trans R S T] (a b c : Nat) (h : R a b) (k : S b c) : T a c := calc\n  R a b := h\n  S _ c := k");
}

#[test]
fn a_missing_or_inapplicable_instance_cannot_invent_transitivity() {
    let env = environment(false);
    for source in [
        "theorem bad (R S T : Nat -> Nat -> Prop) (a b c : Nat) (h : R a b) (k : S b c) : T a c := calc\n  R a b := h\n  S _ c := k",
        "theorem bad (R S T U : Nat -> Nat -> Prop) [dict : Trans R S T] (a b c : Nat) (h : R a b) (k : U b c) : T a c := calc\n  R a b := h\n  U _ c := k",
        "theorem bad (R S T U : Nat -> Nat -> Prop) [dict : Trans R S T] (a b c : Nat) (h : R a b) (k : S b c) : U a c := calc\n  R a b := h\n  S _ c := k",
    ] {
        if let Ok(checked) = check_definition_source(source.as_bytes(), &env, budget()) {
            assert!(!matches!(checked.outcome, Outcome::Complete(Verdict::Accepted { .. })), "{source}");
        }
    }
    // Failed source transactions must not poison the environment or the next query.
    accepted(&env,
        "theorem recovery (R S T : Nat -> Nat -> Prop) [dict : Trans R S T] (a b c : Nat) (h : R a b) (k : S b c) : T a c := calc\n  R a b := h\n  S _ c := k");
}
