#!/usr/bin/env -S python3 -I -S
"""The STANDALONE Mirror facade module (bead `fln-l8f`, G0-8 acceptance b; plan
§4.3, risk R1, OQ-3).

WHY A SECOND EMITTER BESIDE scripts/extract/facade_stubs.py. That one answers
"does the pin re-accept the type it printed for each demanded symbol" — it emits
`axiom Lean_Meta_inferType : ...` inside `namespace FlnFacade` and it opens with
`import Lean`, so the REAL toolchain is linked while the stubs are checked. That is
a real check of the printed types and it is NOT a facade: no mathlib file can be
compiled against it, because every name it declares is mangled and every type it
mentions is served by the very toolchain the facade is supposed to replace.

This emitter produces the other artifact: declarations at their TRUE qualified
names, in one module that has NO `import Lean`, closed under type-level
dependencies so it stands alone against `Init` only. That is the object acceptance
(b) needs — the thing a curated mathlib metaprogram file's toolchain demand can be
checked against with no Reference `Lean.*` in scope at all.

WHAT IT IS NOT, stated here so the artifact is never read as more than it is:

  * An axiom carries a TYPE and no VALUE, so the facade is opaque where the
    Reference is transparent. `Lean.Meta.MetaM` as an axiom does not unfold to its
    reader/state stack, so anything that needs that defeq fails against this
    facade. Those failures are the spike's measurement, not its defect: they are
    exactly the rows a native mirror must implement rather than declare.
  * Constants defined under `Init` are NOT declared: every Lean file that is not
    `prelude` imports `Init` implicitly, so they are the substrate both sides
    share. Everything else in the closure is declared, and closure members outside
    the demanded toolchain-api surface are labelled `substrate` in the manifest
    rather than being silently counted as facade coverage.
  * Universe parameters are emitted from `levelParams`; a polymorphic constant
    whose binders are dropped elaborates as a different declaration.

Outputs: the Lean module, and a manifest NDJSON (fln-facade-module/1) carrying one
row per declaration with its role, partition, census facts and printed signature.
"""

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
from collections import defaultdict

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RESISTANCE = os.path.join(REPO, "contracts", "facade_resistance.ndjson")
ENV_SHARDS = [
    os.path.join(REPO, "contracts", "builtin_environment.tsv"),
    os.path.join(REPO, "contracts", "builtin_environment.001.tsv"),
    os.path.join(REPO, "contracts", "builtin_environment.002.tsv"),
]
SCHEMA = "fln-facade-module/1"
COLS = [
    "key", "display", "kind", "module", "levels", "arity", "telescope",
    "sig_root", "res_root", "res_head", "safety", "attrs", "extern",
    "impl_by", "effect",
]


def unquote(v):
    return v[1:-1] if len(v) >= 2 and v[0] == '"' and v[-1] == '"' else v


def dotted(structural):
    """Decode the census's structural Name encoding into a dotted name.

    `a/s\"Lean\"/s\"Meta\"/s\"Basic\"` -> `Lean.Meta.Basic`. Numeric components
    (`/n3`) are kept as numerals; collapsing them into strings is the f6br defect
    this project has already paid for once.
    """
    parts = []
    for comp in structural.split("/")[1:]:
        if comp.startswith('s\\"') and comp.endswith('\\"'):
            parts.append(comp[3:-2])
        elif comp.startswith('s"') and comp.endswith('"'):
            parts.append(comp[2:-1])
        elif comp.startswith("n"):
            parts.append(comp[1:])
        else:
            return None
    return ".".join(parts) if parts else None


def input_digest(path):
    """Bind a derived artifact to the exact bytes it was derived FROM. Every input
    here is itself generated and is being regenerated by other hands; a summary
    that names its inputs by PATH alone goes stale silently, and the reader cannot
    tell a fresh row from one derived before the input moved."""
    with open(path, "rb") as fh:
        return {"path": os.path.relpath(path, REPO),
                "sha256": hashlib.sha256(fh.read()).hexdigest()}


def pinned_lean():
    with open(os.path.join(REPO, "SUITE.lock"), encoding="utf-8") as fh:
        lock = fh.read()
    tag = None
    for line in lock.splitlines():
        if line.startswith("reference "):
            for field in line.split():
                if field.startswith("tag="):
                    tag = field[4:]
    if not tag:
        raise SystemExit("REFUSE: SUITE.lock has no Reference tag")
    path = os.path.join(
        os.path.expanduser("~"), ".elan", "toolchains",
        f"leanprover--lean4---{tag}", "bin", "lean",
    )
    if not os.path.isfile(path):
        raise SystemExit(f"SKIP: pinned Reference not installed at {path}")
    return path, tag


def load_census():
    """display-name -> census facts, with the shard-completeness refusal.

    Reading one shard of three once manufactured phantom orphans for the
    resistance census; the same trap here would silently declare a closure member
    `Init`-provided (it has no row, so no module) and drop it from the facade.
    """
    facts = {}
    declared = observed = 0
    for shard in ENV_SHARDS:
        if not os.path.isfile(shard):
            raise SystemExit(f"REFUSE: census shard absent: {shard}")
        with open(shard, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                if line.startswith("constant_count\t"):
                    declared = max(declared, int(line.split("\t")[1]))
                if not line.startswith("observed\t"):
                    continue
                observed += 1
                cols = line.rstrip("\n").split("\t")[1:]
                row = {k: unquote(v) for k, v in zip(COLS, cols)}
                facts[row["display"]] = row
    if observed != declared:
        raise SystemExit(
            f"REFUSE: {observed} observed census rows against a declared "
            f"constant_count of {declared} — a partial census would misreport "
            "closure members as Init-provided and drop them from the facade")
    return facts


def demanded_symbols():
    """Toolchain-API symbol rows of the resistance census.

    Tolerates both the pre- and post-totality shapes of fln-facade-resistance/1:
    when a row carries no `partition` field every symbol row is toolchain-api by
    construction (that artifact contained nothing else), and when it does, only
    the toolchain-api rows define the facade surface.
    """
    rows = []
    with open(RESISTANCE, encoding="utf-8") as fh:
        for lineno, line in enumerate(fh, 1):
            try:
                row = json.loads(line)
            except json.JSONDecodeError as exc:
                raise SystemExit(f"REFUSE: {RESISTANCE}:{lineno} is not JSON ({exc})") from exc
            if row.get("kind") != "symbol":
                continue
            if row.get("partition", "toolchain-api") != "toolchain-api":
                continue
            rows.append(row)
    if not rows:
        raise SystemExit(
            "REFUSE: no toolchain-api symbol rows in the resistance census — an "
            "empty facade would compile every probe vacuously")
    return {r["name"]: r for r in rows}


PROBE = r'''import Lean
open Lean in
#eval show CoreM Unit from do
  let txt <- IO.FS.readFile "@NAMES@"
  let names := ((txt.splitOn "\n").filter (fun s => s != "")).map String.toName
  let env <- getEnv
  for n in names do
    match env.find? n with
    | some info =>
      let fmt <- Meta.MetaM.run' (withOptions
        (fun o => o.setBool `pp.fullNames true) (Meta.ppExpr info.type))
      let fmtx <- Meta.MetaM.run' (withOptions
        (fun o => (o.setBool `pp.fullNames true).setBool `pp.explicit true)
        (Meta.ppExpr info.type))
      -- TIER 3, the maximally explicit rendering. `optParam Lean.Meta.Context { }`
      -- is unreadable to a facade: `{ }` is structure-instance notation, so
      -- re-accepting it needs the structure's field DEFAULTS and the instance
      -- synthesis those defaults perform (Inhabited, EmptyCollection) over types
      -- the facade holds opaquely. With pp.structureInstances and pp.notation off,
      -- the same default prints as a fully applied constructor term with every
      -- instance passed EXPLICITLY -- nothing to synthesize, and every constant in
      -- it is already in the type's used-constant set and therefore in the closure.
      let maxOpts : Options -> Options := fun o0 =>
        let o1 := o0.setBool `pp.fullNames true
        let o2 := o1.setBool `pp.explicit true
        let o3 := o2.setBool `pp.structureInstances false
        let o4 := o3.setBool `pp.notation false
        o4.setBool `pp.fieldNotation false
      let fmtm <- Meta.MetaM.run' (withOptions maxOpts (Meta.ppExpr info.type))
      let inst <- Meta.isInstance n
      let lvls := ",".intercalate (info.levelParams.map toString)
      let deps := ",".intercalate ((info.type.getUsedConstants.map toString).toList)
      IO.println s!"TYPE\t{n}\t{lvls}\t{inst}\t{fmt}"
      IO.println s!"TYPEX\t{n}\t{fmtx}"
      IO.println s!"TYPEM\t{n}\t{fmtm}"
      IO.println s!"DEPS\t{n}\t{deps}"
      -- A STRUCTURE is the one shape an `axiom` cannot stand in for: class-hood
      -- and field projections are structural facts, not type facts. Report the
      -- constructor telescope so the emitter can rebuild the declaration itself.
      if let ConstantInfo.inductInfo iv := info then
        if isStructure env n then
          if let some ctor := iv.ctors.head? then
            if let some cinfo := env.find? ctor then
              let cdeps := ",".intercalate ((cinfo.type.getUsedConstants.map toString).toList)
              IO.println s!"STRUCT\t{n}\t{iv.numParams}\t{isClass env n}\t{ctor}"
              -- The PARAMETER binder kinds come from the structure's OWN type, not
              -- from the constructor: Lean makes constructor parameters implicit,
              -- so emitting `class C {m : X}` from the ctor telescope makes `C m`
              -- "Function expected at C" (measured: 76 rows, 45 of them demanded).
              Meta.MetaM.run' <| Meta.forallTelescopeReducing info.type fun ps _ => do
                for i in [0:ps.size] do
                  let pd <- ps[i]!.fvarId!.getDecl
                  let pk := match pd.binderInfo with
                    | BinderInfo.default => "default"
                    | BinderInfo.implicit => "implicit"
                    | BinderInfo.strictImplicit => "strict"
                    | BinderInfo.instImplicit => "inst"
                  IO.println s!"PBINDER\t{n}\t{i}\t{pk}"
              IO.println s!"DEPSC\t{n}\t{cdeps}"
              Meta.MetaM.run' <| Meta.forallTelescopeReducing cinfo.type fun xs _ => do
                for i in [0:xs.size] do
                  let d <- xs[i]!.fvarId!.getDecl
                  let bty <- withOptions (fun o => o.setBool `pp.fullNames true)
                    (Meta.ppExpr d.type)
                  let bk := match d.binderInfo with
                    | BinderInfo.default => "default"
                    | BinderInfo.implicit => "implicit"
                    | BinderInfo.strictImplicit => "strict"
                    | BinderInfo.instImplicit => "inst"
                  IO.println s!"BINDER\t{n}\t{i}\t{bk}\t{d.userName}\t{bty}"
    | none => IO.println s!"MISSING\t{n}"
'''


VALUE_PROBE = r'''import Lean
open Lean in
#eval show CoreM Unit from do
  let txt <- IO.FS.readFile "@NAMES@"
  let names := ((txt.splitOn "\n").filter (fun s => s != "")).map String.toName
  let env <- getEnv
  for n in names do
    match env.find? n with
    | some info =>
      match info.value? with
      | some val =>
        let fmt <- Meta.MetaM.run' (withOptions
          (fun o => o.setBool `pp.fullNames true) (Meta.ppExpr val))
        let deps := ",".intercalate ((val.getUsedConstants.map toString).toList)
        IO.println s!"VALUE\t{n}\t{fmt}"
        IO.println s!"VDEPS\t{n}\t{deps}"
      | none => IO.println s!"NOVALUE\t{n}"
    | none => IO.println s!"NOVALUE\t{n}"
'''


def probe_values(lean, env, work, names):
    """Print the VALUE of each named constant.

    Only reducible constants are asked for. A reducible definition is an
    ABBREVIATION in the Reference — `Lean.LMVarId` is `Lean.LevelMVarId`,
    `Lean.Elab.Term.TermElabM` is its reader/state stack — and the pin therefore
    accepts `BEq LevelMVarId` where `BEq LMVarId` is wanted. Declared as an opaque
    axiom, the two become distinct constants with no defeq between them, and every
    row that depends on the unfolding fails. Emitting these transparently is the
    facade being FAITHFUL, not the facade being lenient.
    """
    if not names:
        return {}, {}
    names_path = os.path.join(work, "vnames.txt")
    with open(names_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(sorted(names)) + "\n")
    src = os.path.join(work, "vprobe.lean")
    with open(src, "w", encoding="utf-8") as fh:
        fh.write(VALUE_PROBE.replace("@NAMES@", names_path))
    proc = subprocess.run([lean, src], capture_output=True, text=True, env=env,
                          timeout=1800)
    if proc.returncode != 0:
        raise SystemExit(f"REFUSE: the pinned binary refused the value probe:\n"
                         f"{(proc.stdout + proc.stderr)[:1200]}")
    values, vdeps = {}, {}
    current = None
    for line in proc.stdout.splitlines():
        if line.startswith("VALUE\t"):
            _, name, val = line.split("\t", 2)
            values[name] = val
            current = (values, name)
        elif line.startswith("VDEPS\t"):
            _, name, dep_csv = line.split("\t", 2)
            vdeps[name] = [d for d in dep_csv.split(",") if d]
            current = None
        elif line.startswith("NOVALUE\t"):
            current = None
        elif current is not None and line.strip():
            d, name = current
            d[name] = d[name] + " " + line.strip()
    return values, vdeps


def probe(lean, env, work, names):
    """Ask the pin for the printed type, universes, instance flag and type-level
    dependencies of each name. Multi-line pp output is rejoined here: the printer
    wraps at its own width, and a probe that pins a width is responsible for an
    option name the pin can move."""
    names_path = os.path.join(work, "names.txt")
    with open(names_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(sorted(names)) + "\n")
    src = os.path.join(work, "probe.lean")
    with open(src, "w", encoding="utf-8") as fh:
        fh.write(PROBE.replace("@NAMES@", names_path))
    proc = subprocess.run([lean, src], capture_output=True, text=True, env=env, timeout=1800)
    if proc.returncode != 0:
        raise SystemExit(f"REFUSE: the pinned binary refused the probe:\n"
                         f"{(proc.stdout + proc.stderr)[:1200]}")
    types, typesx, typesm, levels, insts, deps, missing = {}, {}, {}, {}, {}, {}, []
    structs, binders, pbinders = {}, defaultdict(dict), defaultdict(dict)
    current = None
    for line in proc.stdout.splitlines():
        if line.startswith("TYPE\t"):
            _, name, lvls, inst, ty = line.split("\t", 4)
            types[name], levels[name], insts[name] = ty, lvls, inst == "true"
            current = (types, name)
        elif line.startswith("TYPEX\t"):
            _, name, ty = line.split("\t", 2)
            typesx[name] = ty
            current = (typesx, name)
        elif line.startswith("TYPEM\t"):
            _, name, ty = line.split("\t", 2)
            typesm[name] = ty
            current = (typesm, name)
        elif line.startswith("DEPS\t"):
            _, name, dep_csv = line.split("\t", 2)
            deps[name] = [d for d in dep_csv.split(",") if d]
            current = None
        elif line.startswith("DEPSC\t"):
            _, name, dep_csv = line.split("\t", 2)
            deps[name] = sorted(set(deps.get(name, [])) | {d for d in dep_csv.split(",") if d})
            current = None
        elif line.startswith("STRUCT\t"):
            _, name, nparams, is_class, ctor = line.split("\t", 4)
            structs[name] = {"num_params": int(nparams),
                             "is_class": is_class == "true", "ctor": ctor}
            current = None
        elif line.startswith("PBINDER\t"):
            _, name, idx, kind = line.split("\t", 3)
            pbinders[name][int(idx)] = kind
            current = None
        elif line.startswith("BINDER\t"):
            _, name, idx, kind, user, bty = line.split("\t", 5)
            binders[name][int(idx)] = {"kind": kind, "user": user, "type": bty}
            current = (binders[name][int(idx)], "type")
        elif line.startswith("MISSING\t"):
            missing.append(line.split("\t", 1)[1])
            current = None
        elif current is not None and line.strip():
            d, name = current
            d[name] = d[name] + " " + line.strip()
    return (types, typesx, typesm, levels, insts, deps, missing,
            structs, {k: v for k, v in binders.items()},
            {k: v for k, v in pbinders.items()})


IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_'!?]*$")
TOKEN = re.compile(r"(?<![\w.\u00ab\u00bb])([A-Za-z_][\w'!?]*(?:\.[A-Za-z_][\w'!?]*)*)(?![\w.])")


def root_anchor(ty, deps):
    """Prefix every constant occurrence in a printed type with `_root_.`.

    WHY, and it is a property of a ONE-MODULE facade rather than of any row. A
    declaration named `Lean.Syntax.reprint` resolves names in its own type with
    `Lean.Syntax` and `Lean` open, so the printed `Option String` finds
    `Lean.Option` — a structure — and the pin says "Function expected at Option".
    The Reference never hits this: there, `Lean.Syntax.reprint` is elaborated in a
    module that has not yet imported `Lean.Option`, and module order does the
    disambiguation for free. A facade that declares the whole closure at once has
    no module order to lean on, so every reference is anchored explicitly.

    Only tokens that EXACTLY equal a constant the pin listed for this type are
    rewritten; binder names, universe names and notation are left alone.
    """
    if not deps:
        return ty
    names = set(deps)
    return TOKEN.sub(
        lambda m: ("_root_." + m.group(1)) if m.group(1) in names else m.group(1), ty)


def renderable_name(name):
    """A declaration name the facade can actually declare.

    A numeric component (`Foo.1`, hygiene residue) is not a declarable name; such
    a closure member is quarantined with its reason rather than emitted as a
    line the pin will reject.
    """
    comps = name.split(".")
    if not comps or any(c == "" for c in comps):
        return None
    out = []
    for c in comps:
        if IDENT.match(c):
            out.append(c)
        elif c.isdigit():
            return None
        else:
            out.append("«" + c + "»")
    return ".".join(out)


def close_over_types(lean, env, work, demand, census, max_rounds=24):
    """Fixpoint: a facade that mentions a type it does not declare is not
    standalone. Round after round, every constant appearing in a declared type is
    itself declared, unless `Init` provides it — `import Init` is implicit in every
    non-prelude Lean file, so those constants are the shared substrate."""
    types, typesx, typesm, levels, insts, deps = {}, {}, {}, {}, {}, {}
    structs, binders, pbinders = {}, {}, {}
    known, missing, init_provided = set(), [], set()
    # Names this function INVENTED (a structure's field projection, derived as
    # `C.field`). A derived name the pin does not have is not a missing type: it
    # is a PRIVATE field, whose projection the Reference does not export under
    # that name. Refusing on it would block the facade over the pin's own access
    # control; it is recorded as a divergence instead, because the facade's
    # structural block DOES expose it.
    derived, absent_projections = set(), set()
    frontier = set(demand)
    rounds = 0
    while frontier:
        rounds += 1
        if rounds > max_rounds:
            raise SystemExit(
                f"REFUSE: type closure did not converge in {max_rounds} rounds "
                f"({len(frontier)} names still unresolved) — an unconverged "
                "closure emits a facade that silently depends on the Reference")
        t, tx, tm, lv, ins, dp, ms, st, bd, pb = probe(lean, env, work, frontier)
        types.update(t); typesx.update(tx); typesm.update(tm); levels.update(lv)
        insts.update(ins); deps.update(dp)
        structs.update(st); binders.update(bd); pbinders.update(pb)
        for m in ms:
            if m in derived:
                absent_projections.add(m)
            else:
                missing.append(m)
        known |= set(frontier)
        nxt = set()
        for name in frontier:
            st = structs.get(name)
            if st:
                for i, b in sorted(binders.get(name, {}).items()):
                    if i >= st["num_params"]:
                        proj = f"{name}.{b['user']}"
                        if proj not in known and proj not in absent_projections:
                            nxt.add(proj)
                            derived.add(proj)
                if st["ctor"] not in known and st["ctor"] not in absent_projections:
                    nxt.add(st["ctor"])
                    derived.add(st["ctor"])
            for dep in deps.get(name, ()):
                if dep in known or dep in nxt:
                    continue
                row = census.get(dep)
                mod = dotted(row["module"]) if row and row.get("module") else None
                if mod is not None and (mod == "Init" or mod.startswith("Init.")):
                    init_provided.add(dep)
                    continue
                nxt.add(dep)
        frontier = nxt
    return (types, typesx, typesm, levels, insts, deps, missing, init_provided,
            rounds, structs, binders, absent_projections, pbinders)


def order(names, deps):
    """Wave-based Kahn with a declared tie-break (name), so the emitted order is
    deterministic. A cycle is disclosed as residue and appended in name order —
    never silently linearized into a false ordering claim."""
    pending = set(names)
    edges = {n: {d for d in deps.get(n, ()) if d in pending and d != n} for n in pending}
    ordered, residue = [], []
    while pending:
        wave = sorted(n for n in pending if not (edges[n] - set(ordered)))
        if not wave:
            residue = sorted(pending)
            ordered.extend(residue)
            break
        ordered.extend(wave)
        pending -= set(wave)
    return ordered, residue


HEADER = [
    "-- GENERATED by scripts/extract/facade_module.py from the pinned Reference",
    "-- ({tag}) — the STANDALONE Mirror facade for the demanded toolchain surface",
    "-- (bead fln-l8f, G0-8 acceptance b). DO NOT EDIT.",
    "--",
    "-- There is deliberately NO `import Lean` here. A facade that imports the",
    "-- Reference is checked against the very toolchain it stands in for, and every",
    "-- name it appears to serve is really served by the import. This module names",
    "-- its declarations exactly as the Reference does and closes over its own",
    "-- type-level dependencies, so a probe compiled against it alone is compiled",
    "-- against no Reference `Lean.*` at all.",
    "--",
    "-- `Init` is the shared substrate: every non-prelude Lean file imports it",
    "-- implicitly, so Init-defined constants are not redeclared here. Closure",
    "-- members outside the demanded toolchain-api surface are marked role=substrate",
    "-- in contracts/facade_module.ndjson and are not counted as facade coverage.",
    "--",
    "-- Each declaration is an `axiom`: a TYPE with no VALUE. The facade is",
    "-- therefore opaque exactly where the Reference is transparent, and anything",
    "-- that needs a definitional unfolding fails against it. Those failures are",
    "-- this spike's measurement of what a native mirror must implement rather",
    "-- than declare — see contracts/facade_compile.ndjson.",
    "set_option autoImplicit false",
    "set_option maxRecDepth 8000",
    "",
]


def binder_text(b, deps):
    """Render one constructor binder. An INACCESSIBLE name (`inst✝`) cannot be
    written back as source, and a field type that mentions one cannot either — the
    caller refuses structural emission for that structure rather than emitting a
    line the pin will reject."""
    name, ty, kind = b["user"], root_anchor(b["type"], deps), b["kind"]
    if kind == "inst":
        return f"[{ty}]" if "✝" in name else f"[{name} : {ty}]"
    open_, close = {"default": ("(", ")"), "implicit": ("{", "}"),
                    "strict": ("\u2983", "\u2984")}[kind]
    return f"{open_}{name} : {ty}{close}"


def structural_block(name, d, st, bs, deps, pks):
    """A `class`/`structure` declaration rebuilt from the pin's own constructor
    telescope. This is the ONE thing an axiom facade cannot do: class-hood and
    field projections are structural facts, so an opaque `axiom Lean.MonadEnv`
    makes `[self : Lean.MonadEnv m]` an invalid binder annotation and takes every
    projection down with it (measured: 29 rows plus 20 instance registrations)."""
    keyword = "class" if st["is_class"] else "structure"
    binder = "" if not d["levels"] else ".{" + d["levels"].replace(",", ", ") + "}"
    params, fields = [], []
    for i, b in sorted(bs.items()):
        if i < st["num_params"]:
            params.append(dict(b, kind=pks.get(i, "default")))
        else:
            fields.append(b)
    if not fields:
        return None
    head = f"{keyword} {d['decl_name']}{binder}" + (
        (" " + " ".join(binder_text(b, deps) for b in params)) if params else "") + " where"
    lines = [head]
    for b in fields:
        fname = renderable_name(b["user"])
        if fname is None:
            return None
        lines.append(f"  {fname} : {root_anchor(b['type'], deps)}")
    return lines


def structural_refusal(name, st, bs):
    """Why a structure may not be emitted structurally, decided BEFORE the pin is
    asked, so the reason is a fact rather than a diagnostic."""
    if not bs:
        return "no constructor telescope was probed"
    if all(i < st["num_params"] for i in bs):
        return "constructor has parameters only, no fields"
    for i, b in sorted(bs.items()):
        if "\u271d" in b["type"]:
            return "a binder type mentions an inaccessible name"
        if "\u271d" in b["user"] and b["kind"] != "inst":
            return "a non-instance binder is inaccessible"
    return None


def render(tag, ordered, decl, explicit_for, maxexp_for, quarantine, dropped_attrs,
           structural, structs, binders, deps, pbinders, transparent):
    body = [line.replace("{tag}", tag) for line in HEADER]
    line_map = {}
    emitted = []
    # Everything a structural declaration generates for itself: re-declaring a
    # projection the `class` block already produces is a redeclaration error.
    provided = {}
    for c in structural:
        st = structs[c]
        provided[st["ctor"]] = c
        for i, b in sorted(binders.get(c, {}).items()):
            if i >= st["num_params"]:
                provided[f"{c}.{b['user']}"] = c
    for name in ordered:
        if name in quarantine or name in provided:
            continue
        if name in structural:
            block = structural_block(name, decl[name], structs[name],
                                     binders.get(name, {}), deps.get(name, ()),
                                     pbinders.get(name, {}))
            d = decl[name]
            body.append(f"-- role={d['role']} bucket={d['bucket']} "
                        f"structural={'class' if structs[name]['is_class'] else 'structure'} "
                        f"module={d['module']}")
            for line in block:
                body.append(line)
                line_map[len(body)] = ("struct", name)
            emitted.append(name)
            continue
        d = decl[name]
        ty = (d["typem"] if name in maxexp_for
              else d["typex"] if name in explicit_for else d["type"])
        if ty is None:
            continue
        ty = root_anchor(ty, deps.get(name, ()))
        if name in transparent:
            binder = "" if not d["levels"] else ".{" + d["levels"].replace(",", ", ") + "}"
            body.append(f"-- role={d['role']} bucket={d['bucket']} transparent "
                        f"module={d['module']}")
            body.append(f"@[reducible] noncomputable def {d['decl_name']}{binder} : "
                        f"{ty} := {root_anchor(d['value'], deps.get(name, ()))}")
            line_map[len(body)] = ("transparent", name)
            emitted.append(name)
            continue
        body.append(f"-- role={d['role']} bucket={d['bucket']} effect={d['effect']} "
                    f"module={d['module']}" + (" pp=explicit" if name in explicit_for else ""))
        binder = "" if not d["levels"] else ".{" + d["levels"].replace(",", ", ") + "}"
        body.append(f"axiom {d['decl_name']}{binder} : {ty}")
        line_map[len(body)] = ("axiom", name)
        emitted.append(name)
    body.append("")
    attrs = 0
    for name in ordered:
        d = decl[name]
        if name in quarantine or not d["instance"] or name in dropped_attrs:
            continue
        if name in structural:
            continue
        body.append(f"attribute [instance] {d['decl_name']}")
        line_map[len(body)] = ("attr", name)
        attrs += 1
    # A parent projection of an `extends` class is an instance in the pin; the
    # structural block generates the projection but not its registration.
    for proj, owner in sorted(provided.items()):
        if proj in decl and decl[proj]["instance"] and proj not in dropped_attrs:
            body.append(f"attribute [instance] {decl[proj]['decl_name']}")
            line_map[len(body)] = ("attr", proj)
            attrs += 1
    for name in sorted(quarantine):
        body.append(f"-- QUARANTINED {name}: {quarantine[name]}")
    return "\n".join(body) + "\n", line_map, emitted, attrs, provided


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="the generated Lean facade module")
    ap.add_argument("--manifest", required=True, help="fln-facade-module/1 NDJSON")
    ap.add_argument("--max-attempts", type=int, default=14)
    ap.add_argument("--transparency-rounds", type=int, default=4,
                    help="fixpoint rounds for reducible-alias transparency; a transparent value can name further abbreviations")
    ap.add_argument("--readmit-rounds", type=int, default=4,
                    help="how many times to clear the quarantine and let "
                         "the repair loop re-derive it against the facade "
                         "as it then stands")
    args = ap.parse_args()

    lean, tag = pinned_lean()
    census = load_census()
    demand = demanded_symbols()
    work = os.path.join(os.environ.get("TMPDIR", "/tmp"), f"fln-l8f-facade-{os.getpid()}")
    os.makedirs(work, exist_ok=True)
    env = {k: v for k, v in os.environ.items() if k not in ("LEAN_PATH", "LEAN_SYSROOT")}
    env["LC_ALL"] = "C"

    # The Init test applies to the DEMAND too, not only to the closure. A
    # demanded symbol whose census module sits under Init is served by the shared
    # prelude: `axiom Array.push` is not a facade row, it is a redeclaration error
    # (measured: 163 of 560 demanded rows are Init-defined).
    init_demanded = set()
    for name in list(demand):
        row = census.get(name)
        mod = dotted(row["module"]) if row and row.get("module") else None
        if mod is not None and (mod == "Init" or mod.startswith("Init.")):
            init_demanded.add(name)
    facade_demand = set(demand) - init_demanded
    if not facade_demand:
        raise SystemExit("REFUSE: every demanded symbol is Init-provided — there "
                         "would be no facade left to emit")
    (types, typesx, typesm, levels, insts, deps, missing, init_provided,
     rounds, structs, binders, absent_projections,
     pbinders) = close_over_types(lean, env, work, facade_demand, census)
    if missing:
        raise SystemExit(
            "REFUSE: the pinned environment has no type for "
            f"{sorted(set(missing))[:8]} — no partial facade is emitted")

    # THE TRANSPARENT SET. A reducible constant is an ABBREVIATION in the
    # Reference; declaring it opaquely invents a distinction the pin does not have
    # (`Lean.LMVarId` vs `Lean.LevelMVarId`, `Lean.PHashMap` vs
    # `Lean.PersistentHashMap`), and every row that needs the unfolding then fails.
    #
    # This is a FIXPOINT, not a pass: a transparent value names constants the type
    # closure never saw, those get declared, and some of THEM are abbreviations
    # too. Computing the reducible set once misses exactly the second layer —
    # measured on Lean.Meta.simpGoal, which failed on PHashMap after LMVarId was
    # already fixed.
    def is_reducible(n):
        return ("ReducibilityStatus.reducible"
                in ((census.get(n) or {}).get("attrs") or ""))

    values, vdeps, reducible = {}, {}, set()
    value_residue = set()
    for vround in range(args.transparency_rounds):
        cand = sorted(n for n in types
                      if n not in reducible and n not in structs and is_reducible(n))
        if not cand:
            break
        reducible |= set(cand)
        v, vd = probe_values(lean, env, work, cand)
        values.update(v)
        vdeps.update(vd)
        extra = set()
        for n, ds in vd.items():
            for d in ds:
                if d in types or d in init_provided:
                    continue
                row = census.get(d)
                mod = dotted(row["module"]) if row and row.get("module") else None
                if mod is not None and (mod == "Init" or mod.startswith("Init.")):
                    init_provided.add(d)
                    continue
                extra.add(d)
        if not extra:
            break
        (t2, tx2, tm2, lv2, in2, dp2, ms2, ip2, r2, st2, bd2, ap2,
         pb2) = close_over_types(lean, env, work, extra, census)
        value_residue |= set(ms2)
        types.update(t2); typesx.update(tx2); typesm.update(tm2)
        levels.update(lv2); insts.update(in2); deps.update(dp2)
        structs.update(st2); binders.update(bd2); pbinders.update(pb2)
        init_provided |= ip2; absent_projections |= ap2
        rounds += r2

    decl, quarantine = {}, {}
    for name in sorted(types):
        row = census.get(name)
        module = dotted(row["module"]) if row and row.get("module") else None
        dn = renderable_name(name)
        if dn is None:
            quarantine[name] = "name has a component the facade cannot declare"
        decl[name] = {
            "decl_name": dn or name,
            "type": types[name],
            "typex": typesx.get(name),
            "typem": typesm.get(name),
            "value": values.get(name),
            "levels": levels.get(name, ""),
            "instance": insts.get(name, False),
            "role": "demanded" if name in demand else (
                "substrate" if row is not None else "uncensused-closure"),
            "bucket": demand[name]["bucket"] if name in demand else "-",
            "effect": (row or {}).get("effect", "-"),
            "safety": (row or {}).get("safety", "-"),
            "module": module or "-",
            "census": row is not None,
        }

    # Which structures the facade will try to declare AS structures. A refusal
    # here is a fact decided before the pin is asked; a refusal later is the pin's
    # own verdict, and both are recorded per row.
    structural, structural_refused, transparent_refused = set(), {}, {}
    for name, st in structs.items():
        if name not in decl:
            continue
        reason = structural_refusal(name, st, binders.get(name, {}))
        if reason:
            structural_refused[name] = reason
        else:
            structural.add(name)

    transparent = {n for n in reducible if values.get(n) and n in decl}
    transparent_full = set(transparent)
    for n in transparent:
        # A transparent row must be ordered after the constants its VALUE names,
        # not only after the ones its type names.
        deps[n] = sorted(set(deps.get(n, [])) | set(vdeps.get(n, [])))
    structural_full = set(structural)
    ordered, cycle_residue = order(list(types), deps)
    explicit_for, maxexp_for, dropped_attrs, attr_reason = set(), set(), set(), {}
    text = line_map = emitted = None
    attempts = []
    # QUARANTINE IS NOT MONOTONE. A row can fail an early attempt only because a
    # dependency was still broken at that moment, and the old loop never looked at
    # it again — measured: 8 of 16 quarantined rows elaborate cleanly against the
    # FINISHED facade. Each re-admission round clears the quarantine and lets the
    # repair loop re-derive it against the facade as it now stands; a row that
    # still fails is re-quarantined with its current reason, so this can only add.
    best = None
    for readmit in range(args.readmit_rounds):
        if readmit:
            if not quarantine and not transparent_refused and not any(
                    v.startswith("pin rejected") for v in structural_refused.values()):
                break
            quarantine = {n: r for n, r in quarantine.items()
                          if decl[n]["type"] is None}
            # The stronger FORMS are re-promoted too, for the same reason the
            # quarantine is cleared: `Lean.PHashMap` was demoted to an axiom
            # because `Lean.PersistentHashMap` was quarantined at that moment, and
            # nothing ever looked again once the cause was repaired.
            transparent = set(transparent_full)
            transparent_refused = {}
            structural = set(structural_full)
            structural_refused = {k: v for k, v in structural_refused.items()
                                  if not v.startswith("pin rejected")}
            dropped_attrs = set()
            attr_reason = {}
        for attempt in range(1, args.max_attempts + 1):
            text, line_map, emitted, attr_count, provided = render(
                tag, ordered, decl, explicit_for, maxexp_for, quarantine, dropped_attrs,
                structural, structs, binders, deps, pbinders, transparent)
            candidate = args.out + ".candidate.lean"
            with open(candidate, "w", encoding="utf-8") as fh:
                fh.write(text)
            proc = subprocess.run([lean, "-DmaxErrors=4000", candidate],
                                  capture_output=True, text=True, env=env, timeout=1800)
            out = proc.stdout + proc.stderr
            errors = len(re.findall(r"\.candidate\.lean:\d+:\d+: error", out))
            attempts.append({"attempt": attempt, "emitted": len(emitted),
                             "attributes": attr_count, "errors": errors,
                             "structural": len(structural),
                             "quarantined": len(quarantine)})
            if proc.returncode == 0:
                os.replace(candidate, args.out)
                break
            (blamed_axioms, blamed_attrs, blamed_structs, blamed_transparent,
             blame_msg) = set(), set(), set(), set(), {}
            for m in re.finditer(r"\.candidate\.lean:(\d+):\d+: error(?:\(([^)]*)\))?: (.*)", out):
                hit = line_map.get(int(m.group(1)))
                if hit is None:
                    continue
                {"attr": blamed_attrs, "struct": blamed_structs,
                 "transparent": blamed_transparent}.get(
                    hit[0], blamed_axioms).add(hit[1])
                blame_msg[hit[1]] = ((m.group(2) or "-") + ": " + m.group(3))[:220]
            # ONLY fall back to bare locations when no `error:` line named a
            # declaration. A bare-location match also hits `Note:` lines and the
            # secondary locations of OTHER errors, which quarantines rows that were
            # never the cause — measured: rows blamed this way elaborate cleanly
            # against the finished facade with an empty reason string.
            if not (blamed_axioms or blamed_attrs or blamed_structs):
                for m in re.finditer(r"\.candidate\.lean:(\d+):", out):
                    hit = line_map.get(int(m.group(1)))
                    if hit is not None:
                        {"attr": blamed_attrs, "struct": blamed_structs,
                         "transparent": blamed_transparent}.get(
                            hit[0], blamed_axioms).add(hit[1])
            if not (blamed_axioms or blamed_attrs or blamed_structs
                    or blamed_transparent):
                raise SystemExit(
                    f"REFUSE: elaboration failed but no error line maps to a "
                    f"declaration (candidate kept at {candidate}):\n{out[:1500]}")
            progressed = False
            for name in blamed_transparent:
                if name in transparent:
                    transparent.discard(name)
                    transparent_refused[name] = ("pin rejected the transparent form "
                                                 "-- " + blame_msg.get(name, "-"))
                    progressed = True
            # A structural block the pin rejects DEMOTES to the axiom form rather than
            # taking the row out of the facade: coverage must never fall because the
            # stronger emission was attempted.
            for name in blamed_structs:
                if name in structural:
                    structural.discard(name)
                    structural_refused[name] = ("pin rejected the structural block -- "
                                                + blame_msg.get(name, "-"))
                    progressed = True
            # An instance registration the facade cannot reproduce is a FINDING: the
            # class itself is an opaque axiom here, so `attribute [instance]` has no
            # class to attach to. Drop it and record it; never silently keep a green.
            for name in blamed_attrs - dropped_attrs:
                dropped_attrs.add(name)
                attr_reason[name] = blame_msg.get(name, "-")
                progressed = True
            # A type that does not round-trip readably gets the explicit printer once;
            # if it still fails it is quarantined with its reason, and the anti-vacuity
            # floor below stops a facade from quarantining its way to green.
            for name in blamed_axioms:
                # `X has already been declared` is not a broken stub: it is the
                # implicitly imported Init substrate ALREADY serving that symbol. The
                # facade must not redeclare it, and counting it as a failed stub would
                # understate coverage by exactly the size of the prelude.
                if "already been declared" in blame_msg.get(name, ""):
                    if name not in quarantine:
                        quarantine[name] = "provided by the implicitly imported Init substrate"
                        decl[name]["role"] = "init-substrate"
                        progressed = True
                    continue
                if name not in explicit_for and decl[name]["typex"]:
                    explicit_for.add(name)
                    progressed = True
                elif name not in maxexp_for and decl[name].get("typem"):
                    # Tier 3 before quarantine: a row whose default value the readable
                    # printers render as notation is not an unrenderable row, it is a
                    # row printed in a dialect the facade cannot re-elaborate.
                    maxexp_for.add(name)
                    progressed = True
                elif name not in quarantine:
                    # Carry the pin's OWN message. "not re-acceptable" is a summary of
                    # nothing; the message is what tells a reader that the row failed
                    # because a class became an opaque axiom rather than because a
                    # printer wrapped a line.
                    quarantine[name] = ("pin rejects the printed type -- "
                                        + blame_msg.get(name, "-"))
                    progressed = True
            if not progressed:
                raise SystemExit(
                    f"REFUSE: no repair left for {sorted(blamed_axioms | blamed_attrs)[:8]} "
                    f"(candidate kept at {candidate})")
        else:
            raise SystemExit(
                f"REFUSE: the facade did not converge in {args.max_attempts} attempts")
        if best is None or len(emitted) > best[0]:
            best = (len(emitted), text, line_map, list(emitted), attr_count,
                    provided, dict(quarantine), set(explicit_for), set(maxexp_for),
                    set(dropped_attrs))
    if best is None:
        raise SystemExit("REFUSE: no facade candidate survived")
    (_, text, line_map, emitted, attr_count, provided, quarantine, explicit_for,
     maxexp_for, dropped_attrs) = best
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(text)

    # A projection the structural block generates IS in the facade; counting only
    # the lines this emitter wrote would understate coverage by every field.
    emitted = emitted + [p for p in sorted(provided) if p in decl]
    covered = [n for n in emitted if decl[n]["role"] == "demanded"]
    if len(covered) < 0.5 * len(facade_demand):
        raise SystemExit(
            f"REFUSE: only {len(covered)} of {len(facade_demand)} demanded symbols survive "
            "in the facade — a facade that quarantines its way to a green is not a "
            "facade, and this artifact will not land")

    rows = [{
        "schema": SCHEMA, "kind": "summary", "pin": tag,
        "claim_class": "bounded_model",
        "inputs": [input_digest(RESISTANCE)] + [input_digest(s) for s in ENV_SHARDS],
        "demanded": len(demand), "demanded_emitted": len(covered),
        "demanded_init_substrate": len(init_demanded),
        "facade_demand": len(facade_demand),
        "closure_rounds": rounds, "declarations_emitted": len(emitted),
        "substrate_emitted": sum(1 for n in emitted if decl[n]["role"] == "substrate"),
        "uncensused_emitted": sum(1 for n in emitted if decl[n]["role"] == "uncensused-closure"),
        "init_provided": len(init_provided),
        "transparent_declarations": len(transparent),
        "reducible_candidates": len(reducible),
        "value_residue": len(value_residue),
        "structural_declarations": len(structural),
        "private_fields_exposed": sum(
            1 for c in structural
            for i, b in binders.get(c, {}).items()
            if i >= structs[c]["num_params"] and f"{c}.{b['user']}" in absent_projections),
        "private_fields_note": "the Reference does not export a projection for these "
            "fields; the facade's structural block does, which is a PERMISSIVE "
            "divergence — a probe can resolve a name the Reference would refuse",
        "structural_class": sum(1 for n in structural if structs[n]["is_class"]),
        "structural_refused": len(structural_refused),
        "class_provided_projections": len(provided),
        "instance_attrs_kept": sum(1 for n in emitted
                                   if decl[n]["instance"] and n not in dropped_attrs),
        "instance_attrs_dropped": len(dropped_attrs),
        "explicit_printer": len(explicit_for),
        "maxexplicit_printer": len(maxexp_for),
        "quarantined": len(quarantine),
        "cycle_residue": len(cycle_residue),
        "attempts": attempts,
        "imports_reference": False,
        "bound": "an axiom facade declares types and no values: it is opaque where "
                 "the Reference is transparent, and elaboration against it proves "
                 "name/type availability, never semantic parity",
    }]
    for name in ordered:
        d = decl[name]
        rows.append({
            "schema": SCHEMA, "kind": "decl", "name": name, "role": d["role"],
            "bucket": d["bucket"], "effect": d["effect"], "safety": d["safety"],
            "module": d["module"], "level_params": d["levels"].split(",") if d["levels"] else [],
            "instance": d["instance"],
            "instance_registered": bool(d["instance"]) and name not in dropped_attrs,
            "instance_drop_reason": attr_reason.get(name),
            "form": ("transparent-abbrev" if name in transparent
                     else "class" if name in structural and structs[name]["is_class"]
                     else "structure" if name in structural
                     else "class-projection" if name in provided else "axiom"),
            "provided_by": provided.get(name),
            "structural_refused_reason": structural_refused.get(name),
            "transparent_refused_reason": transparent_refused.get(name),
            "emitted": name not in quarantine,
            "quarantine_reason": quarantine.get(name),
            "printer": ("pp.maxexplicit" if name in maxexp_for
                        else "pp.explicit" if name in explicit_for else "pp.fullNames"),
            "signature": (d["typem"] if name in maxexp_for
                          else d["typex"] if name in explicit_for else d["type"]),
            "type_deps": sorted(deps.get(name, ())),
        })
    for name in sorted(init_demanded):
        rows.append({"schema": SCHEMA, "kind": "decl", "name": name,
                     "role": "init-substrate", "emitted": False,
                     "bucket": demand[name]["bucket"],
                     "module": (dotted(census[name]["module"])
                                if name in census and census[name].get("module") else "-"),
                     "quarantine_reason": "demanded, and defined under Init: the "
                     "shared prelude already provides it, so the facade must not "
                     "redeclare it"})
    for name in sorted(init_provided):
        rows.append({"schema": SCHEMA, "kind": "init-substrate", "name": name,
                     "reason": "defined under Init; implicitly imported by every "
                               "non-prelude module, so both sides share it"})
    tmp = args.manifest + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        for row in rows:
            fh.write(json.dumps(row, sort_keys=True) + "\n")
    os.replace(tmp, args.manifest)
    print(f"facade-module: demanded={len(demand)} init_substrate={len(init_demanded)} "
          f"facade_demand={len(facade_demand)} emitted={len(emitted)} "
          f"covered={len(covered)} substrate={rows[0]['substrate_emitted']} "
          f"init={len(init_provided)} attrs_kept={rows[0]['instance_attrs_kept']} "
          f"attrs_dropped={len(dropped_attrs)} quarantined={len(quarantine)} "
          f"structural={len(structural)} projections={len(provided)} "
          f"maxexp={len(maxexp_for)} transparent={len(transparent)} "
          f"rounds={rounds} attempts={len(attempts)}", file=sys.stderr)


if __name__ == "__main__":
    main()
