#!/usr/bin/env -S python3 -I -S
"""Generate Mirror facade stubs for the demanded toolchain surface (bead `fln-l8f`,
G0-8 acceptance b; plan §4.3).

WHY THIS EXISTS AS A SECOND EXTRACTOR: the builtin census answers "did this type
change" and stores type DIGESTS (68,181 mix256 roots) — a perfect integrity witness
and a useless generator input, because `axiom X : mix256:5372…` is not Lean. Stub
generation needs the type ITSELF, so this extractor asks the pinned Reference for it
through the oracle-only census route (D5/D9): the binary pretty-prints each demanded
symbol's type from its own environment, and the stubs are emitted from that.

Bounded by construction: the input is the DEMANDED surface (the resistance census's
symbol rows), not the whole 204,543-constant environment — which is very likely why
the original census chose digests.

Output: a Lean source file of `axiom` declarations, one per demanded symbol, with the
bucket and effect recorded as comments so the facade's L-level ratchet is readable in
the artifact it generates.
"""

import argparse
import json
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RESISTANCE = os.path.join(REPO, "contracts", "facade_resistance.ndjson")


def pinned_lean():
    lock = open(os.path.join(REPO, "SUITE.lock"), encoding="utf-8").read()
    tag = None
    for line in lock.splitlines():
        if line.startswith("reference "):
            for field in line.split():
                if field.startswith("tag="):
                    tag = field[4:]
    if not tag:
        raise SystemExit("REFUSE: SUITE.lock has no Reference tag")
    path = os.path.join(
        os.path.expanduser("~"), ".elan", "toolchains",
        f"leanprover--lean4---{tag}", "bin", "lean",
    )
    if not os.path.isfile(path):
        raise SystemExit(f"SKIP: pinned Reference not installed at {path}")
    return path, tag


def demanded_symbols():
    rows = []
    with open(RESISTANCE, encoding="utf-8") as fh:
        for line in fh:
            row = json.loads(line)
            if row.get("kind") == "symbol":
                rows.append(row)
    if not rows:
        raise SystemExit("REFUSE: no symbol rows in the resistance census — an empty "
                         "stub set would read as a facade with nothing to serve")
    return sorted(rows, key=lambda r: r["name"])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    lean, tag = pinned_lean()
    rows = demanded_symbols()
    names = "\n".join(f"    `{r['name']},"  for r in rows)
    program = (
        "import Lean\n"
        "open Lean in\n"
        "#eval show CoreM Unit from do\n"
        "  let env <- getEnv\n"
        "  let names : Array Name := #[\n" + names + "\n  ]\n"
        "  for n in names do\n"
        "    match env.find? n with\n"
        "    | some info =>\n"
        "      let fmt <- Meta.MetaM.run' (Meta.ppExpr info.type)\n"
        "      IO.println s!\"TYPE\\t{n}\\t{fmt}\"\n"
        "    | none => IO.println s!\"MISSING\\t{n}\"\n"
    )
    work = os.path.join(os.environ.get("TMPDIR", "/tmp"), f"fln-l8f-stubs-{os.getpid()}")
    os.makedirs(work, exist_ok=True)
    src = os.path.join(work, "probe.lean")
    with open(src, "w", encoding="utf-8") as fh:
        fh.write(program)
    env = {k: v for k, v in os.environ.items() if k not in ("LEAN_PATH", "LEAN_SYSROOT")}
    env["LC_ALL"] = "C"
    proc = subprocess.run([lean, src], capture_output=True, text=True, env=env, timeout=900)
    if proc.returncode != 0:
        raise SystemExit(f"REFUSE: the pinned binary refused the probe:\n{proc.stderr[:800]}")

    # The pretty-printer WRAPS at its default width, so a long type arrives as a
    # TYPE line plus continuation lines (measured: 6 stubs that did not parse
    # when emitted verbatim). Continuations are exactly the lines that open
    # neither marker, and joining them here is robust to any pp width — more so
    # than setting a format option the probe would have to keep matching.
    types, missing = {}, []
    current = None
    for line in proc.stdout.splitlines():
        if line.startswith("TYPE\t"):
            _, name, ty = line.split("\t", 2)
            types[name] = ty
            current = name
        elif line.startswith("MISSING\t"):
            missing.append(line.split("\t", 1)[1])
            current = None
        elif current is not None and line.strip():
            types[current] = types[current] + " " + line.strip()

    out = [
        "-- GENERATED by scripts/extract/facade_stubs.py from the pinned Reference",
        f"-- ({tag}) — Mirror facade stubs for the demanded toolchain surface",
        "-- (bead fln-l8f, G0-8 acceptance b). DO NOT EDIT.",
        "--",
        "-- Each stub is an `axiom`: a facade DECLARES the symbol's type and leaves",
        "-- the implementation to the native mirror. The bucket comment carries the",
        "-- resistance class from contracts/facade_resistance.ndjson, so the L-level",
        "-- ratchet is readable in the generated artifact rather than only beside it.",
        "namespace FlnFacade",
        "",
    ]
    emitted = 0
    for row in rows:
        name = row["name"]
        ty = types.get(name)
        if ty is None:
            continue
        out.append(f"-- {row['bucket']} effect={row.get('effect')} extern={row.get('extern')}")
        out.append(f"axiom {name.replace('.', '_')} : {ty}")
        emitted += 1
    out.append("")
    out.append("end FlnFacade")
    for name in missing:
        out.append(f"-- MISSING FROM THE PINNED ENVIRONMENT: {name}")
    text = "\n".join(out) + "\n"
    tmp = args.out + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(text)
    os.replace(tmp, args.out)
    print(
        f"facade-stubs: demanded={len(rows)} typed={emitted} missing={len(missing)} "
        f"pin={tag}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
