#!/usr/bin/env bash
# gen_seed_protected.sh — the pin's `protected` status for every constant of
# FrankenLean's source seed (bead fln-8xz8; Rule D5/D8-2: derived, never remembered).
#
# Headerless files are checked against FrankenLean's own source seed, not an imported
# closure, so the seed must carry the pin's protected marks itself: `open Nat` must not
# make the protected `Nat.add` available as `add`. This script derives those marks:
#   1. the seed's constant names, from the seed itself (fln's lib test
#      source_seed_names::seed_constant_names_are_unique_and_dumpable, FLN_SEED_NAMES_OUT set);
#   2. each name's status at the pin, `import Init`, from the pinned Reference binary
#      (located via elan, its commit verified against SUITE.lock).
# The output is deterministic (sorted names, no timestamps or paths), so two runs are
# byte-identical.
#
# Output: crates/fln-elab/src/seed/protected.tsv
#
# Usage: scripts/extract/gen_seed_protected.sh [--check]
#   --check  regenerate to a scratch file and diff against the checked-in table
#            (drift mode; exit 1 on drift, 2 on setup failure)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
GENERATOR="$ROOT/scripts/extract/gen_seed_protected.lean"
TABLE="$ROOT/crates/fln-elab/src/seed/protected.tsv"
MODE="generate"
if [ "${1:-}" = "--check" ]; then
  MODE="check"
fi

note() { echo "[gen_seed_protected] $*" >&2; }

# ---- locate and verify the pinned Reference binary (D8: oracle-only) -------------------
PIN_LINE="$(grep -E '^reference ' "$ROOT/SUITE.lock")"
PIN_TAG="$(sed -E 's/.*tag=([^ ]+).*/\1/' <<<"$PIN_LINE")"
PIN_COMMIT="$(sed -E 's/.*commit=([0-9a-f]{40}).*/\1/' <<<"$PIN_LINE")"

LEAN="$HOME/.elan/toolchains/leanprover--lean4---$PIN_TAG/bin/lean"
if [ ! -x "$LEAN" ]; then
  note "setup failure: no Reference binary for $PIN_TAG (install: elan toolchain install leanprover/lean4:$PIN_TAG)"
  exit 2
fi
if [ "$("$LEAN" --githash)" != "$PIN_COMMIT" ]; then
  note "setup failure: binary commit does not match SUITE.lock pin"
  note "  binary : $("$LEAN" --githash)"
  note "  pinned : $PIN_TAG @ $PIN_COMMIT"
  exit 2
fi
note "oracle: $("$LEAN" --version)"

SCRATCH_DIR="$(mktemp -d "${TMPDIR:-/tmp}/seed_protected.XXXXXX")"
NAMES="$SCRATCH_DIR/seed-names.txt"

# ---- 1. the seed's constant names, from the seed itself --------------------------------
if ! ( cd "$ROOT" && FLN_SEED_NAMES_OUT="$NAMES" \
    cargo test --locked -q -p fln --lib \
    source_seed_names::seed_constant_names_are_unique_and_dumpable -- --exact ) >&2; then
  note "setup failure: could not list the source seed's constants"
  exit 2
fi
if [ ! -s "$NAMES" ]; then
  note "setup failure: the seed name dump is empty"
  exit 2
fi

# ---- 2. each name's status at the pin --------------------------------------------------
emit() { # emit <dest>
  local body
  # The pin's own library, never a LEAN_PATH override.
  body="$(env -u LEAN_PATH "$LEAN" --run "$GENERATOR" "$NAMES" | LC_ALL=C sort)"
  {
    printf '# protected.tsv — GENERATED by scripts/extract/gen_seed_protected.sh; never edit by hand.\n'
    printf '# Oracle: leanprover/lean4 %s commit %s (verified against SUITE.lock).\n' "$PIN_TAG" "$PIN_COMMIT"
    printf '# Every constant of the source seed and its status at the pin under import Init:\n'
    printf '# protected, unprotected, or absent (no such constant at the pin). Columns: name, status.\n'
    printf 'schema fln-seed-protected/1\n'
    printf '%s\n' "$body"
  } > "$1"
}

case "$MODE" in
  generate)
    mkdir -p "$(dirname "$TABLE")"
    emit "$TABLE"
    note "wrote $(grep -c $'\tprotected$' "$TABLE") protected of $(grep -vc '^#\|^schema ' "$TABLE") seed constants to ${TABLE#"$ROOT"/}"
    ;;
  check)
    SCRATCH="$SCRATCH_DIR/protected.tsv"
    emit "$SCRATCH"
    if ! diff -u "$TABLE" "$SCRATCH" >&2; then
      note "DRIFT: checked-in table does not match the pin and the seed (see diff above); scratch kept at $SCRATCH"
      exit 1
    fi
    note "no drift: table matches the pin and the seed; scratch kept at $SCRATCH"
    ;;
esac
