#!/usr/bin/env bash
# gen_extern_census.sh — publish the exact extern/builtin environment census
# from a pin-verified Reference walk (beads franken_lean-53v, fln-3tye; plan
# Appendix C; Rule D5/D8-2: derived, never remembered).
#
# The Reference participates here in exactly one legal capacity: census mine via
# a checked-in extraction script. The binary is located via elan, its commit is
# verified against SUITE.lock, and all projections are deterministic. Publication
# is a serialized candidate group: every candidate is synced and validated before
# atomic renames, and any interrupted candidate makes all consumers refuse.
#
# Usage: scripts/extract/gen_extern_census.sh [generate|--check|--validate|--self-test|--recover]

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
GENERATOR="$ROOT/scripts/extract/gen_extern_census.lean"
VALIDATOR="$ROOT/scripts/extract/validate_extern_builtin_census.py"
POLICY="$ROOT/ci/BUILTIN_PARTITION_POLICY.txt"
EXTERN="$ROOT/contracts/extern_census.tsv"
OBSERVED="$ROOT/contracts/builtin_environment.tsv"
OBSERVED_001="$ROOT/contracts/builtin_environment.001.tsv"
OBSERVED_002="$ROOT/contracts/builtin_environment.002.tsv"
PARTITION="$ROOT/contracts/builtin_partition.tsv"
MANIFEST="$ROOT/contracts/EXTERN_BUILTIN_ENVIRONMENT.txt"
EXTERN_CANDIDATE="$EXTERN.candidate"
OBSERVED_CANDIDATE="$OBSERVED.candidate"
OBSERVED_001_CANDIDATE="$OBSERVED_001.candidate"
OBSERVED_002_CANDIDATE="$OBSERVED_002.candidate"
PARTITION_CANDIDATE="$PARTITION.candidate"
MANIFEST_CANDIDATE="$MANIFEST.candidate"
MODE="${1:-generate}"
PUBLICATION_LOCK="/data/tmp/fln-extern-builtin-census.lockfile"

note() { echo "[gen_extern_census] $*" >&2; }
reject() {
  note "inconclusive reason=$1: $2"
  exit 3
}

exec 200>"$PUBLICATION_LOCK"
if ! flock -w 2400 200; then
  reject "publication_lock_timeout" "could not serialize census publication"
fi

# ---- locate and verify the pinned Reference binary (D8: oracle-only) -------------------
PIN_LINE="$(grep -E '^reference ' "$ROOT/SUITE.lock")"
PIN_TAG="$(sed -E 's/.*tag=([^ ]+).*/\1/' <<<"$PIN_LINE")"
PIN_COMMIT="$(sed -E 's/.*commit=([0-9a-f]{40}).*/\1/' <<<"$PIN_LINE")"
PIN_TREE="$(sed -E 's/.*tree=([0-9a-f]{40}).*/\1/' <<<"$PIN_LINE")"
SUITE_ROOT="$(sha256sum "$ROOT/SUITE.lock" | awk '{print $1}')"
POLICY_ROOT="$(sha256sum "$POLICY" | awk '{print $1}')"

LEAN="$HOME/.elan/toolchains/leanprover--lean4---$PIN_TAG/bin/lean"
if [ ! -x "$LEAN" ]; then
  note "setup failure: no Reference binary for $PIN_TAG (install: elan toolchain install leanprover/lean4:$PIN_TAG)"
  exit 2
fi

VERSION="$("$LEAN" --version)"
if ! grep -q "$PIN_COMMIT" <<<"$VERSION"; then
  note "setup failure: binary commit does not match SUITE.lock pin"
  note "  binary : $VERSION"
  note "  pinned : $PIN_TAG @ $PIN_COMMIT"
  exit 2
fi
note "oracle: $VERSION"

# ---- deterministic projections ----------------------------------------------------------
emit_extern() {
  {
    printf '# extern_census.tsv — GENERATED by scripts/extract/gen_extern_census.sh.\n'
    printf '# Oracle: leanprover/lean4 %s commit %s (verified against SUITE.lock).\n' "$PIN_TAG" "$PIN_COMMIT"
    # The backticks are literal Markdown code delimiters in generated TSV prose.
    # shellcheck disable=SC2016
    printf '# Pin-verified environment walk over the full `Lean` import closure\n'
    printf '# (plan Appendix C). Regenerate with the script; never edit by hand (Rule D5).\n'
    printf 'schema fln-extern-census/1\n'
    "$LEAN" --run "$GENERATOR" extern
  }
}

emit_observed() {
  {
    printf '# builtin_environment.tsv — GENERATED; raw Reference environment facts.\n'
    printf '# Oracle-only fixture/census mine; no runtime or release dependency.\n'
    printf 'schema fln-builtin-environment/1\n'
    printf 'oracle_kind\treference-environment-walk\n'
    printf 'reference_commit\t%s\n' "$PIN_COMMIT"
    printf 'reference_tree\t%s\n' "$PIN_TREE"
    printf 'suite_lock_sha256\t%s\n' "$SUITE_ROOT"
    "$LEAN" --run "$GENERATOR" observed
  }
}

emit_observed_shards() { # shard-000 shard-001 shard-002
  local shard_000="$1"
  local shard_001="$2"
  local shard_002="$3"
  local shard
  for shard in "$shard_000" "$shard_001" "$shard_002"; do
    if ! (set -o noclobber; : >"$shard"); then
      return 1
    fi
  done
  emit_observed | awk -F '\t' \
    -v shard_000="$shard_000" \
    -v shard_001="$shard_001" \
    -v shard_002="$shard_002" '
      BEGIN { total = 0; rows = 0 }
      $1 == "constant_count" { total = $2 + 0 }
      $1 == "observed" {
        if (total <= 0) {
          exit 40
        }
        shard_index = int(rows * 3 / total)
        if (shard_index == 0) {
          print > shard_000
        } else if (shard_index == 1) {
          print > shard_001
        } else {
          print > shard_002
        }
        rows += 1
        next
      }
      {
        print > shard_000
        print > shard_001
        print > shard_002
      }
      END {
        if (rows != total) {
          exit 41
        }
      }
    '
}

emit_partition() {
  {
    printf '# builtin_partition.tsv — GENERATED from reviewed first-match policy.\n'
    printf '# Observations remain in builtin_environment.tsv; this file is their bijective policy join.\n'
    printf 'schema fln-builtin-partition/1\n'
    printf 'partition_policy_sha256\t%s\n' "$POLICY_ROOT"
    "$LEAN" --run "$GENERATOR" partition
  }
}

observed_group_sha256() { # shard-000 shard-001 shard-002
  cat "$1" "$2" "$3" | sha256sum | awk '{print $1}'
}

manifest_prefix() { # extern observed-000 observed-001 observed-002 partition
  local extern_path="$1"
  local observed_000_path="$2"
  local observed_001_path="$3"
  local observed_002_path="$4"
  local partition_path="$5"
  printf '# EXTERN_BUILTIN_ENVIRONMENT.txt — GENERATED publication envelope.\n'
  printf 'schema fln-extern-builtin-environment/1\n'
  printf 'extractor\tlean-reference-environment-walk-v2\n'
  printf 'extern-census-sha256\t%s\n' "$(sha256sum "$extern_path" | awk '{print $1}')"
  printf 'builtin-environment-sha256\t%s\n' \
    "$(observed_group_sha256 "$observed_000_path" "$observed_001_path" "$observed_002_path")"
  printf 'builtin-partition-sha256\t%s\n' "$(sha256sum "$partition_path" | awk '{print $1}')"
  printf 'partition-policy-sha256\t%s\n' "$POLICY_ROOT"
  printf 'constant-count\t%s\n' "$(awk -F '\t' '$1=="constant_count"{print $2; exit}' "$observed_000_path")"
  printf 'extern-count\t%s\n' "$(awk -F '\t' '$1=="extern_count"{print $2; exit}' "$observed_000_path")"
  printf 'module-count\t%s\n' "$(awk -F '\t' '$1=="module_count"{print $2; exit}' "$observed_000_path")"
  printf 'attribute-count\t%s\n' "$(awk -F '\t' '$1=="attribute_count"{print $2; exit}' "$observed_000_path")"
  printf 'toolchain-api-count\t%s\n' "$(awk -F '\t' '$1=="toolchain_api_count"{print $2; exit}' "$partition_path")"
  printf 'library-code-count\t%s\n' "$(awk -F '\t' '$1=="library_code_count"{print $2; exit}' "$partition_path")"
  printf 'user-facing-data-count\t%s\n' "$(awk -F '\t' '$1=="user_facing_data_count"{print $2; exit}' "$partition_path")"
  printf 'unresolved-count\t%s\n' "$(awk -F '\t' '$1=="unresolved_count"{print $2; exit}' "$partition_path")"
}

emit_manifest() { # destination extern observed-000 observed-001 observed-002 partition
  local destination="$1"
  local extern_path="$2"
  local observed_000_path="$3"
  local observed_001_path="$4"
  local observed_002_path="$5"
  local partition_path="$6"
  manifest_prefix \
    "$extern_path" \
    "$observed_000_path" \
    "$observed_001_path" \
    "$observed_002_path" \
    "$partition_path" >"$destination"
  local manifest_root
  manifest_root="$(sha256sum "$destination" | awk '{print $1}')"
  printf 'manifest-root\tsha256:%s\n' "$manifest_root" >>"$destination"
}

validate_paths() { # extern observed-000 observed-001 observed-002 partition manifest
  local policy_path="${7:-$POLICY}"
  python3 -I -S "$VALIDATOR" \
    --root "$ROOT" \
    --extern "$1" \
    --observed "$2" \
    --observed "$3" \
    --observed "$4" \
    --partition "$5" \
    --manifest "$6" \
    --policy "$policy_path"
}

candidate_count() {
  local count=0
  local candidate
  for candidate in \
    "$EXTERN_CANDIDATE" \
    "$OBSERVED_CANDIDATE" \
    "$OBSERVED_001_CANDIDATE" \
    "$OBSERVED_002_CANDIDATE" \
    "$PARTITION_CANDIDATE" \
    "$MANIFEST_CANDIDATE"; do
    [ ! -e "$candidate" ] || count=$((count + 1))
  done
  printf '%s\n' "$count"
}

ensure_clean_publication_state() {
  local count
  count="$(candidate_count)"
  if [ "$count" -ne 0 ]; then
    reject "stale_candidate" "$count interrupted census candidate(s) exist; published inputs are refused"
  fi
}

sync_file() {
  sync -f "$1"
}

quarantine_candidates() {
  local quarantine
  quarantine="$(mktemp -d /data/tmp/fln-extern-builtin-retained.XXXXXX)"
  local candidate
  for candidate in \
    "$EXTERN_CANDIDATE" \
    "$OBSERVED_CANDIDATE" \
    "$OBSERVED_001_CANDIDATE" \
    "$OBSERVED_002_CANDIDATE" \
    "$PARTITION_CANDIDATE" \
    "$MANIFEST_CANDIDATE"; do
    if [ -e "$candidate" ]; then
      mv -- "$candidate" "$quarantine/$(basename "$candidate")"
    fi
  done
  sync -f "$quarantine"
  sync -f "$ROOT/contracts"
  note "retained incomplete candidate set at $quarantine"
}

stage_scratch_candidates() { # scratch-dir
  local scratch="$1"
  if [ "$(stat -c '%d' "$scratch")" != "$(stat -c '%d' "$ROOT/contracts")" ]; then
    reject "non_atomic_staging_device" "scratch and contracts must share a filesystem"
  fi
  local source
  for source in \
    "$scratch/extern_census.tsv" \
    "$scratch/builtin_environment.tsv" \
    "$scratch/builtin_environment.001.tsv" \
    "$scratch/builtin_environment.002.tsv" \
    "$scratch/builtin_partition.tsv" \
    "$scratch/EXTERN_BUILTIN_ENVIRONMENT.txt"; do
    sync_file "$source"
  done
  mv -- "$scratch/extern_census.tsv" "$EXTERN_CANDIDATE"
  mv -- "$scratch/builtin_environment.tsv" "$OBSERVED_CANDIDATE"
  mv -- "$scratch/builtin_environment.001.tsv" "$OBSERVED_001_CANDIDATE"
  mv -- "$scratch/builtin_environment.002.tsv" "$OBSERVED_002_CANDIDATE"
  mv -- "$scratch/builtin_partition.tsv" "$PARTITION_CANDIDATE"
  mv -- "$scratch/EXTERN_BUILTIN_ENVIRONMENT.txt" "$MANIFEST_CANDIDATE"
  sync -f "$ROOT/contracts"
}

publish_candidates() {
  validate_paths \
    "$EXTERN_CANDIDATE" \
    "$OBSERVED_CANDIDATE" \
    "$OBSERVED_001_CANDIDATE" \
    "$OBSERVED_002_CANDIDATE" \
    "$PARTITION_CANDIDATE" \
    "$MANIFEST_CANDIDATE"
  local current_suite_root current_policy_root
  current_suite_root="$(sha256sum "$ROOT/SUITE.lock" | awk '{print $1}')"
  current_policy_root="$(sha256sum "$POLICY" | awk '{print $1}')"
  if [ "$current_suite_root" != "$SUITE_ROOT" ] || [ "$current_policy_root" != "$POLICY_ROOT" ]; then
    reject "governed_source_changed" "SUITE.lock or partition policy changed during the sealed walk"
  fi
  sync_file "$EXTERN_CANDIDATE"
  sync_file "$OBSERVED_CANDIDATE"
  sync_file "$OBSERVED_001_CANDIDATE"
  sync_file "$OBSERVED_002_CANDIDATE"
  sync_file "$PARTITION_CANDIDATE"
  sync_file "$MANIFEST_CANDIDATE"
  mv -f -- "$EXTERN_CANDIDATE" "$EXTERN"
  mv -f -- "$OBSERVED_CANDIDATE" "$OBSERVED"
  mv -f -- "$OBSERVED_001_CANDIDATE" "$OBSERVED_001"
  mv -f -- "$OBSERVED_002_CANDIDATE" "$OBSERVED_002"
  mv -f -- "$PARTITION_CANDIDATE" "$PARTITION"
  mv -f -- "$MANIFEST_CANDIDATE" "$MANIFEST"
  sync -f "$ROOT/contracts"
  validate_paths \
    "$EXTERN" \
    "$OBSERVED" \
    "$OBSERVED_001" \
    "$OBSERVED_002" \
    "$PARTITION" \
    "$MANIFEST"
}

generate_candidates() {
  ensure_clean_publication_state
  mkdir -p "$ROOT/contracts"
  local scratch
  scratch="$(mktemp -d /data/tmp/fln-extern-builtin-stage.XXXXXX)"
  generate_scratch "$scratch"
  stage_scratch_candidates "$scratch"
}

generate_scratch() { # scratch-dir
  local scratch="$1"
  emit_extern >"$scratch/extern_census.tsv"
  emit_observed_shards \
    "$scratch/builtin_environment.tsv" \
    "$scratch/builtin_environment.001.tsv" \
    "$scratch/builtin_environment.002.tsv"
  emit_partition >"$scratch/builtin_partition.tsv"
  emit_manifest \
    "$scratch/EXTERN_BUILTIN_ENVIRONMENT.txt" \
    "$scratch/extern_census.tsv" \
    "$scratch/builtin_environment.tsv" \
    "$scratch/builtin_environment.001.tsv" \
    "$scratch/builtin_environment.002.tsv" \
    "$scratch/builtin_partition.tsv"
  validate_paths \
    "$scratch/extern_census.tsv" \
    "$scratch/builtin_environment.tsv" \
    "$scratch/builtin_environment.001.tsv" \
    "$scratch/builtin_environment.002.tsv" \
    "$scratch/builtin_partition.tsv" \
    "$scratch/EXTERN_BUILTIN_ENVIRONMENT.txt"
}

case "$MODE" in
  generate)
    generate_candidates
    publish_candidates
    note "published exact extern/builtin census via synced candidates and atomic renames"
    ;;
  --recover)
    recovery_count="$(candidate_count)"
    if [ "$recovery_count" -eq 0 ]; then
      reject "candidate_set_absent" "there is no interrupted publication to recover"
    elif [ "$recovery_count" -ne 6 ]; then
      quarantine_candidates
      generate_candidates
    fi
    publish_candidates
    note "recovered and published the validated candidate set"
    ;;
  --validate)
    ensure_clean_publication_state
    validate_paths \
      "$EXTERN" \
      "$OBSERVED" \
      "$OBSERVED_001" \
      "$OBSERVED_002" \
      "$PARTITION" \
      "$MANIFEST"
    ;;
  --check)
    ensure_clean_publication_state
    SCRATCH="$(mktemp -d "${TMPDIR:-/tmp}/extern_builtin_check.XXXXXX")"
    generate_scratch "$SCRATCH"
    diff -u "$EXTERN" "$SCRATCH/extern_census.tsv" >&2
    diff -u "$OBSERVED" "$SCRATCH/builtin_environment.tsv" >&2
    diff -u "$OBSERVED_001" "$SCRATCH/builtin_environment.001.tsv" >&2
    diff -u "$OBSERVED_002" "$SCRATCH/builtin_environment.002.tsv" >&2
    diff -u "$PARTITION" "$SCRATCH/builtin_partition.tsv" >&2
    diff -u "$MANIFEST" "$SCRATCH/EXTERN_BUILTIN_ENVIRONMENT.txt" >&2
    note "no drift: two sealed projections and their publication envelope match the pin"
    ;;
  --self-test)
    ensure_clean_publication_state
    SCRATCH="$(mktemp -d "${TMPDIR:-/tmp}/extern_builtin_selftest.XXXXXX")"
    generate_scratch "$SCRATCH"
    MUTATED="$SCRATCH/builtin_environment.omitted.tsv"
    awk 'BEGIN { omitted=0 } /^observed\t/ && omitted==0 { omitted=1; next } { print }' \
      "$SCRATCH/builtin_environment.tsv" >"$MUTATED"
    if validate_paths \
      "$SCRATCH/extern_census.tsv" \
      "$MUTATED" \
      "$SCRATCH/builtin_environment.001.tsv" \
      "$SCRATCH/builtin_environment.002.tsv" \
      "$SCRATCH/builtin_partition.tsv" \
      "$SCRATCH/EXTERN_BUILTIN_ENVIRONMENT.txt" \
      >"$SCRATCH/omission.out" 2>"$SCRATCH/omission.err"; then
      note "SELF-TEST FAILED: validator accepted a planted declaration omission"
      exit 1
    fi
    if ! grep -q 'reason=declaration_count_mismatch' "$SCRATCH/omission.err"; then
      note "SELF-TEST FAILED: omission was rejected for the wrong reason"
      sed -n '1,20p' "$SCRATCH/omission.err" >&2
      exit 1
    fi
    MUTATED_POLICY="$SCRATCH/BUILTIN_PARTITION_POLICY.native-marker-misclassified.txt"
    awk '
      /^rule 01 / {
        sub(/partition=toolchain-api/, "partition=library-code")
      }
      { print }
    ' "$POLICY" >"$MUTATED_POLICY"
    MUTATED_POLICY_ROOT="$(sha256sum "$MUTATED_POLICY" | awk '{print $1}')"
    MUTATED_PARTITION="$SCRATCH/builtin_partition.native-marker-misclassified.tsv"
    awk -F '\t' -v OFS='\t' -v policy_root="$MUTATED_POLICY_ROOT" '
      $1 == "partition_policy_sha256" {
        $2 = policy_root
      }
      { print }
    ' "$SCRATCH/builtin_partition.tsv" >"$MUTATED_PARTITION"
    if validate_paths \
      "$SCRATCH/extern_census.tsv" \
      "$SCRATCH/builtin_environment.tsv" \
      "$SCRATCH/builtin_environment.001.tsv" \
      "$SCRATCH/builtin_environment.002.tsv" \
      "$MUTATED_PARTITION" \
      "$SCRATCH/EXTERN_BUILTIN_ENVIRONMENT.txt" \
      "$MUTATED_POLICY" \
      >"$SCRATCH/native-marker.out" 2>"$SCRATCH/native-marker.err"; then
      note "SELF-TEST FAILED: validator accepted native markers as library code"
      exit 1
    fi
    if ! grep -q 'reason=native_marker_misclassified' "$SCRATCH/native-marker.err"; then
      note "SELF-TEST FAILED: native-marker policy was rejected for the wrong reason"
      sed -n '1,20p' "$SCRATCH/native-marker.err" >&2
      exit 1
    fi
    note "self-test pass: planted omission rejected reason=declaration_count_mismatch"
    note "self-test pass: planted native-marker misclassification rejected"
    ;;
  *)
    note "unknown mode: $MODE"
    exit 2
    ;;
esac
