#!/usr/bin/env bash
# gen_grammar_census.sh — publish the pin's grammar census (bead fln-vokf; plan §9.1;
# Rules D5/D8-2: derived from the pin, never transcribed).
#
# Two generated files, both under contracts/:
#
#   REFERENCE_GRAMMAR_CENSUS.txt   every builtin parser / keyed elaborator registration in the
#                                  pinned binary, the builtin token table and node kinds, the
#                                  module-header tokens, and for every Init/Std module its
#                                  imports, token/kind entries, syntax declarations and macros.
#                                  ~15 s. Consumed by fln-parse's derived token table.
#   REFERENCE_SYNTAX_KIND_USE.txt  every Init/Std source file replayed through the pinned
#                                  frontend: the syntax kinds its commands' parse trees use and
#                                  its syntax-extension commands. ~5-10 CPU-minutes per 100 files.
#
# The Reference participates in exactly one legal capacity: census mine via a checked-in
# extraction script. The binary is located via elan and its commit verified against
# SUITE.lock; the replayed sources are vendor/lean4-src, whose subtree id must equal the
# SUITE.lock `tree=` pin. Every projection is deterministic (sorted, no times, no absolute
# paths), so --check is a byte comparison.
#
# Usage: scripts/extract/gen_grammar_census.sh [generate|--check|--grammar|--check-grammar]
#   generate         regenerate both files (atomic: .candidate then rename)
#   --check          regenerate both into scratch and diff against the published files
#   --grammar        regenerate REFERENCE_GRAMMAR_CENSUS.txt only
#   --check-grammar  drift-check REFERENCE_GRAMMAR_CENSUS.txt only (the cheap half)
# Exit: 0 ok / no drift, 1 drift, 2 setup failure (no pin, wrong commit, vendor drift),
#       3 the oracle refused (a totality check failed inside the extractor, or a replay fault).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
GENERATOR="$ROOT/scripts/extract/gen_grammar_census.lean"
GRAMMAR="$ROOT/contracts/REFERENCE_GRAMMAR_CENSUS.txt"
KIND_USE="$ROOT/contracts/REFERENCE_SYNTAX_KIND_USE.txt"
VENDOR="$ROOT/vendor/lean4-src"
MODE="${1:-generate}"
JOBS="${FLN_GRAMMAR_CENSUS_JOBS:-12}"

note() { echo "[gen_grammar_census] $*" >&2; }

# ---- locate and verify the pinned Reference (D8: oracle-only) ---------------------------
PIN_LINE="$(grep -E '^reference ' "$ROOT/SUITE.lock")"
PIN_TAG="$(sed -E 's/.*tag=([^ ]+).*/\1/' <<<"$PIN_LINE")"
PIN_COMMIT="$(sed -E 's/.*commit=([0-9a-f]{40}).*/\1/' <<<"$PIN_LINE")"
PIN_TREE="$(sed -E 's/.*tree=([0-9a-f]{40}).*/\1/' <<<"$PIN_LINE")"

LEAN="$HOME/.elan/toolchains/leanprover--lean4---$PIN_TAG/bin/lean"
if [ ! -x "$LEAN" ]; then
  note "setup failure: no Reference binary for $PIN_TAG (install: elan toolchain install leanprover/lean4:$PIN_TAG)"
  exit 2
fi
VERSION="$("$LEAN" --version)"
if ! grep -q "$PIN_COMMIT" <<<"$VERSION"; then
  note "setup failure: binary commit does not match SUITE.lock pin"
  note "  binary : $VERSION"
  note "  pinned : $PIN_TAG @ $PIN_COMMIT"
  exit 2
fi

if [ "$MODE" = "--replay-one" ]; then
  # internal: emit_kind_use's per-file worker; the parent already verified the vendor tree
  cd "$ROOT"
  exec "$LEAN" --run "$GENERATOR" replay "$4" "$5" >"$2/$3.out" 2>"$2/$3.err"
fi

# The replay reads vendor sources, so they must be the pinned tree, unmodified.
VENDOR_TREE="$(git -C "$ROOT" rev-parse "HEAD:vendor/lean4-src")"
if [ "$VENDOR_TREE" != "$PIN_TREE" ]; then
  note "setup failure: committed vendor/lean4-src is $VENDOR_TREE, SUITE.lock pins $PIN_TREE"
  exit 2
fi
if [ -n "$(git -C "$ROOT" status --porcelain -- vendor/lean4-src)" ]; then
  note "setup failure: vendor/lean4-src differs from the committed pinned tree"
  exit 2
fi
note "oracle: $VERSION"

GENERATOR_SHA="$(sha256sum "$GENERATOR" | awk '{print $1}')"
DRIVER_SHA="$(sha256sum "$ROOT/scripts/extract/gen_grammar_census.sh" | awk '{print $1}')"
SUITE_SHA="$(sha256sum "$ROOT/SUITE.lock" | awk '{print $1}')"

provenance() { # <schema> <file-name>
  printf '# %s — GENERATED by scripts/extract/gen_grammar_census.sh (bead fln-vokf).\n' "$2"
  printf '# Oracle: leanprover/lean4 %s commit %s (verified against SUITE.lock).\n' "$PIN_TAG" "$PIN_COMMIT"
  printf '# Regenerate with the script; never edit by hand (Rule D5). Tab-separated rows;\n'
  printf '# multi-valued fields are space-separated (tokens never contain whitespace: the\n'
  printf '# extractor refuses one that does).\n'
  printf 'schema\t%s\n' "$1"
  printf 'reference\t%s\t%s\ttree=%s\n' "$PIN_TAG" "$PIN_COMMIT" "$PIN_TREE"
  printf 'suite-lock-sha256\t%s\n' "$SUITE_SHA"
  printf 'generator-sha256\t%s\n' "$GENERATOR_SHA"
  printf 'driver-sha256\t%s\n' "$DRIVER_SHA"
}

emit_grammar() { # <dest>
  local body status
  body="$(mktemp "${TMPDIR:-/tmp}/grammar_census.XXXXXX")"
  set +e
  (cd "$ROOT" && "$LEAN" --run "$GENERATOR" grammar) >"$body"
  status=$?
  set -e
  if [ "$status" -ne 0 ]; then
    note "the extractor refused (exit $status); nothing published"
    exit 3
  fi
  { provenance fln-reference-grammar-census/1 REFERENCE_GRAMMAR_CENSUS.txt; cat "$body"; } >"$1"
  rm -f "$body"
}

source_list() { # Init.lean, Std.lean and every file below src/Init, src/Std, as "<path>\t<module>"
  (cd "$VENDOR/src" && { printf '%s\n' Init.lean Std.lean; find Init Std -name '*.lean'; } | LC_ALL=C sort) |
    while IFS= read -r rel; do
      local module="${rel%.lean}"
      printf '%s\t%s\n' "$VENDOR/src/$rel" "${module//\//.}"
    done
}

emit_kind_use() { # <dest>
  # One oracle process per file: an in-process batch is measurably unfaithful (see the
  # generator's `replay`). A nonzero exit from any file is a fault and nothing is published.
  local work status
  work="$(mktemp -d "${TMPDIR:-/tmp}/grammar_replay.XXXXXX")"
  source_list | awk -F '\t' '{ printf "%06d\t%s\t%s\n", NR, $1, $2 }' >"$work/all.tsv"
  set +e
  tr '\t' '\n' <"$work/all.tsv" |
    xargs -P "$JOBS" -n 3 bash "$ROOT/scripts/extract/gen_grammar_census.sh" --replay-one "$work"
  status=$?
  set -e
  if [ "$status" -ne 0 ]; then
    note "a replay faulted (xargs exit $status); see $work/*.err"
    exit 3
  fi
  {
    provenance fln-reference-syntax-kind-use/1 REFERENCE_SYNTAX_KIND_USE.txt
    cat "$work"/[0-9]*.out | python3 -I -S -c '
import sys
blocks, current = {}, None
for line in sys.stdin.read().splitlines():
    fields = line.split("\t")
    if fields[0] == "file":
        current = fields[1]
        if current in blocks:
            sys.exit("duplicate replay record for " + current)
        blocks[current] = []
    if current is None:
        sys.exit("replay output does not start with a file record")
    blocks[current].append(line)
files = len(blocks)
commands = errors = faults = 0
kinds, syntax_commands = set(), {}
for rows in blocks.values():
    head = rows[0].split("\t")
    if any(f.startswith("fault=") for f in head):
        faults += 1
        continue
    commands += int(head[3].split("=")[1])
    errors += int(head[4].split("=")[1])
    for row in rows[1:]:
        fields = row.split("\t")
        if fields[0] == "uses":
            kinds.update(fields[2].split(" "))
        elif fields[0] == "syntax-command":
            syntax_commands[fields[3]] = syntax_commands.get(fields[3], 0) + 1
print("count\tfiles\t%d" % files)
print("count\tcommands\t%d" % commands)
print("count\terrors\t%d" % errors)
print("count\tfaults\t%d" % faults)
print("count\tdistinct-kinds\t%d" % len(kinds))
print("count\tsyntax-commands\t%d" % sum(syntax_commands.values()))
for kind in sorted(syntax_commands):
    print("syntax-command-kind\t%s\t%d" % (kind, syntax_commands[kind]))
for module in sorted(blocks):
    for row in blocks[module]:
        print(row)
'
  } >"$1"
  rm -rf "$work"
}

publish() { # <candidate> <final>
  mv -f "$1" "$2"
}

case "$MODE" in
  generate)
    emit_grammar "$GRAMMAR.candidate"
    emit_kind_use "$KIND_USE.candidate"
    publish "$GRAMMAR.candidate" "$GRAMMAR"
    publish "$KIND_USE.candidate" "$KIND_USE"
    note "wrote ${GRAMMAR#"$ROOT"/} and ${KIND_USE#"$ROOT"/}"
    ;;
  --grammar)
    emit_grammar "$GRAMMAR.candidate"
    publish "$GRAMMAR.candidate" "$GRAMMAR"
    note "wrote ${GRAMMAR#"$ROOT"/}"
    ;;
  --check|--check-grammar)
    SCRATCH="$(mktemp -d "${TMPDIR:-/tmp}/grammar_census_check.XXXXXX")"
    drift=0
    emit_grammar "$SCRATCH/grammar.txt"
    if ! diff -u "$GRAMMAR" "$SCRATCH/grammar.txt" >&2; then drift=1; fi
    if [ "$MODE" = "--check" ]; then
      emit_kind_use "$SCRATCH/kind_use.txt"
      if ! diff -u "$KIND_USE" "$SCRATCH/kind_use.txt" >&2; then drift=1; fi
    fi
    rm -rf "$SCRATCH"
    if [ "$drift" -ne 0 ]; then
      note "DRIFT: the published census does not match the pin (diff above)"
      exit 1
    fi
    note "no drift: the census matches the pin"
    ;;
  *)
    note "unknown mode: $MODE"
    exit 2
    ;;
esac
