#!/usr/bin/env -S python3 -I -S
"""Extract native source-import extension layouts from pinned Lean source data.

No Lean code executes. Field order, pointer/scalar slots, scoped-entry tags and
attribute-kind tags come from the declarations, not observations of one fixture.
Only the supported field types have a physical layout; drift fails closed.
"""
import argparse
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
VENDOR = ROOT / "vendor/lean4-src"
OUTPUT = ROOT / "crates/fln-olean/src/source_extension_format.rs"


def strip_comments(text):
    out, i, depth = [], 0, 0
    while i < len(text):
        if text.startswith("/-", i):
            depth += 1
            i += 2
        elif depth and text.startswith("-/", i):
            depth -= 1
            i += 2
        elif depth:
            out.append("\n" if text[i] == "\n" else " ")
            i += 1
        elif text.startswith("--", i):
            end = text.find("\n", i)
            i = len(text) if end < 0 else end
        else:
            out.append(text[i])
            i += 1
    if depth:
        raise ValueError("unterminated Lean comment")
    return "".join(out)


def declaration(text, kind, name):
    found = re.search(r"^" + kind + r" " + re.escape(name) + r"[^\n]*\n", text, re.M)
    if found is None:
        raise ValueError(f"missing {kind} {name}")
    end = re.search(r"^\S", text[found.end():], re.M)
    return text[found.end():found.end() + end.start()] if end else text[found.end():]


def render():
    reference = [line for line in (ROOT / "SUITE.lock").read_text().splitlines() if line.startswith("reference ")]
    if len(reference) != 1:
        raise ValueError("expected one Reference pin")
    pin = dict(item.split("=", 1) for item in reference[0].split()[2:])
    files = ["src/Lean/Class.lean", "src/Lean/Meta/Instances.lean", "src/Lean/ScopedEnvExtension.lean", "src/Lean/Attributes.lean"]
    sources = {path: (VENDOR / path).read_text(encoding="utf-8") for path in files}
    text = {path: strip_comments(value) for path, value in sources.items()}
    lines = ["//! Generated by scripts/extract/gen_source_extension_contract.py; do not edit.",
             f"//! Reference: {pin['tag']} @ {pin['commit']}."]
    for path in files:
        digest = hashlib.sha256(sources[path].encode()).hexdigest()
        lines.append(f"//! {path}: sha256 {digest}")
    lines += ["#![allow(dead_code)]", ""]
    pointers = {"Name", "Array Nat", "Array InstanceKey", "Expr", "Nat", "Option Name"}
    for prefix, path, name in [("CLASS", files[0], "ClassEntry"), ("INSTANCE", files[1], "InstanceEntry"), ("DEFAULT", files[1], "DefaultInstanceEntry")]:
        body = declaration(text[path], "structure", name)
        fields = re.findall(r"^\s+(\w+\??)\s*:\s*(.+?)(?:\s*:=.*)?$", body, re.M)
        if not fields:
            raise ValueError(f"no fields for {name}")
        ptr, scalar = 0, 0
        for field, ty in fields:
            ty = ty.strip()
            field = re.sub(r"([a-z])([A-Z])", r"\1_\2", field).replace("?", "_OPTION").upper()
            if ty in pointers:
                lines.append(f"pub const {prefix}_{field}: usize = {ptr};")
                ptr += 1
            elif ty == "AttributeKind":
                lines.append(f"pub const {prefix}_{field}_SCALAR: usize = {scalar};")
                scalar += 1
            else:
                raise ValueError(f"unsupported {name} field type {ty!r}")
        lines += [f"pub const {prefix}_POINTERS: usize = {ptr};", f"pub const {prefix}_SCALAR_BYTES: usize = {scalar};", ""]
    for path, name, prefix in [(files[2], "Entry", "SCOPE"), (files[3], "AttributeKind", "ATTRIBUTE")]:
        body = declaration(text[path], "inductive", name)
        tags = re.findall(r"\|\s+(\w+)", body)
        expected = ["global", "scoped"] if prefix == "SCOPE" else ["global", "local", "scoped"]
        if set(tags) != set(expected) or len(tags) != len(expected):
            raise ValueError(f"unsupported {name} inventory: {tags}")
        for index, tag in enumerate(tags):
            lines.append(f"pub const {prefix}_{tag.upper()}: u8 = {index};")
    for path, namespace, variable, row, mode in [
        (files[0], "Lean", "classExtension", "ClassEntry", "SimplePersistentEnvExtension"),
        (files[1], "Lean.Meta", "instanceExtension", "InstanceEntry", "SimpleScopedEnvExtension"),
        (files[1], "Lean.Meta", "defaultInstanceExtension", "DefaultInstanceEntry", "SimplePersistentEnvExtension"),
    ]:
        if not re.search(r"\bnamespace " + re.escape(namespace) + r"\b", text[path]):
            raise ValueError(f"namespace moved: {namespace}")
        if not re.search(r"builtin_initialize\s+" + variable + r"\s*:\s*" + mode + r"\s+" + row + r"\b", text[path]):
            raise ValueError(f"extension schema moved: {variable}")
        prefix = {"classExtension": "CLASS", "instanceExtension": "INSTANCE", "defaultInstanceExtension": "DEFAULT"}[variable]
        lines.append(f'pub const {prefix}_EXTENSION: &str = "{namespace}.{variable}";')
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("source extension contract drift; regenerate and review")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")
    print("source extension contract: 3 structures, 2 constructor inventories; checked")


if __name__ == "__main__":
    main()
