#!/usr/bin/env bash
# gen_seed_csimp.sh — the recursors the pin's code generator compiles through a
# `@[csimp]` replacement (bead franken_lean-z8j.1.6.6; Rule D5/D8-2: derived, never
# remembered).
#
# The pin refuses a compiled declaration that applies a recursor directly ("code
# generator does not support recursor"), except where a csimp lemma replaces that
# recursor first (`Nat.rec` by `Nat.recCompiled`). A headerless file sees the csimp set
# of `import Init`, so this script asks the pinned Reference binary (located via elan,
# its commit verified against SUITE.lock) for exactly that set's recursor entries.
# The output is deterministic (sorted, no timestamps or paths), so two runs are
# byte-identical.
#
# Output: crates/fln-elab/src/seed/csimp_recursors.tsv
#
# Usage: scripts/extract/gen_seed_csimp.sh [--check]
#   --check  regenerate to a scratch file and diff against the checked-in table
#            (drift mode; exit 1 on drift, 2 on setup failure)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
GENERATOR="$ROOT/scripts/extract/gen_seed_csimp.lean"
TABLE="$ROOT/crates/fln-elab/src/seed/csimp_recursors.tsv"
MODE="generate"
if [ "${1:-}" = "--check" ]; then
  MODE="check"
fi

note() { echo "[gen_seed_csimp] $*" >&2; }

# ---- locate and verify the pinned Reference binary (D8: oracle-only) -------------------
PIN_LINE="$(grep -E '^reference ' "$ROOT/SUITE.lock")"
PIN_TAG="$(sed -E 's/.*tag=([^ ]+).*/\1/' <<<"$PIN_LINE")"
PIN_COMMIT="$(sed -E 's/.*commit=([0-9a-f]{40}).*/\1/' <<<"$PIN_LINE")"

LEAN="$HOME/.elan/toolchains/leanprover--lean4---$PIN_TAG/bin/lean"
if [ ! -x "$LEAN" ]; then
  note "setup failure: no Reference binary for $PIN_TAG (install: elan toolchain install leanprover/lean4:$PIN_TAG)"
  exit 2
fi
if [ "$("$LEAN" --githash)" != "$PIN_COMMIT" ]; then
  note "setup failure: binary commit does not match SUITE.lock pin"
  note "  binary : $("$LEAN" --githash)"
  note "  pinned : $PIN_TAG @ $PIN_COMMIT"
  exit 2
fi
note "oracle: $("$LEAN" --version)"

emit() { # emit <dest>
  local body
  # The pin's own library, never a LEAN_PATH override.
  body="$(env -u LEAN_PATH "$LEAN" --run "$GENERATOR" | LC_ALL=C sort)"
  if [ -z "$body" ]; then
    note "setup failure: the pin reported no csimp recursor (expected at least Nat.rec)"
    exit 2
  fi
  {
    printf '# csimp_recursors.tsv — GENERATED by scripts/extract/gen_seed_csimp.sh; never edit by hand.\n'
    printf '# Oracle: leanprover/lean4 %s commit %s (verified against SUITE.lock).\n' "$PIN_TAG" "$PIN_COMMIT"
    printf '# Every recursor the pin'"'"'s csimp set replaces under import Init, so its code generator\n'
    printf '# compiles it. Columns: recursor, replacement.\n'
    printf 'schema fln-seed-csimp-recursors/1\n'
    printf '%s\n' "$body"
  } > "$1"
}

case "$MODE" in
  generate)
    mkdir -p "$(dirname "$TABLE")"
    emit "$TABLE"
    note "wrote $(grep -vc '^#\|^schema ' "$TABLE") csimp recursors to ${TABLE#"$ROOT"/}"
    ;;
  check)
    SCRATCH_DIR="$(mktemp -d "${TMPDIR:-/tmp}/seed_csimp.XXXXXX")"
    SCRATCH="$SCRATCH_DIR/csimp_recursors.tsv"
    emit "$SCRATCH"
    if ! diff -u "$TABLE" "$SCRATCH" >&2; then
      note "DRIFT: checked-in table does not match the pin (see diff above); scratch kept at $SCRATCH"
      exit 1
    fi
    note "no drift: table matches the pin; scratch kept at $SCRATCH"
    ;;
esac
