#!/usr/bin/env bash
# gen_core_fixtures.sh — regenerate the C0 core-observable fixtures from the pinned
# Reference binary (bead franken_lean-p8a; Rule D5/D8-2: derived, never remembered).
#
# The Reference participates here in exactly one legal capacity: fixture mine inside
# the conformance apparatus. The binary is located via elan, its commit is verified
# against SUITE.lock, and the output is deterministic (no timestamps, no paths) so
# two runs are byte-identical. Output: crates/fln-conformance/fixtures/core_observables.txt
#
# Usage: scripts/extract/gen_core_fixtures.sh [--check]
#   --check  regenerate to a scratch file and diff against the checked-in fixture
#            (CI drift mode; exit 1 on drift, 2 on setup failure)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
GENERATOR="$ROOT/scripts/extract/gen_core_fixtures.lean"
FIXTURE="$ROOT/crates/fln-conformance/fixtures/core_observables.txt"
MODE="${1:-generate}"

note() { echo "[gen_core_fixtures] $*" >&2; }

# ---- locate and verify the pinned Reference binary (D8: oracle-only) -------------------
PIN_LINE="$(grep -E '^reference ' "$ROOT/SUITE.lock")"
PIN_TAG="$(sed -E 's/.*tag=([^ ]+).*/\1/' <<<"$PIN_LINE")"
PIN_COMMIT="$(sed -E 's/.*commit=([0-9a-f]{40}).*/\1/' <<<"$PIN_LINE")"

LEAN=""
for candidate in "$HOME/.elan/toolchains/leanprover--lean4---$PIN_TAG/bin/lean" \
                 "$(command -v lean 2>/dev/null || true)"; do
  [ -n "$candidate" ] && [ -x "$candidate" ] && { LEAN="$candidate"; break; }
done
if [ -z "$LEAN" ]; then
  note "setup failure: no Reference binary for $PIN_TAG (install: elan toolchain install leanprover/lean4:$PIN_TAG)"
  exit 2
fi

VERSION="$("$LEAN" --version)"
if ! grep -q "$PIN_COMMIT" <<<"$VERSION"; then
  note "setup failure: binary commit does not match SUITE.lock pin"
  note "  binary : $VERSION"
  note "  pinned : $PIN_TAG @ $PIN_COMMIT"
  exit 2
fi
note "oracle: $VERSION"

# ---- generate --------------------------------------------------------------------------
emit() { # emit <dest>
  {
    printf '# core_observables.txt — GENERATED by scripts/extract/gen_core_fixtures.sh.\n'
    printf '# Oracle: leanprover/lean4 %s commit %s (verified against SUITE.lock).\n' "$PIN_TAG" "$PIN_COMMIT"
    printf '# Regenerate with the script; never edit by hand (Rule D5).\n'
    printf 'schema fln-core-observables/1\n'
    "$LEAN" --run "$GENERATOR"
  } > "$1"
}

case "$MODE" in
  generate)
    mkdir -p "$(dirname "$FIXTURE")"
    emit "$FIXTURE"
    note "wrote $(grep -c '|' "$FIXTURE") records to ${FIXTURE#"$ROOT"/}"
    ;;
  --check)
    SCRATCH="$(mktemp "${TMPDIR:-/tmp}/core_observables.XXXXXX.txt")"
    emit "$SCRATCH"
    if ! diff -u "$FIXTURE" "$SCRATCH" >&2; then
      note "DRIFT: checked-in fixture does not match the pin (see diff above)"
      exit 1
    fi
    note "no drift: fixture matches the pin"
    ;;
  *)
    note "unknown mode: $MODE"
    exit 2
    ;;
esac
