#!/usr/bin/env bash
# gen_instance_choices.sh — the pin's instance candidate order and choice for every
# instance goal of one pinned module's closure (bead fln-vm35; Rule D5/D8-2: derived,
# never remembered).
#
# The Reference participates here in exactly one legal capacity: fixture mine inside
# the conformance apparatus. The binary is located via elan, its commit is verified
# against SUITE.lock, and the output is deterministic (no timestamps, no paths), so
# two runs are byte-identical. The record format is documented in
# scripts/extract/gen_instance_choices.lean.
#
# Output: crates/fln/tests/fixtures/instance_choices/<Module>.tsv
#
# Usage: scripts/extract/gen_instance_choices.sh [--check] [<Module>]   (default Init.Core)
#   --check  regenerate to a scratch file and diff against the checked-in fixture
#            (drift mode; exit 1 on drift, 2 on setup failure)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
GENERATOR="$ROOT/scripts/extract/gen_instance_choices.lean"
MODE="generate"
if [ "${1:-}" = "--check" ]; then
  MODE="check"
  shift
fi
MODULE="${1:-Init.Core}"
FIXTURE="$ROOT/crates/fln/tests/fixtures/instance_choices/$MODULE.tsv"

note() { echo "[gen_instance_choices] $*" >&2; }

# ---- locate and verify the pinned Reference binary (D8: oracle-only) -------------------
PIN_LINE="$(grep -E '^reference ' "$ROOT/SUITE.lock")"
PIN_TAG="$(sed -E 's/.*tag=([^ ]+).*/\1/' <<<"$PIN_LINE")"
PIN_COMMIT="$(sed -E 's/.*commit=([0-9a-f]{40}).*/\1/' <<<"$PIN_LINE")"

LEAN="$HOME/.elan/toolchains/leanprover--lean4---$PIN_TAG/bin/lean"
if [ ! -x "$LEAN" ]; then
  note "setup failure: no Reference binary for $PIN_TAG (install: elan toolchain install leanprover/lean4:$PIN_TAG)"
  exit 2
fi
if [ "$("$LEAN" --githash)" != "$PIN_COMMIT" ]; then
  note "setup failure: binary commit does not match SUITE.lock pin"
  note "  binary : $("$LEAN" --githash)"
  note "  pinned : $PIN_TAG @ $PIN_COMMIT"
  exit 2
fi
note "oracle: $("$LEAN" --version)"

# ---- generate --------------------------------------------------------------------------
emit() { # emit <dest>
  local body
  # The pin's own library, never a LEAN_PATH override.
  body="$(env -u LEAN_PATH "$LEAN" --run "$GENERATOR" "$MODULE")"
  {
    printf '# %s.tsv — GENERATED by scripts/extract/gen_instance_choices.sh; never edit by hand.\n' "$MODULE"
    printf '# Oracle: leanprover/lean4 %s commit %s (verified against SUITE.lock).\n' "$PIN_TAG" "$PIN_COMMIT"
    printf '# Closure: %s. Columns: goal, priority, offered (getInstances order), chosen.\n' "$MODULE"
    printf 'schema fln-instance-choices/1\n'
    printf '%s\n' "$body"
  } > "$1"
}

case "$MODE" in
  generate)
    mkdir -p "$(dirname "$FIXTURE")"
    emit "$FIXTURE"
    note "wrote $(grep -vc '^#\|^schema ' "$FIXTURE") goals to ${FIXTURE#"$ROOT"/}"
    ;;
  check)
    SCRATCH="$(mktemp "${TMPDIR:-/tmp}/instance_choices.XXXXXX.tsv")"
    emit "$SCRATCH"
    if ! diff -u "$FIXTURE" "$SCRATCH" >&2; then
      note "DRIFT: checked-in fixture does not match the pin (see diff above); scratch kept at $SCRATCH"
      exit 1
    fi
    note "no drift: fixture matches the pin; scratch kept at $SCRATCH"
    ;;
esac
