/-
gen_core_ext_fixtures.lean — oracle fixtures for the fln-core surfaces that the C0
corpus in scripts/extract/gen_core_fixtures.lean does not cover (bead fln-it70).

RUN BY THE PINNED REFERENCE BINARY ONLY (D8-2: the Reference as fixture mine).
Do not invoke this file directly — go through the wrapper, which refuses to generate
from anything but the pin:

  scripts/extract/gen_core_ext_fixtures.sh            # regenerate
  scripts/extract/gen_core_ext_fixtures.sh --check    # CI drift mode

Provenance is recorded HERE rather than by the wrapper, and that is deliberate: the
header below carries `Lean.githash`, which is the *binary's own* report of what it is.
A wrapper writing the commit it read from SUITE.lock would make the header a copy of
the expectation instead of an observation. The wrapper verifies the binary before it
runs and verifies this header after; the consuming test
(crates/fln-core/tests/pin_ext_observables.rs) checks it a third time against
SUITE.lock, so a fixture generated by anything other than the pin fails at three
independent places rather than being trusted.

Emits one record per line, '|'-separated, deterministic — no timestamps, no paths.
Labels name values that the Rust side constructs identically; the Rust side fails if
it does not recognise a label, so the two corpora cannot silently drift apart.
-/

import Lean
open Lean

/-- Names the Rust side rebuilds by the same labels. -/
def names : List (String × Name) :=
  [ ("anon",      Name.anonymous)
  , ("a",         .str .anonymous "a")
  , ("b",         .str .anonymous "b")
  , ("a.b",       .str (.str .anonymous "a") "b")
  , ("a.c",       .str (.str .anonymous "a") "c")
  , ("a.b.c",     .str (.str (.str .anonymous "a") "b") "c")
  , ("n0",        .num .anonymous 0)
  , ("n1",        .num .anonymous 1)
  , ("a.n7",      .num (.str .anonymous "a") 7)
  , ("a.n7.b",    .str (.num (.str .anonymous "a") 7) "b")
  ]

/-- Hygienic and near-hygienic names: the `_@`/`_hyg` grammar and its edges. -/
def hygienicNames : List (String × Name) :=
  [ ("plain",           .str (.str .anonymous "Foo") "bar")
  , ("hyg1",            .num (.str (.str (.str (.str .anonymous "Foo") "bar") "_@") "_hyg") 7)
  , ("hyg2",            .num (.num (.str (.str (.str (.str .anonymous "Foo") "bar") "_@") "_hyg") 7) 9)
  , ("hyg_with_module", .num (.str (.str (.str (.str .anonymous "Foo") "_@") "Mod") "_hyg") 3)
  , ("hyg_no_sep",      .num (.str .anonymous "_hyg") 1)
  , ("marker_only",     .str .anonymous "_hyg")
  ]

/-- Levels the Rust side rebuilds by the same labels. `m` is a universe metavariable. -/
def levels : List (String × Level) :=
  [ ("zero",            .zero)
  , ("one",             .succ .zero)
  , ("u",               .param `u)
  , ("v",               .param `v)
  , ("m",               .mvar ⟨`m⟩)
  , ("succ_u",          .succ (.param `u))
  , ("u_plus_2",        .succ (.succ (.param `u)))
  , ("max_u_v",         .max (.param `u) (.param `v))
  , ("imax_u_v",        .imax (.param `u) (.param `v))
  , ("imax_u_zero",     .imax (.param `u) .zero)
  , ("imax_v_succ_u",   .imax (.param `v) (.succ (.param `u)))
  , ("succ_imax_v_su",  .succ (.imax (.param `v) (.succ (.param `u))))
  , ("max_u_succ_v",    .max (.param `u) (.succ (.param `v)))
  , ("three",           .succ (.succ (.succ .zero)))
  ]

/-- Structural rendering, so the fixture pins SEMANTICS rather than the
pretty-printer's formatting choices (which are a separate surface we make no claim
about here). The Rust side reproduces this shape exactly. -/
partial def lvl : Level → String
  | .zero      => "0"
  | .succ u    => s!"s({lvl u})"
  | .max a b   => s!"M({lvl a},{lvl b})"
  | .imax a b  => s!"I({lvl a},{lvl b})"
  | .param n   => s!"P({n.toString})"
  | .mvar id   => s!"V({id.name.toString})"

def optLevel : Option Level → String
  | none   => "none"
  | some l => lvl l

def optNat : Option Nat → String
  | none   => "none"
  | some n => toString n

def ordStr : Ordering → String
  | .lt => "lt" | .eq => "eq" | .gt => "gt"

/-- KVMaps built by insert sequences; insertion order IS the value upstream. -/
def kvmaps : List (String × KVMap) :=
  [ ("empty",   {})
  , ("one_nat", (KVMap.empty.insert `a (.ofNat 7)))
  , ("mixed",   ((KVMap.empty.insert `a (.ofString "s")).insert `b (.ofBool true)).insert `c (.ofInt (-3)))
  , ("replaced", ((KVMap.empty.insert `a (.ofNat 1)).insert `b (.ofBool false)).insert `a (.ofNat 2))
  , ("named",   (KVMap.empty.insert `k (.ofName (.str (.str .anonymous "x") "y"))))
  ]

/-- Sources whose byte positions are wire-visible through diagnostics later. -/
def sources : List (String × String) :=
  [ ("empty",      "")
  , ("one_line",   "abc")
  , ("two_lines",  "ab\ncd")
  , ("crlf",       "ab\r\ncd")
  , ("multibyte",  "héllo\nwörld")
  , ("trailing_nl","ab\n")
  , ("blank_line", "a\n\nb")
  ]

def main : IO Unit := do
  IO.println "# core_ext_observables.txt — GENERATED by scripts/extract/gen_core_ext_fixtures.lean."
  IO.println s!"# Oracle: leanprover/lean4 {Lean.versionString} commit {Lean.githash} (verified against SUITE.lock by the consuming test)."
  IO.println "# Regenerate with scripts/extract/gen_core_ext_fixtures.sh; never edit by hand (Rule D5)."
  IO.println "schema fln-core-ext-observables/1"

  -- Name ordering: quickCmp and quickLt over every ordered pair.
  for (la, a) in names do
    for (lb, b) in names do
      IO.println s!"namecmp|{la}|{lb}|{ordStr (Name.quickCmp a b)}|{Name.quickLt a b}"

  -- Name rendering.
  for (l, n) in names do
    IO.println s!"namestr|{l}|{n.toString}"

  -- Hygiene hooks.
  for (l, n) in hygienicNames do
    IO.println s!"hygiene|{l}|{n.hasMacroScopes}|{n.eraseMacroScopes.toString}|{n.simpMacroScopes.toString}"

  -- appendCore over a few shapes.
  for (la, a) in names do
    for (lb, b) in names do
      IO.println s!"append|{la}|{lb}|{(a ++ b).toString}"

  -- Level operations outside the data word.
  for (l, lv) in levels do
    IO.println s!"lvlunary|{l}|{lv.isAlwaysZero}|{optNat lv.toNat}|{optLevel lv.dec}|{lvl (lv.addOffset 2)}|{lvl lv.normalize}"
  for (la, a) in levels do
    for (lb, b) in levels do
      IO.println s!"lvlbin|{la}|{lb}|{Level.geq a b}|{a.occurs b}|{lvl (mkLevelMax' a b)}|{lvl (mkLevelIMax' a b)}"

  -- KVMap: every typed getter, including absent-key and type-mismatch defaults.
  for (l, m) in kvmaps do
    let g := m.getString `a "DEF"
    let n := m.getNat `a 99
    let i := m.getInt `a (-99)
    let b := m.getBool `a true
    let nm := (m.getName `k .anonymous).toString
    IO.println s!"kvmap|{l}|{g}|{n}|{i}|{b}|{nm}|{m.size}"

  -- KVMap operations the getters do not reach on their own.
  for (l, m) in kvmaps do
    let erased := (m.erase `a)
    IO.println s!"kvmapops|{l}|{erased.size}|{(erased.find `a).isSome}|{(m.find `a).isSome}|{(m.find `zz).isSome}"

  -- DataValue.sameCtor across every pair of constructors.
  let dvs : List (String × DataValue) :=
    [ ("str", .ofString "s"), ("bool", .ofBool true), ("name", .ofName `n)
    , ("nat", .ofNat 1), ("int", .ofInt (-1)) ]
  for (la, a) in dvs do
    for (lb, b) in dvs do
      IO.println s!"sameCtor|{la}|{lb}|{a.sameCtor b}"

  -- FileMap: byte positions are UTF-8 offsets and are wire-visible.
  for (l, s) in sources do
    let fm := s.toFileMap
    IO.println s!"filemap|{l}|{fm.getLastLine}|{s.utf8ByteSize}"
    for line in [1:fm.getLastLine + 2] do
      IO.println s!"fileline|{l}|{line}|{(fm.lineStart line).byteIdx}"
    for i in [0:s.utf8ByteSize + 1] do
      let p : String.Pos.Raw := ⟨i⟩
      let pos := fm.toPosition p
      let back := fm.ofPosition pos
      IO.println s!"filepos|{l}|{i}|{pos.line}|{pos.column}|{back.byteIdx}"
