//! The pin's `protected` marks for the source seed's own constants (bead `fln-8xz8`).
//!
//! A headerless file is checked against the source seed, not an imported closure, so
//! the marks an import would activate (`crate::protected_names`) are absent unless the
//! seed carries them: without them `open Nat` makes the pin's `protected def Nat.add`
//! available as `add`, which the pin refuses ("Unknown identifier `add`").
//!
//! The marks are derived, never remembered: `protected.tsv` lists every seed constant
//! with its status at the pin under `import Init` (what a headerless file sees there),
//! and is generated by `scripts/extract/gen_seed_protected.sh` from the pinned `lean`
//! binary's own `isProtected`. Nothing here decides what is protected; it only reads
//! the table, and refuses a malformed one rather than reading it as fewer marks, which
//! would silently widen name resolution again.
use fln_core::name::Name;
use std::collections::BTreeSet;

const TABLE: &str = include_str!("protected.tsv");
const SCHEMA: &str = "schema fln-seed-protected/1";

/// A seed constant's status at the pin.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum PinStatus {
    /// The pin has the constant and marks it `protected`.
    Protected,
    /// The pin has the constant, unprotected.
    Unprotected,
    /// The pin has no constant of that name.
    Absent,
}

/// Why the checked-in table cannot be read.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProtectedTableError {
    MissingSchema,
    MalformedRow(usize),
    UnknownStatus(usize),
    UnsortedOrDuplicate(usize),
}

impl std::fmt::Display for ProtectedTableError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingSchema => write!(f, "seed protected table lacks `{SCHEMA}`"),
            Self::MalformedRow(line) => write!(f, "seed protected table line {line} is malformed"),
            Self::UnknownStatus(line) => {
                write!(f, "seed protected table line {line} has an unknown status")
            }
            Self::UnsortedOrDuplicate(line) => write!(
                f,
                "seed protected table line {line} is out of order or repeats a name"
            ),
        }
    }
}
impl std::error::Error for ProtectedTableError {}

/// Every row of the checked-in table: a seed constant and its status at the pin, in
/// the table's (byte-sorted) order.
pub fn seed_pin_statuses() -> Result<Vec<(Name, PinStatus)>, ProtectedTableError> {
    parse(TABLE)
}

/// The seed constants the pin marks `protected`, in the table's order.
pub fn seed_protected_names() -> Result<Vec<Name>, ProtectedTableError> {
    Ok(seed_pin_statuses()?
        .into_iter()
        .filter(|(_, status)| *status == PinStatus::Protected)
        .map(|(name, _)| name)
        .collect())
}

/// The table's spelling of a name: its components joined by `.`. A name it cannot
/// spell so that [`parse_name`] reads it back identically is `None`.
pub fn table_spelling(name: &Name) -> Option<String> {
    let spelled = name.to_display_string();
    (parse_name(&spelled).as_ref() == Some(name)).then_some(spelled)
}

fn parse_name(text: &str) -> Option<Name> {
    if text.is_empty()
        || text
            .split('.')
            .any(|part| part.is_empty() || part.chars().any(|c| c.is_whitespace()))
    {
        return None;
    }
    Some(Name::from_components(text.split('.')))
}

fn parse(table: &str) -> Result<Vec<(Name, PinStatus)>, ProtectedTableError> {
    let mut rows = Vec::new();
    let mut schema = false;
    let mut previous: Option<&str> = None;
    let mut seen = BTreeSet::new();
    for (index, line) in table.lines().enumerate() {
        let line_number = index + 1;
        if line.starts_with('#') {
            continue;
        }
        if !schema {
            if line != SCHEMA {
                return Err(ProtectedTableError::MissingSchema);
            }
            schema = true;
            continue;
        }
        let Some((spelled, status)) = line.split_once('\t') else {
            return Err(ProtectedTableError::MalformedRow(line_number));
        };
        let status = match status {
            "protected" => PinStatus::Protected,
            "unprotected" => PinStatus::Unprotected,
            "absent" => PinStatus::Absent,
            _ => return Err(ProtectedTableError::UnknownStatus(line_number)),
        };
        let name = parse_name(spelled).ok_or(ProtectedTableError::MalformedRow(line_number))?;
        // The generator sorts with `LC_ALL=C sort`: byte order, each name once.
        if previous.is_some_and(|previous| previous.as_bytes() >= spelled.as_bytes())
            || !seen.insert(name.clone())
        {
            return Err(ProtectedTableError::UnsortedOrDuplicate(line_number));
        }
        previous = Some(spelled);
        rows.push((name, status));
    }
    if !schema {
        return Err(ProtectedTableError::MissingSchema);
    }
    Ok(rows)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_checked_in_table_reads() {
        let rows = seed_pin_statuses().expect("the generated table reads");
        assert!(!rows.is_empty());
        assert!(
            rows.iter().any(
                |(name, status)| *name == Name::from_components(["Nat", "add"])
                    && *status == PinStatus::Protected
            ),
            "the pin marks Nat.add protected"
        );
    }

    /// The table was generated by the binary SUITE.lock pins: a pin bump fails here
    /// until `scripts/extract/gen_seed_protected.sh` regenerates the table.
    #[test]
    fn the_table_was_generated_by_the_pinned_reference() {
        let lock = include_str!("../../../../SUITE.lock");
        let pin = lock
            .lines()
            .find(|line| line.starts_with("reference "))
            .expect("SUITE.lock pins the Reference");
        let field = |key: &str| {
            pin.split_whitespace()
                .find_map(|word| word.strip_prefix(key))
                .expect("the Reference pin line has a tag and a commit")
        };
        let oracle = format!(
            "# Oracle: leanprover/lean4 {} commit {} (verified against SUITE.lock).",
            field("tag="),
            field("commit=")
        );
        assert!(
            TABLE.lines().any(|line| line == oracle),
            "the table was not generated by the pinned Reference ({oracle}); regenerate it"
        );
    }

    #[test]
    fn a_malformed_table_is_refused_never_read_as_fewer_marks() {
        let good = "# c\nschema fln-seed-protected/1\nA.b\tprotected\nA.c\tunprotected\n";
        assert_eq!(parse(good).unwrap().len(), 2);
        for (table, error) in [
            ("A.b\tprotected\n", ProtectedTableError::MissingSchema),
            ("# only a comment\n", ProtectedTableError::MissingSchema),
            (
                "schema fln-seed-protected/1\nA.b protected\n",
                ProtectedTableError::MalformedRow(2),
            ),
            (
                "schema fln-seed-protected/1\nA.b\tprivate\n",
                ProtectedTableError::UnknownStatus(2),
            ),
            (
                "schema fln-seed-protected/1\nA..b\tprotected\n",
                ProtectedTableError::MalformedRow(2),
            ),
            (
                "schema fln-seed-protected/1\nA.c\tprotected\nA.b\tprotected\n",
                ProtectedTableError::UnsortedOrDuplicate(3),
            ),
            (
                "schema fln-seed-protected/1\nA.b\tprotected\nA.b\tunprotected\n",
                ProtectedTableError::UnsortedOrDuplicate(3),
            ),
        ] {
            assert_eq!(parse(table), Err(error), "{table:?}");
        }
    }
}
